#!/usr/bin/env node
// Tests du panneau 🎫 tickets migré (RM2889) — porte RM2606/2883 (tickets ouverts), RM2757 (carte repliable), RM2619 (infobulles),
// RM1952/2830/2831 (triage ROI, étiquettes, lot par domaine), RM2807 (fan-out borné), RM2795 (marque d'épinglage).
"use strict";
const path = require("path"); const assert = require("assert"); const DIR = __dirname;
const settle = (ms) => new Promise(r => setTimeout(r, ms || 10));
function fakeElement(id) { const L = []; let inner = ""; const kids = {}; return { id, dataset: {}, style: {}, open: false, value: "", textContent: "", kids, get innerHTML() { return inner; }, set innerHTML(v) { inner = v; }, contains: () => true,
  querySelector(sel) { return kids[sel] || null; }, querySelectorAll(sel) { return Object.values(kids).filter(k => k.matches && k.matches(sel)); },
  addEventListener(t, f) { L.push([t, f]); }, removeEventListener(t, f) { const i = L.findIndex(([a, b]) => a === t && b === f); if (i >= 0) L.splice(i, 1); }, get listenerCount() { return L.length; },
  async fire(type, target) { for (const [t, f] of [...L]) if (t === type) await f({ target, preventDefault() {}, stopPropagation() {} }); },
  async click(action, data) { const n = { dataset: { action, ...(data || {}) }, closest: (s) => (s === "[data-action]" || s === '[data-action="open"]' && action === "open") ? n : null }; for (const [t, f] of [...L]) if (t === "click") await f({ target: n, preventDefault() {}, stopPropagation() {} }); return n; } }; }
(async () => {
  const O = await import(path.join(DIR, "src/modules/tickets/openedTickets.js"));
  const TR = await import(path.join(DIR, "src/modules/tickets/triage.js"));
  const B = await import(path.join(DIR, "src/modules/tickets/briefs.js"));
  const { TicketsPanelRepository } = await import(path.join(DIR, "src/modules/tickets/TicketsPanelRepository.js"));
  const { TicketsPanelService } = await import(path.join(DIR, "src/modules/tickets/tickets.service.js"));
  const VM = await import(path.join(DIR, "src/modules/tickets/TicketsPanelViewModel.js"));
  const V = await import(path.join(DIR, "src/modules/tickets/TicketsPanel.view.js"));
  const { mountTicketsPanel } = await import(path.join(DIR, "src/modules/tickets/tickets.controller.js"));
  // — RM2606 : liste, ordre —
  assert.deepStrictEqual(O.openedAdd([], "2606"), ["2606"]); assert.deepStrictEqual(O.openedAdd(["2605"], "2606"), ["2606", "2605"]); assert.deepStrictEqual(O.openedAdd(["2605", "2606"], "2605"), ["2605", "2606"]);
  assert.deepStrictEqual(O.openedAdd([], "abc"), []); assert.deepStrictEqual(O.openedAdd(null, "1"), ["1"]); assert.deepStrictEqual(O.openedAdd(["1", "2", "3"], "4", 3), ["4", "1", "2"]);
  assert(O.ticketStatusRank("a_corriger") < O.ticketStatusRank("en_cours") && O.ticketStatusRank("en_cours") < O.ticketStatusRank("a_faire") && O.ticketStatusRank("a_faire") < O.ticketStatusRank("ferme") && O.ticketStatusRank("statut_exotique") < O.ticketStatusRank("ferme"));
  // — RM2883 : familles —
  for (const st of ["nouveau", "a_etudier_chiffrer", "etude_chiffrage_en_cours", "etude_chiffrage_a_valider", "a_faire", "en_cours", "a_tester_dev", "a_tester_demandeur", "a_mep", "en_mep", "en_pause", "a_corriger", "ferme"]) assert.notStrictEqual(O.ticketStatusFamily(st), "autre", "statut NORMS sans famille : " + st);
  assert.strictEqual(O.ticketStatusFamily("statut_exotique"), "autre"); assert.strictEqual(O.ticketStatusFamily("a_mep"), "mep"); assert.strictEqual(O.ticketStatusFamily("a_corriger"), "todo");
  const tabs = O.statusFamilyTabs([{ status: "en_cours" }, { status: "en_cours" }, { status: "ferme" }]); assert.deepStrictEqual(tabs.map(t => [t.key, t.n]), [["encours", 2], ["ferme", 1]]); assert.strictEqual(O.statusFamilyTabs([]).length, 0);
  const tkCache = { "1": { found: true, client: "acme", project: "shop", title: "A", status: "ferme" }, "2": { found: true, client: "acme", project: "shop", title: "B", status: "en_cours" }, "3": { found: true, client: "beta", project: "api", title: "C", status: "a_faire" } };
  const g = O.groupOpenedTickets(["1", "2", "3", "9"], tkCache, null); assert.deepStrictEqual(g.keys, ["acme/shop", "beta/api", "…"]); assert.deepStrictEqual(g.groups.get("acme/shop").map(x => x.rm_id), ["2", "1"]); assert.deepStrictEqual(g.clients, ["acme", "beta"]); assert.strictEqual(g.groups.get("…")[0].resolved, false);
  assert.deepStrictEqual(O.groupOpenedTickets(["1", "2", "3"], tkCache, "beta").keys, ["beta/api"]); assert.deepStrictEqual(O.groupOpenedTickets([], {}, null).keys, []); assert.deepStrictEqual(O.groupOpenedTickets(null, null, null).keys, []);
  const fs2883 = O.groupOpenedTickets(["1", "2", "3"], tkCache, null, "encours"); assert.deepStrictEqual(fs2883.keys, ["acme/shop"]); assert.deepStrictEqual(fs2883.groups.get("acme/shop").map(x => x.rm_id), ["2"]); assert(fs2883.families.length > 1, "les familles se calculent AVANT le filtre statut"); assert.deepStrictEqual(O.groupOpenedTickets(["1"], tkCache, null, "encours").keys, []);
  // — RM2757 —
  for (const v of [null, undefined, "", "0"]) assert.strictEqual(O.openedPanelOpen(v), false); assert.strictEqual(O.openedPanelOpen("1"), true);
  assert.strictEqual(O.openedCountLabel(12), "(12)"); assert.strictEqual(O.openedCountLabel(0), "(vide)"); assert.strictEqual(O.openedCountLabel(null), "(vide)"); assert.strictEqual(O.openedCountLabel("7"), "(7)"); assert.strictEqual(O.openedCountLabel(3, 40), "(3 / 40)"); assert.strictEqual(O.openedCountLabel(40, 40), "(40)"); assert.strictEqual(O.openedCountLabel(0, 40), "(vide)");
  console.log("✓ tickets ouverts (RM2606/2883/2757) : sans doublon, ordre de lecture, familles, groupes, carte repliée par défaut");
  // — la carte rendue —
  const openedHtml = (e) => String(V.OpenedList(new VM.OpenedViewModel(Object.assign({ ids: ["1", "2", "3", "9"], cache: tkCache, client: null, family: null }, e)), { tip: (id) => ' data-tip-rm="' + id + '" title="t"', pin: (k, key) => '<span class="pinmark">📌' + key + '</span>' }));
  assert(/Aucun ticket ouvert pour l'instant/.test(openedHtml({ ids: [] })));
  const h = openedHtml({}); assert(/data-action="client" data-client="">tous<\/button>/.test(h) && /data-client="acme"/.test(h) && /data-client="beta"/.test(h) && /data-action="clear"/.test(h), "filtre client proposé quand plusieurs clients");
  assert(/data-action="family" data-family="encours">en cours \(1\)/.test(h) && /data-family="ferme">fermé \(1\)/.test(h) && /data-family="todo">à faire \(1\)/.test(h), "RM2883 : un bouton par famille présente, avec son compte");
  assert(/acme\/shop \(2\)/.test(h) && /en cours de résolution \(1\)/.test(h) && /class="oline otix" data-action="open" data-rm="2"/.test(h) && /data-tip-rm="2"/.test(h) && /📌2/.test(h) && /data-action="forget" data-rm="2"/.test(h) && /class="otix-title">B</.test(h) && /chargement…/.test(h), "RM2637 : deux lignes, RM2795 : marque d'épinglage, RM2619 : infobulle");
  assert(!/onclick=/.test(h)); assert(/aucun ticket dans ce filtre — « tous » les ramène/.test(openedHtml({ ids: ["1"], family: "encours" })), "RM2883 : filtre vide annoncé");
  assert(!/data-action="client"/.test(openedHtml({ ids: ["1", "2"] })) && /data-action="clear"/.test(openedHtml({ ids: ["1", "2"] })), "un seul client : pas de barre client, mais « vider »");
  const vm1 = new VM.OpenedViewModel({ ids: ["1", "2", "3"], cache: tkCache, client: "acme" }); assert.strictEqual(vm1.countLabel, "(2 / 3)"); assert.strictEqual(new VM.OpenedViewModel({ ids: ["1"], cache: tkCache }).countLabel, "(1)");
  // — RM2619 : infobulles —
  const tip = B.ticketTipText("2619", { found: true, title: "Cache des tickets", status: "en_cours", completion_pct: 40, type: "feature", priority: "high", client: "iprospective", project: "pm-ai-agents" });
  assert(/RM2619 — Cache des tickets/.test(tip) && /en_cours/.test(tip) && /40 %/.test(tip) && /iprospective\/pm-ai-agents/.test(tip) && /priorité high/.test(tip)); assert(!/priorité normal/.test(B.ticketTipText("1", { found: true, priority: "normal" })));
  assert(/chargement/.test(B.ticketTipText("42", null)) && /inconnu/.test(B.ticketTipText("42", { found: false })) && /sans titre/.test(B.ticketTipText("42", { found: true, title: "" })) && /0 %/.test(B.ticketTipText("42", { found: true, completion_pct: 0 })));
  assert.deepStrictEqual(B.pendingBriefIds(["1", "2"], {}, new Set()), ["1", "2"]); assert.deepStrictEqual(B.pendingBriefIds(["1", "2"], { "1": {} }, new Set()), ["2"]); assert.deepStrictEqual(B.pendingBriefIds(["1", "2"], {}, new Set(["1"])), ["2"]); assert.deepStrictEqual(B.pendingBriefIds(["3", "3", "3"], {}, new Set()), ["3"]); assert.deepStrictEqual(B.pendingBriefIds(["abc", "", null, "12"], {}, new Set()), ["12"]); assert.deepStrictEqual(B.pendingBriefIds(null, null, null), []); assert.deepStrictEqual(B.pendingBriefIds(["9"], { "9": { found: false } }, new Set()), []);
  // le dépôt : demandes groupées en UNE requête, id absent mis en cache comme introuvable, échec non fatal
  const calls = []; const realFetch = globalThis.fetch; let failNext = false;
  globalThis.fetch = async (url) => { calls.push(String(url)); if (failNext) { failNext = false; throw new Error("réseau"); } return { ok: true, status: 200, headers: { get: () => "application/json" }, json: async () => (/\/triage/.test(url) ? { tickets: [{ rm_id: 1, client: "iprospective", project: "atlas", title: "un", status: "a_faire", priority: "high", score: 200, awaiting_validation: false, tags: ["front"] }, { rm_id: 2, client: "iprospective", project: "infra", title: "deux", status: "a_mep", priority: "normal", score: 5, awaiting_validation: true }, { rm_id: 3, client: "calicote", project: "prestashop", title: "trois", status: "en_cours", priority: "normal", score: 9, awaiting_validation: false, tags: ["bdd"] }] } : { tickets: { "7": { found: true, title: "Sept", status: "en_cours" } } }), text: async () => "{}" }; };
  const repo = new TicketsPanelRepository({ delay: 1 }); let loads = 0;
  assert.strictEqual(repo.requestBriefs(["7", "8", "7"], () => loads++), true); assert.strictEqual(repo.requestBriefs(["8", "9"], () => loads++), false, "pendant le délai : la file grossit, pas de second appel"); await settle(20);
  assert.strictEqual(calls.filter(u => /ticket\/brief/.test(u)).length, 1, "UNE requête pour tout ce qui était affiché"); assert(/ids=7%2C8%2C9/.test(calls[0]) && loads === 1); assert.deepStrictEqual(repo.brief("7"), { found: true, title: "Sept", status: "en_cours" }); assert.deepStrictEqual(repo.brief("8"), { found: false, rm_id: "8" }, "absent de la réponse : mis en cache introuvable, jamais redemandé");
  assert.strictEqual(repo.requestBriefs(["7", "8", "9"]), false, "tout est connu : rien à demander"); failNext = true; repo.requestBriefs(["10"]); await settle(20); assert(repo.brief("10").error && !repo.inflight.size, "échec : marqué, plus en vol");
  console.log("✓ infobulles (RM2619) : texte (attente ≠ inconnu), demandes groupées, une requête par lot, jamais en boucle");
  // — RM1952 / RM2830 / RM2831 : triage —
  const TT = [{ rm_id: 1, client: "iprospective", project: "atlas", awaiting_validation: false, tags: ["front", "refacto"] }, { rm_id: 2, client: "iprospective", project: "infra", awaiting_validation: true, tags: ["bdd"] }, { rm_id: 3, client: "calicote", project: "prestashop", awaiting_validation: false }];
  assert.strictEqual(TR.triageFilter(TT, "", "", false).length, 3); assert.strictEqual(TR.triageFilter(TT, "iprospective", "", false).length, 2); assert.strictEqual(TR.triageFilter(TT, "iprospective", "infra", false).length, 1); assert.strictEqual(TR.triageFilter(TT, "", "", true).length, 2); assert.strictEqual(TR.triageFilter(null, "", "", false).length, 0);
  assert.strictEqual(TR.triageFilter(TT, "", "", false, "front").map(t => t.rm_id).join(","), "1"); assert.strictEqual(TR.triageFilter(TT, "", "", false, "").length, 3, "aucune étiquette choisie → tout, y compris sans étiquette"); assert.strictEqual(TR.triageFilter(TT, "", "", false, "Front").map(t => t.rm_id).join(","), "1"); assert.strictEqual(TR.triageFilter(TT, "iprospective", "infra", false, "bdd").map(t => t.rm_id).join(","), "2");
  assert.deepStrictEqual(TR.triageClients(TT), ["calicote", "iprospective"]); assert.deepStrictEqual(TR.triageProjects(TT, "iprospective"), ["atlas", "infra"]); assert.deepStrictEqual(TR.triageProjects(TT, ""), ["atlas", "infra", "prestashop"]);
  const TB = [{ rm_id: "10", status: "a_faire", title: "un" }, { rm_id: "11", status: "en_cours", title: "deux" }, { rm_id: "12", status: "ferme", title: "trois" }];
  const items = TR.triageBatchItems(TB, 10); assert.strictEqual(items.map(i => i.rm_id).join(","), "10,11,12"); assert.strictEqual(items[0].status, "a_faire"); assert.strictEqual(items[0].title, "un"); assert.deepStrictEqual(items[0].points, []); assert.strictEqual(TR.triageBatchItems(TB, 2).length, 2); assert.strictEqual(TR.triageBatchItems([], 10).length, 0); assert.strictEqual(TR.triageBatchItems(null, 10).length, 0);
  const tri = (e) => String(V.TriageList(new VM.TriageViewModel(e)));
  const row = String(V.TriageRow(new VM.TriageViewModel({ tickets: [] }).row({ rm_id: 42, title: "Fix <b>x</b>", status: "nouveau", priority: "high", score: 200, time_minutes: 90, unblocks: 3, blocked: true, blocked_by: [7, 8], awaiting_validation: false }, 1)));
  assert(/data-action="open" data-rm="42"/.test(row) && /tr-score[^>]*>200</.test(row) && />RM42</.test(row) && /🔓 3/.test(row) && /tr-blocked/.test(row) && /bloqué par : 7, 8/.test(row) && /Fix &lt;b&gt;x&lt;\/b&gt;/.test(row) && !/<b>/.test(row) && /90 min/.test(row) && /tr-prio-high/.test(row) && !/onclick=/.test(row));
  const rv = String(V.TriageRow(new VM.TriageViewModel({ tickets: [] }).row({ rm_id: 9, title: "v", status: "a_mep", priority: "normal", score: 5, awaiting_validation: true }, 2))); assert(/⏳/.test(rv) && !/🔓/.test(rv));
  assert(/aucun ticket ouvert avec ces filtres/.test(tri({ tickets: TT, client: "zzz" }))); assert(/3 ticket\(s\) · triés par levier ROI/.test(tri({ tickets: TT })));
  const many = Array.from({ length: 70 }, (_, i) => ({ rm_id: i + 1, score: 1, title: "t" })); const tm = tri({ tickets: many }); assert(/… 10 de plus \(affine les filtres\)/.test(tm) && (tm.match(/class="tr-row"/g) || []).length === 60, "plafonné à 60 lignes, le reste annoncé");
  console.log("✓ triage (RM1952/2830/2831) : filtres cumulables, étiquette normalisée, lot plafonné, ligne échappée, liste bornée");
  // — le contrôleur —
  const triage = fakeElement("triagecard"), opened = fakeElement("openedcard"), badge = fakeElement("ln-tickets");
  const list = fakeElement("triage-list"), box = fakeElement("openedbox"), cnt = fakeElement("opened-count"), spawnBtn = fakeElement("tr-spawn");
  const sel = (id) => Object.assign(fakeElement(id), { value: "" }); const cs = sel("tr-client"), ps = sel("tr-project"), tg = sel("tr-tag"), hv = Object.assign(fakeElement("tr-hidevalid"), { type: "checkbox", checked: false });
  Object.assign(triage.kids, { "#triage-list": list, "#tr-client": cs, "#tr-project": ps, "#tr-tag": tg, "#tr-hidevalid": hv, "#tr-spawn": spawnBtn }); Object.assign(opened.kids, { "#openedbox": box, "#opened-count": cnt });
  const store = { data: { karlOpenedTickets: JSON.stringify(["2", "3"]), karlOpenedCard: "1" }, getItem(k) { return this.data[k] === undefined ? null : this.data[k]; }, setItem(k, v) { this.data[k] = String(v); } };
  const ev = []; const resolve = Object.assign({}, tkCache); const inflight = {};
  const T = { inFlight: (t) => !!inflight[t], ensureResolved: async (rm) => { ev.push(["resolve", rm]); inflight[rm] = true; await settle(5); delete inflight[rm]; resolve[rm] = { found: true, client: "acme", project: "shop", title: "T" + rm, status: "en_cours" }; return resolve[rm]; } };
  const svc = new TicketsPanelService({ repo, storage: store });
  const ctr = mountTicketsPanel({ triage, opened, badge }, { ticket: T, service: svc, notify: (m, e) => ev.push(["toast", m, !!e]), root: { querySelectorAll: () => [] }, resolve: () => resolve, showTicket: (id) => ev.push(["show", id]), pinOf: () => "", clientContext: () => "iprospective", spawnBatch: async (items, btn, opts) => ev.push(["spawn", items.map(i => i.rm_id), opts]) });
  assert.strictEqual(opened.open, true, "RM2757 : l'utilisateur l'avait dépliée → rouverte"); assert.deepStrictEqual(ctr.opened(), ["2", "3"], "liste restaurée du stockage"); assert.strictEqual(badge.textContent, "2"); assert.strictEqual(cnt.textContent, "(2)"); assert(/data-rm="2"/.test(box.innerHTML) && /data-rm="3"/.test(box.innerHTML));
  opened.open = false; await opened.fire("toggle", opened); assert.strictEqual(store.data.karlOpenedCard, "0", "le geste est mémorisé");
  ctr.noteOpened("RM99" === "x" ? "" : "99"); assert.deepStrictEqual(ctr.opened(), ["99", "2", "3"]); assert.strictEqual(JSON.parse(store.data.karlOpenedTickets)[0], "99", "persistée"); assert(ev.some(x => x[0] === "resolve" && x[1] === "99"), "un ticket inconnu est résolu"); assert(/chargement…/.test(box.innerHTML));
  const n = ev.filter(x => x[0] === "resolve").length; ctr.noteOpened("99"); ctr.renderOpened(); assert.strictEqual(ev.filter(x => x[0] === "resolve").length, n, "RM2807 : pas de second .then pendant le vol"); await settle(20); assert(/T99/.test(box.innerHTML), "…et le titre arrive");
  await box.click("open", { rm: "2" }); assert(ev.some(x => x[0] === "show" && x[1] === "2")); await box.click("client", { client: "acme" }); assert.strictEqual(ctr.state.client, "acme"); assert.strictEqual(cnt.textContent, "(2 / 3)", "RM2883 : vu / total avec un filtre");
  await box.click("family", { family: "ferme" }); assert(/data-rm="1"/.test(box.innerHTML) === false && /aucun ticket dans ce filtre|data-rm="2"/.test(box.innerHTML)); await box.click("forget", { rm: "3" }); assert.deepStrictEqual(ctr.opened(), ["99", "2"]); await box.click("clear"); assert.deepStrictEqual(ctr.opened(), []); assert.strictEqual(badge.style.display, "none"); assert.strictEqual(ctr.state.client, null);
  // triage : dépliage → chargement, filtres remplis (contexte client par défaut), lignes rendues, lot = ce qui est affiché
  triage.open = true; await triage.fire("toggle", triage); await settle(20); assert.strictEqual(calls.filter(u => /\/triage/.test(u)).length, 1); assert(/selected>iprospective</.test(cs.innerHTML), "RM2639 : le contexte client pré-sélectionne"); assert(/atlas/.test(ps.innerHTML) && /infra/.test(ps.innerHTML));
  assert(/tr-row/.test(list.innerHTML) && /3 ticket\(s\)/.test(list.innerHTML), "sans filtre appliqué (valeur du select factice vide) : tout"); assert.strictEqual(spawnBtn.style.display, ""); assert.strictEqual(ctr.triageRows().length, 3);
  cs.value = "calicote"; await triage.fire("change", cs); assert.strictEqual(ctr.triageRows().length, 1); assert(/prestashop/.test(ps.innerHTML) && !/atlas/.test(ps.innerHTML), "les projets suivent le client"); hv.checked = true; cs.value = ""; await triage.fire("change", hv); assert.strictEqual(ctr.triageRows().length, 2, "masquer la validation");
  tg.value = "front"; await triage.fire("change", tg); assert.strictEqual(ctr.triageRows().map(r => r.rm_id).join(","), "1", "RM2830 : étiquette");
  await triage.click("spawn"); assert(ev.some(x => x[0] === "spawn" && x[1].join(",") === "1" && x[2].titre === "Ouvrir une session sur ce lot" && x[2].reste === ""), "RM2831 : ce qui est affiché EST le lot");
  tg.value = "zzz"; await triage.fire("change", tg); assert.strictEqual(spawnBtn.style.display, "none"); assert(/aucun ticket ouvert avec ces filtres/.test(list.innerHTML)); await triage.click("spawn"); assert(ev.some(x => x[0] === "toast" && /aucun ticket dans cette liste/.test(x[1])));
  triage.open = true; await triage.fire("toggle", triage); assert.strictEqual(calls.filter(u => /\/triage/.test(u)).length, 1, "redéplier ne recalcule pas"); await triage.click("reload"); await settle(20); assert.strictEqual(calls.filter(u => /\/triage/.test(u)).length, 2, "↻ recalcule");
  const attr = ctr.tipAttr("RM7"); assert(/data-tip-rm="7"/.test(attr) && /title="RM7 — Sept/.test(attr)); assert.strictEqual(ctr.tipAttr("slug"), ""); assert(/chargement…/.test(ctr.tipAttr("77")));
  globalThis.fetch = realFetch;
  ctr.unmount(); assert.strictEqual(box.listenerCount + list.listenerCount + triage.listenerCount + opened.listenerCount, 0);
  console.log("✓ contrôleur : carte restaurée et mémorisée, liste persistée, fan-out borné, filtres, triage chargé au dépliage, lot affiché");
  console.log("\nTous les tests du panneau tickets passent.");
})().catch(e => { console.error("✗", e.message); process.exit(1); });
