#!/usr/bin/env node
// Tests du domaine worklog — VIEWMODELS et VUES (RM3019, scindé de test_cockpit_worklog.js) : ligne de MR RM2723, panneau (notifications,
// sous-onglets, lignes de ticket, groupes, dérive, étape MR, documents), écrans de lot (traiter, merger, fermer).
"use strict";
const path = require("path"); const assert = require("assert"); const DIR = __dirname;
const { settle, escO, fakeElement, CFG, SEL, W } = require("./test_cockpit_worklog.helpers.js");
(async () => {
  const M = await import(path.join(DIR, "src/modules/worklog/worklog.js"));
  const VM = await import(path.join(DIR, "src/modules/worklog/WorklogViewModel.js"));
  const V = await import(path.join(DIR, "src/modules/worklog/Worklog.view.js"));

  // — vue —
  const mr = String(V.MrLine(VM.mrLine({ iid: 571, ref: "RM2720", target: "dev", url: "https://gl.x/g/p/-/merge_requests/571" }))); assert(/!571/.test(mr) && /RM2720/.test(mr) && /→ <span class="pill">dev<\/span>/.test(mr) && /ouvrir ↗/.test(mr) && /data-action="merge-one" data-url="https:\/\/gl.x\/g\/p\/-\/merge_requests\/571" data-iid="571" data-target="dev">⇥ merger</.test(mr) && !/onclick=/.test(mr), "RM2723 : la MR est désignée par son URL");
  const mrNo = String(V.MrLine(VM.mrLine({ iid: 12, target: "dev" }))); assert(!/merge-one/.test(mrNo) && /!12/.test(mrNo), "sans URL : pas de bouton"); assert(/session éteinte/.test(String(V.MrLine(VM.mrLine({ iid: 3, url: "u", alive: false }))))); assert(!/<img|<i>/.test(String(V.MrLine(VM.mrLine({ iid: "<img src=x>", ref: '"><b>', target: "<i>", url: "https://gl.x/9" })))), "iid, ref, cible échappés");
  const pane = (e, sub) => String(V.WorklogPane(new VM.WorklogViewModel(Object.assign({ data: W, attached: "42", branches: ["1-ma-branche", "orpheline"], selected: new Set(["RM1"]), sub: sub || "todo" }, e), { ago: () => "2min" }), { tip: (id) => ' data-tip-rm="' + id + '"', pin: (k, key) => "<pin>" + key + "</pin>", linkify: (s) => "<lk>" + escO(s) + "</lk>" }));
  assert.strictEqual(pane({ attached: null }), "", "sans session : rien");
  let h = pane({});
  assert(/🔔 notifications de la session \(2\) <span class="otag"[^>]*>2 traitées<\/span>/.test(h) && /class="oline oq ounres"[^>]*title="t1">🔴 <span class="otag">critical<\/span><span class="pill">hook<\/span> <b>RM1<\/b> boum &lt;b&gt;/.test(h) && h.indexOf("🔔") < h.indexOf("🔀") && h.indexOf("🔀") < h.indexOf("📥") && h.indexOf("📥") < h.indexOf('class="rsub"'), "RM2466 : incidents, MR, demandes AVANT le travail, échappés");
  // RM3074 : la tête ne LISTE plus les MR (le détail est dans l'onglet) — elle rappelle combien il en reste, et y mène.
  assert(/📥 <span class="otag">#3<\/span> fais &lt;x&gt;/.test(h) && /🔀 <b>1<\/b> MR à merger/.test(h) && /data-action="sub" data-key="mrs"/.test(h));
  assert(/<div class="rsub"><button class="active" data-action="sub" data-key="todo">⏳ reste à faire \(2\)<\/button><button class="" data-action="sub" data-key="done">✅ fait \(2\)<\/button><button class="" data-action="sub" data-key="mrs">🔀 MR \(1\)<\/button><button class="" data-action="sub" data-key="documents">📄 documents \(2\)<\/button><\/div>/.test(h), "RM2610 : sous-onglets par statut + MR (RM3074) + documents");
  assert(/<input type="checkbox"[^>]*data-action="toggle" data-ref="RM1" data-status="a_faire" data-label="Un &lt;b&gt;" checked>/.test(h) && /<pin>1<\/pin><span class="rmref" data-tip-rm="1" data-action="ticket" data-rm="1">RM1<\/span>/.test(h) && /data-action="status" data-ref="RM1"><span class="pill">a_faire<\/span><\/span>/.test(h), "ligne ticket : case cochée, marque, numéro cliquable + infobulle, pastille → menu de statut (RM2888)");
  assert(/<span class="pill" title="branche du ticket">⎇ 1-ma-branche<\/span>/.test(h) && /→ suite/.test(h) && /↳ n/.test(h) && /<span class="pill " title="critères d’acceptation cochés">1\/2 ✓<\/span><span class="wl-crit"[^>]*>☐ reste</.test(h), "RM2591/2695 : branche, suite, note, avancement");
  assert(/<b>libre-x<\/b> <span class="pill">\?<\/span>/.test(h) && !/data-ref="libre-x"[^>]*type="checkbox"/.test(h) && !/data-action="status" data-ref="libre-x"/.test(h), "RM2605/2716/2888 : un chantier libre n'est ni un lien, ni cochable, ni un workflow");
  assert(/🌿 autres branches \(1\)[\s\S]*⎇ orpheline/.test(h), "RM2610 : branches orphelines sous « à faire »"); assert(!/onclick=/.test(h));
  h = pane({}, "done"); assert(/<div class="wlgroup"><div class="wlghead">c \/ p <span class="gcnt">1<\/span><\/div>/.test(h) && /class="wlghead">d \/ q/.test(h), "RM2798 : deux projets → groupes délimités"); assert(/<span class="pill warn" title="Statut modifié hors de cette session : en_cours → a_tester_demandeur">a_tester_demandeur<\/span>/.test(h), "RM2796 : la dérive en couleur, le détail au survol"); assert(/<span class="pill warn" style="cursor:pointer" title="MR ouverte, à merger" data-action="mr-stage" data-url="https:\/\/g\/mr\/2">⇥ MR<\/span>/.test(h), "RM2801 : l'étape de MR sur la ligne");
  h = pane({ data: Object.assign({}, W, { buckets: { todo: [W.buckets.todo[0]] } }) }, "todo"); assert(!/wlghead/.test(h) && /data-ref="RM1"/.test(h), "RM2798 : un seul groupe → pas d'en-tête"); assert(/wlghead">hors projet/.test(pane({}, "todo")), "…un chantier libre à côté d'un ticket de projet forme le groupe « hors projet »");
  h = pane({}, "documents"); assert(/<span class="olink" title="Ouvrir la fiche RM1" data-action="ticket" data-rm="1">RM1<\/span>/.test(h) && /📄 <lk>docs\/cdc.md<\/lk> <span class="pill">output<\/span>/.test(h) && /<lk>memory: x.md<\/lk>/.test(h) && !/'memory/.test(h), "RM2935 : documents cliquables par linkify, quotes YAML retirées");
  h = pane({ data: { found: false, buckets: {} }, branches: [] }); assert(/pas de worklog pour cette session/.test(h)); assert(/aucun ticket ouvert dans cette session/.test(pane({ data: { found: true, buckets: {} }, branches: [] }))); assert(/🌿 autres branches \(1\)/.test(pane({ data: { found: true, buckets: {}, docs: {} }, branches: ["x"] }, "documents")), "seules des branches : l'onglet à faire les accueille (RM2610)");
  const vmF = new VM.WorklogViewModel({ data: W, attached: "42" }, { ago: () => "2min" }); assert.strictEqual(vmF.fresh, "vérifié 2min", "RM2581 : fraîcheur"); assert.strictEqual(new VM.WorklogViewModel({ data: W, attached: null }, { ago: () => "x" }).fresh, "");
  const PLAN = { count: 2, prompt: "consigne <x>", todo: [{ rm_id: "10", status: "a_faire", title: "dev", instruction: "traiter puis livrer", points: ["critère A", 'crit "B"'], points_truncated: true }, { rm_id: "11", status: "a_etudier_chiffrer", title: "étude", instruction: "étudier et chiffrer" }], skipped: [{ rm_id: "12", status: "a_tester_demandeur", title: "chez toi", reason: "attend TON verdict" }] };
  const bp = String(V.BatchPlan(new VM.BatchPlanViewModel(PLAN), { envoi: "▶ envoyer à la session" })); assert(/▶ à traiter \(2\)/.test(bp) && /<b>1\.<\/b> <span class="r-id">RM10/.test(bp) && /traiter puis livrer/.test(bp) && /⊘ écartés \(1\)/.test(bp) && /attend TON verdict/.test(bp) && !/au-delà de 10/.test(bp) && /data-action="send-batch">▶ envoyer à la session</.test(bp) && /data-action="close">annuler/.test(bp) && /consigne &lt;x&gt;/.test(bp));
  assert((bp.match(/type="checkbox" checked/g) || []).length === 2 && /data-ref="10"/.test(bp) && /value="critère A"/.test(bp) && /value="crit &quot;B&quot;"/.test(bp) && /aucun coché = ticket écarté · ⚠ liste de critères incomplète/.test(bp), "RM2719 : points cochés par défaut, échappés, liste tronquée dite");
  assert(/au-delà de 10/.test(String(V.BatchPlan(new VM.BatchPlanViewModel({ todo: Array.from({ length: 12 }, (_, i) => ({ rm_id: String(i) })), skipped: [] }), { envoi: "x" })))); assert(/aucun ticket actionnable/.test(String(V.BatchPlan(new VM.BatchPlanViewModel({ todo: [], skipped: [] }), { envoi: "x" })))); assert(!/<img|<script>/.test(String(V.BatchPlan(new VM.BatchPlanViewModel({ todo: [{ rm_id: "1<b>", status: "<img src=x>", title: "<script>", instruction: "<b>i" }], skipped: [{ rm_id: "2", reason: "<script>" }] }), { envoi: "x" }))));
  const mbDev = String(V.MrBatch(new VM.MrBatchViewModel({ mode: "dev", live: [], skipped: [], runs: [{ rm_ids: ["10"], source: "10-x", target: "dev" }] }))); assert(/10-x → dev/.test(mbDev) && !/promotion emporte/.test(mbDev) && /data-action="send-mr"/.test(mbDev)); const mbProd = String(V.MrBatch(new VM.MrBatchViewModel({ mode: "prod", live: ["11"], skipped: [{ rm_id: "13", reason: "aucune branche" }], runs: [{ rm_ids: ["10", "11"], source: "dev", target: "main" }] }))); assert(/emporte TOUT ce que « dev »/.test(mbProd) && /dev → main/.test(mbProd) && /session encore vivante pour RM11/.test(mbProd) && /⊘ écartés \(1\)/.test(mbProd) && /aucune branche/.test(mbProd)); assert(/rien à merger/.test(String(V.MrBatch(new VM.MrBatchViewModel({ mode: "dev", runs: [] })))));
  const cp = String(V.ClosePlan(M.closeBatchPlan(SEL, CFG))); assert(/Seront fermés \(1\)/.test(cp) && /<b>RM3<\/b>/.test(cp) && /Écartés \(3\)/.test(cp) && /data-action="send-close"/.test(cp) && /pm-task-status-update/.test(cp)); assert(!/send-close/.test(String(V.ClosePlan(M.closeBatchPlan([{ rm_id: "1", status: "a_faire" }], CFG)))), "rien de fermable : pas de bouton");
  console.log("✓ vue : notifications avant le travail, sous-onglets, lignes de ticket complètes, groupes, dérive, étape MR, documents, écrans de lot");
  console.log("\nTous les tests des vues du worklog passent.");
})().catch(e => { console.error("✗", e.stack || e.message); process.exit(1); });
