#!/usr/bin/env node
// Tests des actions de session migrées (RM2889) — porte RM1893 §2 (chips), RM2720 (actions PM d'un ticket : cible, repli dit,
// {id} = le ticket), §3 (moniteurs, disposition des panes), RM2515 (menu de disposition + fermer), fermeture d'une session.
"use strict";
const path = require("path"); const assert = require("assert"); const DIR = __dirname;
function fakeEl(id, extra) { const L = []; let inner = ""; const self = Object.assign({ id, style: {}, value: "", dataset: {}, kids: {}, get innerHTML() { return inner; }, set innerHTML(v) { inner = v; }, insertAdjacentHTML(p, h) { inner += h; }, contains: () => true, querySelector(sel) { return self.kids[sel] || null; }, remove() { self.removed = true; },
  addEventListener(t, f) { L.push([t, f]); }, removeEventListener(t, f) { const i = L.findIndex(([a, b]) => a === t && b === f); if (i >= 0) L.splice(i, 1); }, get listenerCount() { return L.length; },
  async fire(type, target, extra2) { for (const [t, f] of [...L]) if (t === type) await f(Object.assign({ target, preventDefault() {}, stopPropagation() {} }, extra2 || {})); },
  async click(action, data) { const n = { dataset: Object.assign({ action }, data || {}), closest: () => n, disabled: false }; for (const [t, f] of [...L]) if (t === "click") await f({ target: n, preventDefault() {}, stopPropagation() {} }); return n; } }, extra || {}); return self; }
(async () => {
  const M = await import(path.join(DIR, "src/modules/actions/actions.js"));
  const KS = await import(path.join(DIR, "src/core/store.js")); const mkStore = (name, obj) => { const s = new KS.Store(name, { ttl: 1e9, max: 1000 }); Object.entries(obj || {}).forEach(([k, v]) => s.set(k, v)); return s; };   // RM3005
  const { ActionsService } = await import(path.join(DIR, "src/modules/actions/actions.service.js"));
  const VM = await import(path.join(DIR, "src/modules/actions/ActionsViewModel.js"));
  const V = await import(path.join(DIR, "src/modules/actions/Actions.view.js"));
  const { mountSessionActions } = await import(path.join(DIR, "src/modules/actions/actions.controller.js"));
  const SESS = { "123": { rm_id: "123" }, "77": { rm_id: "77" }, "88": { rm_id: "88", ghost: true } };
  const tOwn = M.pmActionTarget("123", SESS, "77"); assert(tOwn.sid === "123" && tOwn.own === true); const tF = M.pmActionTarget("999", SESS, "77"); assert(tF.sid === "77" && tF.own === false && /pas la session du ticket/.test(tF.why)); assert(M.pmActionTarget("999", SESS, null).sid === null && /aucune session/.test(M.pmActionTarget("999", SESS, null).why)); assert.strictEqual(M.pmActionTarget("88", SESS, null).sid, null, "un fantôme n'est pas une cible"); assert.strictEqual(M.pmActionTarget("999", {}, "77").sid, null);
  assert.strictEqual(M.actionMessage({ text: "passe RM{id} en cours pour {id}" }, "42"), "passe RM42 en cours pour 42", "RM2720 : {id} vaut le TICKET"); assert.strictEqual(M.actionMessage(null, "1"), "");
  const ACTS = [{ label: "État", text: "où en es-tu ?", group: "session" }, { label: "Fin", text: "termine", group: "session", enter: false }, { label: "→ en cours", text: "passe RM{id}", ticket_only: true }, { label: "Autre", text: "x", group: "divers" }];
  const chips = M.chipList(ACTS, "42"); assert.deepStrictEqual(chips.map(c => c.group !== undefined ? "G:" + c.group : c.i), ["G:session", 0, 1, "G:divers", 3], "les actions ticket_only ne sont pas dans la barre ; un groupe est annoncé une fois"); assert(/sans Enter/.test(chips[2].title) && chips[1].title === "où en es-tu ?"); assert.deepStrictEqual(M.pmActions(ACTS).map(a => a.label), ["→ en cours"]);
  assert.deepStrictEqual(M.dispositionItems("parke").map(d => [d.value, d.on]), [["a_traiter", false], ["parke", true], ["termine", false]]); assert(M.dispositionItems(null)[0].on, "défaut : à traiter"); assert.strictEqual(M.tmuxLabel("42"), "karl-RM42"); assert.strictEqual(M.tmuxLabel("slug"), "karl-slug");
  const cv = new VM.ChipsViewModel({ actions: ACTS, attached: "42" }); assert(cv.shown); const h = String(V.Chips(cv)); assert(/<span class="cgroup">session<\/span><button class="chip" title="où en es-tu \?" data-action="chip" data-i="0">État<\/button>/.test(h) && /data-i="1">Fin</.test(h) && !/en cours/.test(h) && !/onclick=/.test(h)); assert(!new VM.ChipsViewModel({ actions: ACTS, attached: null }).shown && !new VM.ChipsViewModel({ actions: [ACTS[2]], attached: "42" }).shown, "sans session ou sans action de session : rien");
  const dm = String(V.DispositionMenu(new VM.DispositionMenuViewModel({ session: { rm_id: "7", disposition: "termine" } }))); assert(/<button data-v="a_traiter">🟠 à traiter<\/button><button data-v="parke">🔖 parké<\/button><button data-v="termine" class="on">✅ terminé<\/button><div class="sep"><\/div><button data-kill="1">✕ fermer la session<\/button>/.test(dm)); assert.strictEqual(String(V.PresetOptions(["a", "b"], "📺 ")), '<option value="a">📺 a</option><option value="b">📺 b</option>');
  console.log("✓ modèle et vue (RM2720/1893/2515) : cible d'une action PM, {id} = ticket, chips sans actions de ticket, menu de disposition");
  const calls = []; const repo = { async send(sid, msg, enter) { calls.push(["send", sid, msg, enter]); }, async monitor(sid, p) { calls.push(["monitor", sid, p]); }, async unmonitor(sid) { calls.push(["unmonitor", sid]); }, async layout(sid, l) { calls.push(["layout", sid, l]); }, async disposition(sid, d) { calls.push(["disposition", sid, d]); }, async kill(sid) { calls.push(["kill", sid]); if (sid === "9") throw new Error("refusé"); } };
  const svc = new ActionsService({ repo }); assert.strictEqual(await svc.send(ACTS[0], "42", "42"), "Envoyé : État"); assert.deepStrictEqual(calls[0], ["send", "42", "où en es-tu ?", true]); assert.strictEqual(await svc.send(ACTS[1], "42", "42"), "Texte injecté — complète dans le terminal"); assert.strictEqual(calls[1][3], false);
  const chipsEl = fakeEl("chipsrow"), bar = fakeEl("tabactions"), mp = fakeEl("monpreset"), ls = fakeEl("layoutsel"); Object.assign(bar.kids, { "#monpreset": mp, "#layoutsel": ls });
  const ev = []; let att = "42"; let ok = true; const menus = [];
  const ctr = mountSessionActions({ chips: chipsEl, bar }, { service: svc, notify: (m, e) => ev.push(["toast", m, !!e]), confirm: (m) => { ev.push(["confirm", m]); return ok; }, attached: () => att, sess: () => mkStore("sess", { "42": { rm_id: "42" }, "5": { rm_id: "5" } }), cfg: () => ({ actions: ACTS, monitors: ["cpu", "logs"], layouts: ["even-h"] }), detach: () => ev.push("detach"), refreshSessions: () => ev.push("sessions"), refreshHealth: () => ev.push("health"), popover: () => { const m = fakeEl("dispmenu"); menus.push(m); return m; }, place: (m, a) => ev.push(["place", a]), onOutsideClick: (fn) => ev.push(["outside", typeof fn]) });
  ctr.renderChips(); assert(chipsEl.style.display === "flex" && /data-i="0">État</.test(chipsEl.innerHTML) && !/en cours/.test(chipsEl.innerHTML), "§2 : chips de la session attachée"); att = null; ctr.renderChips(); assert(chipsEl.style.display === "none" && chipsEl.innerHTML === ""); att = "42";
  ctr.renderChips(); calls.length = 0; await chipsEl.click("chip", { i: "1" }); assert.deepStrictEqual(calls[0], ["send", "42", "termine", false]); assert(ev.some(x => x[0] === "toast" && /Texte injecté/.test(x[1])), "un clic sur un chip envoie à la session attachée, {id} = la session");
  calls.length = 0; ev.length = 0; await ctr.sendPmAction(0, "5", null); assert.deepStrictEqual(calls[0], ["send", "5", "passe RM5", true]); assert(!ev.some(x => x[0] === "confirm"), "RM2720 : la session DU ticket → pas de confirmation");
  calls.length = 0; ev.length = 0; await ctr.sendPmAction(0, "999", null); assert(ev.some(x => x[0] === "confirm" && /pas la session du ticket/.test(x[1])) && calls[0][1] === "42" && calls[0][2] === "passe RM999", "…repli sur la session attachée : confirmé, {id} reste le ticket"); ok = false; calls.length = 0; await ctr.sendPmAction(0, "999", null); assert.strictEqual(calls.length, 0, "refus → rien"); ok = true;
  att = null; ev.length = 0; await ctr.sendPmAction(0, "999", null); assert(ev.some(x => x[0] === "toast" && /aucune session vivante/.test(x[1]) && x[2])); att = "42"; await ctr.sendPmAction(9, "5", null); assert.strictEqual(calls.length, 0, "action inconnue : rien");
  ctr.fillPresets(); assert(/<option value="cpu">📺 cpu<\/option><option value="logs">📺 logs<\/option>/.test(mp.innerHTML) && /<option value="even-h">even-h<\/option>/.test(ls.innerHTML), "§3 : presets depuis la config");
  calls.length = 0; mp.value = "cpu"; await bar.click("monitor-add"); assert.deepStrictEqual(calls[0], ["monitor", "42", "cpu"]); mp.value = ""; calls.length = 0; await bar.click("monitor-add"); assert.strictEqual(calls.length, 0, "sans preset : rien"); await bar.click("monitor-remove"); assert.deepStrictEqual(calls[0], ["unmonitor", "42"]);
  calls.length = 0; ls.value = "even-h"; await bar.fire("change", ls); assert.deepStrictEqual(calls[0], ["layout", "42", "even-h"]); assert.strictEqual(ls.value, "", "le sélecteur revient à « Disposition… »");
  ev.length = 0; ctr.openDispositionMenu({ rm_id: "7", disposition: "parke" }, { anchor: 1 }); const m = menus[menus.length - 1]; assert(/class="on">🔖 parké/.test(m.innerHTML) && ev.some(x => x[0] === "place") && ev.some(x => x[0] === "outside"), "RM2515 : popover ancré, disposition courante marquée, clic ailleurs referme");
  calls.length = 0; ev.length = 0; await m.fire("click", { closest: () => ({ dataset: { v: "termine" } }) }); assert.deepStrictEqual(calls[0], ["disposition", "7", "termine"]); assert(m.removed && ev.includes("sessions"), "choisir : envoyé, menu fermé, liste rafraîchie");
  ctr.openDispositionMenu({ rm_id: "42" }, {}); const m2 = menus[menus.length - 1]; calls.length = 0; ev.length = 0; await m2.fire("click", { closest: () => ({ dataset: { kill: "1" } }) }); assert(ev.some(x => x[0] === "confirm" && /karl-RM42/.test(x[1])) && calls.some(c => c[0] === "kill" && c[1] === "42") && ev.includes("detach") && ev.includes("sessions") && ev.includes("health") && m2.removed, "✕ fermer : confirmé, tuée, détachée (c'était la session attachée), rafraîchie");
  ev.length = 0; calls.length = 0; await ctr.kill("9"); assert(ev.some(x => x[0] === "toast" && x[1] === "refusé" && x[2]) && !ev.includes("detach")); ok = false; calls.length = 0; await ctr.kill("5"); assert.strictEqual(calls.length, 0, "refus de confirmation : rien"); ok = true;
  ctr.unmount(); assert.strictEqual(chipsEl.listenerCount + bar.listenerCount, 0);
  console.log("✓ contrôleur : chips → session attachée, actions PM → session du ticket ou repli confirmé, moniteurs/disposition des panes, menu RM2515, fermeture");
  console.log("\nTous les tests des actions de session passent.");
})().catch(e => { console.error("✗", e.message); process.exit(1); });
