#!/usr/bin/env node
// Tests du lanceur migré (RM2889) — porte §1 (résolution), RM1941 (modèles par moteur), RM2873 (consigne partagée), RM2818 (garde),
// spawn, §8 (saisie éclair), RM2639 (contexte client), RM2285 (réouverture), RM2173/2427 (aller au ticket).
"use strict";
const path = require("path"); const assert = require("assert"); const DIR = __dirname;
const settle = (ms) => new Promise(r => setTimeout(r, ms || 10));
function fakeEl(id, extra) { const L = []; let inner = ""; const self = Object.assign({ id, value: "", textContent: "", className: "", dataset: {}, options: [], kids: {}, get innerHTML() { return inner; }, set innerHTML(v) { inner = v; self.options = [...v.matchAll(/<option value="([^"]*)"/g)].map(m => ({ value: m[1] })); },
  querySelector(sel) { return self.kids[sel] || null; }, addEventListener(t, f) { L.push([t, f]); }, removeEventListener(t, f) { const i = L.findIndex(([a, b]) => a === t && b === f); if (i >= 0) L.splice(i, 1); }, get listenerCount() { return L.length; },
  async fire(type, target, extra2) { for (const [t, f] of [...L]) if (t === type) await f(Object.assign({ target, preventDefault() {} }, extra2 || {})); },
  async click(action) { const n = { dataset: { action }, closest: () => n }; for (const [t, f] of [...L]) if (t === "click") await f({ target: n, preventDefault() {} }); } }, extra || {}); return self; }
(async () => {
  const M = await import(path.join(DIR, "src/modules/launcher/launcher.js"));
  const { LauncherService } = await import(path.join(DIR, "src/modules/launcher/launcher.service.js"));
  const V = await import(path.join(DIR, "src/modules/launcher/Launcher.view.js"));
  const { mountLauncher } = await import(path.join(DIR, "src/modules/launcher/launcher.controller.js"));
  const PJ = [{ client: "iprospective", project: "pm-ai-agents", value: "iprospective/pm-ai-agents" }, { client: "acme", project: "site", value: "acme/site" }, { client: "iprospective", project: "infra", value: "iprospective/infra" }];
  assert.deepStrictEqual(M.clientCtxList(PJ), ["acme", "iprospective"]); assert.deepStrictEqual(M.clientCtxList([]), []); assert.strictEqual(M.clientCtxProject(PJ, "iprospective"), "iprospective/pm-ai-agents"); assert.strictEqual(M.clientCtxProject(PJ, "inconnu"), ""); assert.strictEqual(M.clientCtxProject(PJ, ""), "");
  const mo = M.modelOptions({ claude: ["opus", "sonnet"] }, "claude", { found: true, ai_model: "opus" }, "sonnet"); assert.deepStrictEqual(mo.options.map(o => o.value), ["ticket", "", "opus", "sonnet"]); assert.strictEqual(mo.options[0].label, "défini dans le ticket (opus)"); assert.strictEqual(mo.value, "sonnet", "le choix précédent survit s'il est encore valide");
  assert.strictEqual(M.modelOptions({ claude: ["opus"] }, "claude", null, "zzz").value, "ticket", "sinon la sentinelle « ticket », toujours sûre"); assert.strictEqual(M.modelOptions({}, "shell", null, "").options.length, 2); assert.strictEqual(M.modelOptions(null, "claude", { found: false, ai_model: "x" }, "").options[0].label, "défini dans le ticket");
  assert.strictEqual(M.resolvedLine(null), null); assert.deepStrictEqual(M.resolvedLine({ found: false }), { found: false, text: "⚠ ticket non trouvé en local — prompt générique", closed: false }); const rl = M.resolvedLine({ found: true, client: "acme", project: "site", title: "T", status: "ferme", cwd: "/w" }); assert(rl.found && rl.text === "✓ acme / site — T  [ferme]" && rl.closed && rl.cwd === "/w");
  assert.deepStrictEqual(M.spawnBody({ rm: "abc" }), { error: "RM id requis (entier)" }); assert.deepStrictEqual(M.spawnBody({ rm: " 42 ", engine: "claude", model: "", cwd: " ", prompt: "" }), { body: { rm_id: "42", engine: "claude" }, rm: "42" }); assert.deepStrictEqual(M.spawnBody({ rm: "42", engine: "vibe", model: "m", cwd: "/w", prompt: " go " }).body, { rm_id: "42", engine: "vibe", model: "m", cwd: "/w", prompt: "go" });
  assert.deepStrictEqual(M.ticketBody({ title: "  " }), { error: "Titre requis" }); assert.deepStrictEqual(M.ticketBody({ title: " T ", project: "a/b", type: "feature", priority: "normal", tags: " ci ", description: " d " }).body, { title: "T", project: "a/b", type: "feature", priority: "normal", tags: "ci", description: "d" });
  assert.deepStrictEqual(M.typeOptions({ task_types: [{ value: "feature" }, { value: "bug", label: "Bug" }] }), [{ value: "feature", label: "feature", selected: true }, { value: "bug", label: "Bug", selected: false }]); assert.strictEqual(M.prioOptions({}).find(p => p.selected).value, "normal"); assert.deepStrictEqual(M.prioOptions({ priorities: ["a"] }).map(p => p.value), ["a"]);
  assert.strictEqual(String(V.ResolvedLine(M.resolvedLine({ found: true, client: "a", project: "b <x>", status: "ferme" }))), '✓ a / b &lt;x&gt;  [ferme] <button class="mini" data-action="reopen" title="Rouvrir le ticket (ferme → a_faire, motif requis)">↻ Rouvrir</button>', "RM2285 : un ticket fermé propose sa réouverture, échappé"); assert(!/reopen/.test(String(V.ResolvedLine(M.resolvedLine({ found: true, client: "a", project: "b", status: "en_cours" }))))); assert.strictEqual(String(V.ResolvedLine(null)), "");
  assert.strictEqual(String(V.Options([{ value: "x", label: "X", selected: true }, { value: "y", label: "Y" }])), '<option value="x" selected>X</option><option value="y">Y</option>'); assert.strictEqual(String(V.Options([{ value: "a", label: "a" }], "a", "tous")), '<option value="">tous</option><option value="a" selected>a</option>');
  console.log("✓ modèle et vue (RM2639/1941/2285) : contexte client, modèles par moteur, ligne de résolution, corps de spawn et de ticket, options");
  const calls = []; const repo = { async resolve(rm) { calls.push(["resolve", rm]); if (rm === "9") throw new Error("boom"); return rm === "7" ? { found: false } : { found: true, client: "acme", project: "site", title: "T" + rm, status: rm === "5" ? "ferme" : "en_cours", cwd: "/w/" + rm, ai_model: "opus", role_hint: null }; }, async spawn(b) { calls.push(["spawn", b]); return { ok: true }; }, async createTicket(b) { calls.push(["create", b]); return { rm_id: "77" }; }, async projects() { calls.push(["projects"]); return PJ; }, async running() { return [{ rm_id: "42" }]; } };
  const store = { d: {}, getItem(k) { return this.d[k] === undefined ? null : this.d[k]; }, setItem(k, v) { this.d[k] = String(v); } };
  const svc = new LauncherService({ repo, storage: store }); assert.strictEqual(await svc.resolve("abc"), null); assert((await svc.resolve("42")).found); assert.strictEqual(await svc.resolve("9"), null, "échec réseau : non résolu, pas d'exception"); store.d.karlClientCtx = "beta"; const svc2 = new LauncherService({ repo, storage: store }); assert.strictEqual(svc2.clientContext, "beta"); await svc2.loadProjects(); assert.strictEqual(svc2.clientContext, "", "client disparu → tous"); svc2.setClientContext("acme"); assert.strictEqual(store.d.karlClientCtx, "acme"); assert(await svc2.isRunning("42") && !(await svc2.isRunning("1")));
  console.log("✓ service : résolution tolérante, contexte client de ce navigateur (client disparu → tous), session vivante");
  const card = fakeEl("launchcard"), ntcard = fakeEl("ntcard", { open: true }), clientctx = fakeEl("clientctx");
  const rm = fakeEl("rm"), resolved = fakeEl("resolved"), engine = Object.assign(fakeEl("engine"), { value: "claude" }), model = fakeEl("model"), cwd = fakeEl("cwd"), tpl = Object.assign(fakeEl("ptpl"), { value: "traiter" }), prompt = fakeEl("prompt"), spawnbtn = fakeEl("spawnbtn");
  const ntTitle = fakeEl("nt-title"), ntProject = fakeEl("nt-project"), ntType = fakeEl("nt-type"), ntPrio = fakeEl("nt-prio"), ntTags = fakeEl("nt-tags"), ntDesc = fakeEl("nt-desc"), ntBtn = fakeEl("nt-btn");
  Object.assign(card.kids, { "#rm": rm, "#resolved": resolved, "#engine": engine, "#model": model, "#cwd": cwd, "#ptpl": tpl, "#prompt": prompt, "#spawnbtn": spawnbtn }); Object.assign(ntcard.kids, { "#nt-title": ntTitle, "#nt-project": ntProject, "#nt-type": ntType, "#nt-prio": ntPrio, "#nt-tags": ntTags, "#nt-desc": ntDesc, "#nt-btn": ntBtn });
  const ev = []; let guard = true; let answer = "parce que"; const store2 = { d: { karlClientCtx: "iprospective" }, getItem(k) { return this.d[k] === undefined ? null : this.d[k]; }, setItem(k, v) { this.d[k] = String(v); } };
  const ctr = mountLauncher({ card, ntcard, clientctx }, { service: new LauncherService({ repo, storage: store2 }), cfg: () => ({ models: { claude: ["opus", "sonnet"], vibe: ["mistral"] }, task_types: [{ value: "feature" }, { value: "bug" }], priorities: ["low", "normal"] }), notify: (m, e) => ev.push(["toast", m, !!e]), capture: (t) => ev.push(["capture", t]), run: async (n, a) => { ev.push(["run", n, a]); return { ok: a.rm_id !== "5", rc: 1, stderr: "refus" }; }, prompt: () => answer,
    promptText: (t, r, c, p, h) => t + ":RM" + r + (c ? ":" + c + "/" + p : ""), promptFill: (t, cur, computed) => (t === "libre" ? cur : computed), confirmSecondSession: async () => guard, warnSpawn: () => ev.push("warn"), afterSpawn: async () => ev.push("afterSpawn"), attach: (r) => ev.push(["attach", r]), switchPanel: (p) => ev.push(["panel", p]), afterStatus: async (r) => ev.push(["afterStatus", r]), afterCreate: () => ev.push("afterCreate"), onProjects: () => ev.push("onProjects"), onContext: (c, proj, initial) => ev.push(["context", c, proj, initial]) });
  assert.deepStrictEqual(ev[0], ["context", "iprospective", "", true], "le contexte restauré est connu du reste dès le montage");
  ctr.populateModels(); assert(/<option value="ticket">défini dans le ticket<\/option><option value="" selected>défaut moteur<\/option>/.test(model.innerHTML) && /opus/.test(model.innerHTML) && /sonnet/.test(model.innerHTML) && model.value === "", "RM1941 : catalogue du moteur ; un sélecteur vide (valeur « ») retombe sur « défaut moteur », comme avant");
  engine.value = "vibe"; model.value = "sonnet"; await card.fire("change", engine); assert(/mistral/.test(model.innerHTML) && !/sonnet/.test(model.innerHTML) && model.value === "ticket", "changer de moteur : nouveau catalogue, choix invalide → ticket");
  ctr.fillTicketForm(); assert(/<option value="feature" selected>feature<\/option><option value="bug">bug<\/option>/.test(ntType.innerHTML) && /<option value="normal" selected>/.test(ntPrio.innerHTML), "§8 : types et priorités depuis la config, défauts feature/normal"); ntType.value = "bug"; ctr.fillTicketForm(); assert.strictEqual(ntType.value, "bug", "déjà peuplé : pas re-peuplé");
  calls.length = 0; rm.value = "42"; await card.fire("input", rm); assert.strictEqual(calls.filter(c => c[0] === "resolve").length, 0, "frappe amortie"); await settle(350); assert(calls.some(c => c[0] === "resolve" && c[1] === "42") && /✓ acme \/ site — T42/.test(resolved.innerHTML) && resolved.className === "resolved" && cwd.value === "/w/42" && /défini dans le ticket \(opus\)/.test(model.innerHTML) && prompt.value === "traiter:RM42:acme/site", "§1 : résolu → ligne, cwd, prescription du modèle, consigne (RM2873)");
  tpl.value = "libre"; prompt.value = "ma consigne"; await card.fire("change", tpl); assert.strictEqual(prompt.value, "ma consigne", "modèle « libre » : la saisie reste"); tpl.value = "traiter"; await card.fire("change", tpl); assert.strictEqual(prompt.value, "traiter:RM42:acme/site");
  rm.value = "7"; await ctr.resolve(); assert(resolved.className === "resolved nf" && /non trouvé en local/.test(resolved.innerHTML)); rm.value = "5"; await ctr.resolve(); assert(/data-action="reopen"/.test(resolved.innerHTML), "RM2285 : fermé → rouvrir proposé");
  ev.length = 0; await card.click("reopen"); assert(ev.some(x => x[0] === "run" && x[1] === "task-status" && x[2].rm_id === "5" && x[2].status === "a_faire" && x[2].note === "parce que") && ev.some(x => x[0] === "toast" && /Échec réouverture/.test(x[1])) && ev.some(x => x[0] === "capture") && ev.some(x => x[0] === "afterStatus" && x[1] === "5"), "réouverture : motif transmis, refus capturé, suites"); answer = "   "; ev.length = 0; await ctr.reopen("5"); assert(ev.some(x => x[0] === "toast" && /Motif requis/.test(x[1])) && !ev.some(x => x[0] === "run"), "motif vide : rien ne part"); answer = "ok";
  rm.value = "abc"; ev.length = 0; await card.click("spawn"); assert(ev.some(x => x[0] === "toast" && /RM id requis/.test(x[1])) && !calls.some(c => c[0] === "spawn")); rm.value = "42"; engine.value = "claude"; model.value = "opus"; cwd.value = "/w/42"; prompt.value = "go"; guard = false; ev.length = 0; await card.click("spawn"); assert(!calls.some(c => c[0] === "spawn"), "RM2818 : la garde refuse → rien");
  guard = true; ev.length = 0; await card.fire("keydown", rm, { key: "Enter" }); await settle(450); assert(calls.some(c => c[0] === "spawn" && c[1].rm_id === "42" && c[1].engine === "claude" && c[1].model === "opus" && c[1].cwd === "/w/42" && c[1].prompt === "go") && ev.some(x => x[0] === "toast" && /karl-RM42 lancée/.test(x[1])) && ev.includes("warn") && ev.includes("afterSpawn") && ev.some(x => x[0] === "attach" && x[1] === "42") && prompt.value === "" && spawnbtn.textContent === "▶ Lancer & attacher", "Entrée lance : corps complet, alerte, suites, attache, consigne vidée");
  ev.length = 0; await ctr.loadProjects(); assert(/<option value="iprospective\/pm-ai-agents">/.test(ntProject.innerHTML) && ntProject.value === "iprospective/pm-ai-agents" && /<option value="iprospective" selected>iprospective<\/option>/.test(clientctx.innerHTML) && clientctx.value === "iprospective" && ev.includes("onProjects") && ev.some(x => x[0] === "context" && x[1] === "iprospective" && x[2] === "iprospective/pm-ai-agents" && x[3] === true), "projets connus : formulaire, menu du contexte, reste prévenu (pré-filtre initial)");
  ev.length = 0; clientctx.value = "acme"; await clientctx.fire("change", clientctx); assert(store2.d.karlClientCtx === "acme" && ntProject.value === "acme/site" && ev.some(x => x[0] === "context" && x[1] === "acme" && x[2] === "acme/site" && x[3] === false), "RM2639 : contexte retenu, formulaires suivent, reste prévenu"); ctr.setClientContext(""); assert.strictEqual(ctr.clientContext(), "");
  ntTitle.value = " "; ev.length = 0; await ntcard.click("create"); assert(ev.some(x => x[0] === "toast" && /Titre requis/.test(x[1]))); ntTitle.value = "Nouveau"; ntTags.value = "ci"; ntDesc.value = "d"; ntProject.value = "acme/site"; ev.length = 0; await ntcard.click("create"); await settle();
  assert(calls.some(c => c[0] === "create" && c[1].title === "Nouveau" && c[1].project === "acme/site" && c[1].type === "bug" && c[1].tags === "ci") && ev.some(x => x[0] === "toast" && /RM77 créé/.test(x[1])) && rm.value === "77" && ntTitle.value === "" && ntTags.value === "" && ntDesc.value === "" && ntcard.open === false && ev.includes("afterCreate"), "§8 : créé, lanceur pré-rempli, formulaire vidé et replié, recherche prévenue");
  ev.length = 0; await ctr.goto("42"); assert(rm.value === "42" && ev.some(x => x[0] === "panel" && x[1] === "sessions") && ev.some(x => x[0] === "attach" && x[1] === "42"), "RM2173/2427 : aller au ticket rattache si la session tourne"); ev.length = 0; await ctr.goto("1"); assert(!ev.some(x => x[0] === "attach"));
  ctr.unmount(); assert.strictEqual(card.listenerCount + ntcard.listenerCount + clientctx.listenerCount, 0);
  console.log("✓ contrôleur : résolution amortie, modèles, consigne partagée, réouverture, garde RM2818 + spawn, projets et contexte, saisie éclair, aller au ticket");
  console.log("\nTous les tests du lanceur passent.");
})().catch(e => { console.error("✗", e.message); process.exit(1); });
