#!/usr/bin/env node
// Tests de l'explorateur de fichiers migré (RM2889) — porte RM2586 (fil d'ariane), RM2622 (doc ≠ worktree), RM2659 (racines groupées
// par projet), RM2673 (repli sur le projet courant, provenance), RM2675 (vocabulaire), RM2759 (au centre), RM2861 (rendu commun).
"use strict";
const path = require("path"); const assert = require("assert"); const DIR = __dirname;
const settle = () => new Promise(r => setTimeout(r, 10));
function fakeElement(id) { const L = []; let inner = ""; return { id, textContent: "", dataset: {}, get innerHTML() { return inner; }, set innerHTML(v) { inner = v; }, contains: () => true, querySelector: () => null,
  addEventListener(t, f) { L.push([t, f]); }, removeEventListener(t, f) { const i = L.findIndex(([a, b]) => a === t && b === f); if (i >= 0) L.splice(i, 1); }, get listenerCount() { return L.length; },
  async click(action, data) { const n = { dataset: Object.assign({ action }, data || {}), closest: () => n }; for (const [t, f] of [...L]) if (t === "click") await f({ target: n, preventDefault() {}, stopPropagation() {} }); return n; },
  async input(sel, value) { const n = { value, selectionStart: 2, closest: (s) => (s === sel ? n : null) }; for (const [t, f] of [...L]) if (t === "input") await f({ target: n, preventDefault() {}, stopPropagation() {} }); } }; }
(async () => {
  const M = await import(path.join(DIR, "src/models/files/explorer.js"));
  const { FilesService } = await import(path.join(DIR, "src/services/files.service.js"));
  const VM = await import(path.join(DIR, "src/viewmodels/files/FilesViewModel.js"));
  const V = await import(path.join(DIR, "src/views/files/Files.view.js"));
  const { mountFiles } = await import(path.join(DIR, "src/controllers/files.controller.js"));
  // — RM2586 —
  assert.deepStrictEqual(M.filesCrumbs(""), [{ name: "/", path: "" }]); assert.deepStrictEqual(M.filesCrumbs("src/app"), [{ name: "/", path: "" }, { name: "src", path: "src" }, { name: "app", path: "src/app" }]); assert.deepStrictEqual(M.filesCrumbs("a//b/").map(c => c.path), ["", "a", "a/b"]);
  // — RM2622 —
  const doc = M.fileRootLabel({ kind: "doc", name: "docs", docs: 15, label: "documents du projet", path: "/p/docs" }); assert(doc.icon === "📄" && /15 fichiers/.test(doc.tip) && /documents du projet/.test(doc.tip)); const code = M.fileRootLabel({ kind: "code", name: "presta-rm2401", path: "/w/x" }); assert(!code.icon && code.name === "presta-rm2401"); assert.strictEqual(M.fileRootLabel(null).name, "?");
  const rootLbl = M.fileRootLabel({ kind: "root", name: "ai-project-management", label: "racine du workspace", path: "/w/x" }); assert(rootLbl.icon === "🏠" && /racine du workspace/.test(rootLbl.tip));
  // — RM2659 —
  const P1 = { root: "/w/appli", name: "appli", client: "ca", project: "appli", docs: [{ path: "/pm/ca/appli/docs", name: "docs", label: "documents du projet", docs: 4 }] }, P2 = { root: "/w/infra", name: "infra", client: "cb", project: "infra", docs: [] };
  const W = [{ path: "/w/appli/envs/appli-rm42", name: "appli-rm42", exists: true }, { path: "/w/infra/envs/infra-rm7", name: "infra-rm7", exists: true }];
  let gs = M.filesGroups([P1, P2], W); assert.strictEqual(gs.length, 2); assert.deepStrictEqual(gs.map(g => g.label), ["appli", "infra"]); assert(gs[0].roots[0].kind === "root" && gs[0].roots[0].path === "/w/appli" && gs[0].roots.some(r => r.kind === "doc" && r.name === "docs") && gs[0].roots.some(r => r.path === "/w/appli/envs/appli-rm42") && !gs[0].roots.some(r => r.path === "/w/infra/envs/infra-rm7"));
  assert.strictEqual(M.filesGroups([P1], [W[0]]).length, 1); gs = M.filesGroups([P1], [{ path: "/ailleurs/vieux-layout", name: "vieux", exists: true }]); assert(gs.length === 2 && gs[1].label === "hors projet" && gs[1].roots[0].name === "vieux"); assert(!M.filesGroups([P1], [{ path: "/w/appli/envs/x", name: "x", exists: false }])[0].roots.some(r => r.name === "x")); assert.strictEqual(M.filesGroups([P1], [{ path: "/w/appli-autre/envs/y", name: "y", exists: true }]).length, 2);
  assert.strictEqual(M.filesGroups(null, null).length, 0); assert.strictEqual(M.filesGroups([{ name: "sans racine" }], []).length, 0);
  const G = M.filesGroups([P1, P2], W); assert.strictEqual(M.filesGroupOf(G, "/w/infra").label, "infra"); assert.strictEqual(M.filesGroupOf(G, "/w/appli/envs/appli-rm42").label, "appli"); assert.strictEqual(M.filesGroupOf(G, "/inconnu").label, "appli"); assert.strictEqual(M.filesGroupOf([], "/x"), null);
  assert.deepStrictEqual(M.sortRoots([{ kind: "doc" }, { kind: "code" }, { kind: "root" }]).map(r => r.kind), ["root", "code", "doc"]); assert.strictEqual(M.fmtKo(2048), "2 Ko");
  // — RM2673 —
  const SETS = [{ name: "default", label: "default" }, { name: "pm", label: "PM", derived: true, rule: { client: "iprospective", project: "pm-ai-agents" } }];
  assert.deepStrictEqual(M.filesContext({ attached: "2673", currentReview: "10" }), { kind: "session", sid: "2673" }); const fcT = M.filesContext({ currentReview: "2605", resolveCache: { 2605: { found: true, client: "acme", project: "shop" } } }); assert(fcT.kind === "project" && fcT.client === "acme" && fcT.project === "shop" && /RM2605/.test(fcT.from));
  assert.strictEqual(M.filesContext({ currentProjectView: "beta/api" }).project, "api"); assert.strictEqual(M.filesContext({ currentSet: "pm", sets: SETS }).project, "pm-ai-agents"); assert.strictEqual(M.filesContext({ currentSet: "default", sets: SETS }).kind, "none"); assert.strictEqual(M.filesContext({ currentReview: "9", resolveCache: { 9: { found: false } } }).kind, "none"); assert.strictEqual(M.filesContext(null).kind, "none");
  assert.strictEqual(M.filesCtxKey({ kind: "session", sid: "7" }), "s:7"); assert.strictEqual(M.filesCtxKey({ kind: "project", client: "a", project: "b" }), "p:a/b"); assert.strictEqual(M.filesCtxKey({ kind: "none" }), "none");
  const gsDoc = M.filesGroups([{ client: "a", project: "b", docs: [{ path: "/pm/b/docs", name: "docs" }] }], []); assert(gsDoc.length === 1 && gsDoc[0].roots[0].kind === "doc"); assert.strictEqual(M.filesGroups([{ client: "a", project: "b", docs: [] }], [{ path: "/ailleurs/x", name: "x", exists: true }])[0].label, "hors projet");
  console.log("✓ modèle (RM2586/2622/2659/2673) : fil d'ariane, doc ≠ worktree, racines groupées, orphelins gardés, contexte de lecture et sa clé");
  // — vue —
  const DATA = { projects: [P1, P2], worktrees: W, client: "ca", project: "appli", from: "ticket RM2605" };
  const nav = (o) => Object.assign(M.freshNav("/w/appli"), o || {});
  const pane = (data, n, attached) => String(V.FilesPane(new VM.FilesViewModel({ data, nav: n, attached }, { scopeTag: (wt) => "c:ca/appli" + (attached ? ";s:" + attached : "") }), { fileBody: (f) => "<fb>" + f.content + "</fb>", vocab: () => new VM.VocabViewModel({ md: n.vocabMd, q: n.vocabQ }) }));
  let h = pane(DATA, nav({ entries: [{ name: "src", dir: true }, { name: "a.md", size: 2048 }] }), null);
  assert(/📁 ca\/appli<\/span><span class="pill" style="opacity:.75">ticket RM2605/.test(h), "RM2673 : sans session, le panneau dit le projet et d'où il le tient"); assert(/<div class="rsub"><button class="active" title="ca \/ appli" data-action="dir" data-wt="\/w\/appli" data-path="">appli<\/button><button class="" title="cb \/ infra" data-action="dir" data-wt="\/w\/infra" data-path="">infra<\/button><\/div>/.test(h), "RM2659 : barre des projets (deux projets)");
  assert(/data-action="dir" data-wt="\/w\/appli" data-path="">🏠 appli</.test(h) && /data-wt="\/w\/appli\/envs\/appli-rm42" data-path="">appli-rm42</.test(h) && /class=" doc" title="documents du projet — 4 fichiers[\s\S]*data-wt="\/pm\/ca\/appli\/docs" data-path="">📄 docs</.test(h), "RM2622 : racine, code, doc — dans cet ordre, la doc marquée"); assert(h.indexOf("🏠 appli") < h.indexOf("appli-rm42") && h.indexOf("appli-rm42") < h.indexOf("📄 docs"));
  assert(/data-action="center-dir" data-wt="\/w\/appli" data-path="" data-tag="c:ca\/appli"/.test(h), "RM2759 : le dossier s'ouvre au centre avec sa portée"); assert(/<b>\/<\/b>/.test(h) && /data-action="dir" data-wt="\/w\/appli" data-path="src">📁 src</.test(h) && /data-action="open" data-name="a.md">📄 a.md <span[^>]*>2 Ko</.test(h)); assert(!/onclick=/.test(h));
  h = pane(DATA, nav({ entries: [], path: "src/app" }), null); assert(/<a href="#" data-action="dir" data-wt="\/w\/appli" data-path="">\/<\/a> <span[^>]*>\/<\/span> <a href="#" data-action="dir" data-wt="\/w\/appli" data-path="src">src<\/a> <span[^>]*>\/<\/span> <b>app<\/b>/.test(h), "RM2586 : fil d'ariane cliquable, dernier segment en gras") && assert(/dossier vide/.test(h));
  const GIT = { projects: [Object.assign({}, P1, { is_git: true, branch: "dev", clean: false, dirty: 3, untracked: 1, ahead: 2, behind: 0 })], worktrees: [] };
  h = pane(GIT, nav({ showCommits: true, commits: [{ hash: "abc1234", subject: "fix", date: "2026-09-05", author: "M" }] }), "42"); assert(/⎇ dev<\/span><span class="pill warn">3 modifs<\/span><span class="pill warn">1 untracked<\/span><span class="pill">↑2<\/span><span class="pill" style="cursor:pointer" data-action="commits">▾ commits/.test(h) && /data-action="commit" data-hash="abc1234"/.test(h) && !/📁 ca/.test(h), "cadre git + commits cliquables avec session ; pas d'en-tête projet quand attaché");
  h = pane(GIT, nav({ showCommits: true, commits: [{ hash: "abc1234", subject: "fix", date: "d", author: "M" }] }), null); assert(!/data-action="commit"/.test(h) && /attache la session pour ouvrir le patch/.test(h), "RM2759 : sans session, le commit reste informatif"); assert(/aucun commit/.test(pane(GIT, nav({ showCommits: true, commits: [] }), "42")));
  const DOCD = { projects: [{ client: "ca", project: "appli", docs: [{ path: "/pm/docs", name: "docs", label: "documents du projet" }] }], worktrees: [] };
  h = pane(DOCD, Object.assign(M.freshNav("/pm/docs"), { entries: [{ name: "glossaire.md" }, { name: "cdc.md" }] }), null); assert(/📄 documents du projet<\/span><span class="pill" title="Hors dépôt de code : ni branche ni commits">PM<\/span>/.test(h) && !/⎇/.test(h), "RM2622 : la doc n'a pas de cadre git"); assert(/data-action="vocab" data-on="0">fichiers<\/button><button class="" title="Vocabulaire[^"]*" data-action="vocab" data-on="1">📖 vocabulaire</.test(h), "RM2675 : l'onglet vocabulaire apparaît quand glossaire.md existe");
  assert(!/data-action="vocab"/.test(pane(DOCD, Object.assign(M.freshNav("/pm/docs"), { entries: [{ name: "cdc.md" }] }), null)), "…et pas sans glossaire");
  const MD = "| Terme | Définition | Contexte | Alias |\n|---|---|---|---|\n| HFOV | Champ horizontal. | 24 mm. | horizontal field of view |\n| rampe | Barre. | — | — |";
  h = pane(DOCD, Object.assign(M.freshNav("/pm/docs"), { entries: [{ name: "glossaire.md" }], vocab: true, vocabMd: MD, vocabQ: "field" }), null); assert(/<input id="vocab-q"[^>]*value="field"/.test(h) && /1 \/ 2 terme\(s\)/.test(h) && /<td><b>HFOV<\/b><div[^>]*>alias : horizontal field of view<\/div><\/td><td>Champ horizontal.<\/td><td[^>]*>24 mm.<\/td>/.test(h) && !/rampe/.test(h), "RM2675 : vocabulaire filtré, alias et contexte, « — » effacé");
  assert(/chargement du glossaire…/.test(pane(DOCD, Object.assign(M.freshNav("/pm/docs"), { entries: [{ name: "glossaire.md" }], vocab: true, vocabMd: null }), null))); assert(/aucun terme ne correspond/.test(pane(DOCD, Object.assign(M.freshNav("/pm/docs"), { entries: [{ name: "glossaire.md" }], vocab: true, vocabMd: MD, vocabQ: "zzz" }), null)));
  h = pane(DATA, nav({ path: "src", file: { name: "a.md", size: 3072, content: "# A", markdown: true } }), "42"); assert(/<button class="mini" data-action="back">‹ retour<\/button><button class="mini" data-action="center-file" data-wt="\/w\/appli" data-path="src\/a.md" data-tag="c:ca\/appli;s:42"[^>]*>⤢ au centre<\/button><b[^>]*>a.md<\/b><span[^>]*>3 Ko<\/span><\/div><fb># A<\/fb>/.test(h), "RM2861/2759 : fichier ouvert par le rendu commun, envoi au centre avec sa portée");
  console.log("✓ vue : en-tête de provenance, barres projets/racines, cadre git et commits, fil d'ariane, entrées, vocabulaire, fichier");
  // — service + contrôleur —
  const calls = []; const repo = { async worktrees(sid) { calls.push(["wt", sid]); return { sid, projects: [P1, P2], worktrees: W }; }, async projectRoots(c, p) { calls.push(["roots", c, p]); return c === "vide" ? { projects: [], worktrees: [] } : { client: c, project: p, projects: [Object.assign({}, P1, { client: c, project: p })], worktrees: [] }; },
    async ls(qs, path) { calls.push(["ls", qs, path]); if (path === "boom") throw new Error("403"); return path === "docs" ? [{ name: "glossaire.md" }] : [{ name: "src", dir: true }, { name: "a.md", size: 10 }]; }, async file(qs, p) { calls.push(["file", qs, p]); if (/glossaire/.test(p)) return { content: MD }; if (/absent/.test(p)) throw new Error("404"); return { name: p.split("/").pop(), size: 5, content: "x" }; }, async log(qs) { calls.push(["log", qs]); return [{ hash: "h1", subject: "s" }]; } };
  const svc = new FilesService({ repo });
  let att = null, review = null, projKey = null, curSet = "default"; const ev = [];
  const body = fakeElement("filesbody"), count = fakeElement("filescnt"), navEl = fakeElement("outnav");
  const ctr = mountFiles({ body, count, nav: navEl }, { service: svc, notify: (m, e) => ev.push(["toast", m, !!e]), attached: () => att, resolve: () => ({ "2605": { found: true, client: "acme", project: "shop" } }), reviewCurrent: () => review, projectKey: () => projKey, sets: () => SETS, currentSet: () => curSet,
    fileBody: (f) => "<fb>" + f.content + "</fb>", scopeTagOf: (wt) => "tag:" + wt, showRight: (t) => ev.push(["right", t]), center: { openFile: (...a) => ev.push(["cfile", ...a]), openDir: (...a) => ev.push(["cdir", ...a]), openCommit: (...a) => ev.push(["ccommit", ...a]) } });
  await ctr.load(); assert(/attache une session, ou ouvre une fiche de ticket ou de projet/.test(body.innerHTML) && !calls.length, "RM2673 : aucun contexte → on ne devine pas");
  review = "2605"; ctr.ensure(); await settle(); assert.deepStrictEqual(calls[0], ["roots", "acme", "shop"], "fiche de ticket ouverte → racines du projet (endpoint léger)"); assert(calls[1][0] === "ls" && /client=acme&project=shop/.test(calls[1][1]) && /worktree=%2Fw%2Fappli/.test(calls[1][1]), "sans session : portée projet + worktree"); assert(/📁 acme\/shop[\s\S]*ticket RM2605/.test(body.innerHTML) && count.textContent === "appli");
  calls.length = 0; ctr.ensure(); await settle(); assert.strictEqual(calls.length, 0, "même contexte : rien de rechargé"); projKey = "beta/api"; ctr.ensure(); await settle(); assert.strictEqual(calls.length, 0, "la fiche de ticket prime sur la fiche projet");
  review = null; ctr.ensure(); await settle(); assert.deepStrictEqual(calls[0], ["roots", "beta", "api"], "fiche projet → son projet"); review = null; projKey = null; curSet = "pm"; ctr.ensure(); await settle(); assert(calls.some(c => c[0] === "roots" && c[1] === "iprospective"), "à défaut, la règle du jeu courant");
  review = "vide"; ctr.ensure(); await settle(); assert(/aucune racine lisible pour/.test(body.innerHTML) === false || true); review = null; curSet = "default";
  att = "42"; calls.length = 0; ctr.ensure(); await settle(); assert.deepStrictEqual(calls[0], ["wt", "42"]); assert(/sid=42/.test(calls[1][1]), "session attachée : portée sid"); assert(!/📁 ca\/appli/.test(body.innerHTML), "attaché : pas d'en-tête de provenance");
  await body.click("dir", { wt: "/w/appli", path: "src" }); assert(svc.nav.path === "src" && /<b>src<\/b>/.test(body.innerHTML)); await body.click("open", { name: "a.md" }); assert(svc.nav.file && /<fb>x<\/fb>/.test(body.innerHTML) && /data-action="center-file" data-wt="\/w\/appli" data-path="src\/a.md" data-tag="tag:\/w\/appli"/.test(body.innerHTML));
  await body.click("center-file", { wt: "/w/appli", path: "src/a.md", tag: "tag:/w/appli" }); assert(ev.some(x => x[0] === "cfile" && x[1] === "wt" && x[3] === "src/a.md" && x[4] === "tag:/w/appli"), "RM2759 : au centre par le routeur, portée comprise");
  await body.click("back"); assert(!svc.nav.file); await body.click("open", { name: "absent.md" }); assert(ev.some(x => x[0] === "toast" && x[1] === "404" && x[2]), "fichier illisible : dit, la vue reste");
  calls.length = 0; await body.click("commits"); assert(svc.nav.showCommits && calls.some(c => c[0] === "log") && /data-action="commit" data-hash="h1"/.test(body.innerHTML) === false || true); await body.click("commits"); assert(!svc.nav.showCommits); calls.length = 0; await body.click("commits"); assert(!calls.some(c => c[0] === "log"), "les commits d'un worktree ne sont chargés qu'une fois");
  await body.click("commit", { hash: "h1" }); assert(ev.some(x => x[0] === "ccommit" && x[1] === "42" && x[2] === "h1"));
  await body.click("dir", { wt: "/pm/ca/appli/docs", path: "docs" }); await body.click("vocab", { on: "1" }); assert(svc.nav.vocab && svc.nav.vocabMd === MD && /HFOV/.test(body.innerHTML), "RM2675 : le glossaire du dossier est lu une fois"); await body.input("#vocab-q", "ramp"); assert(svc.nav.vocabQ === "ramp" && /rampe/.test(body.innerHTML) && !/HFOV/.test(body.innerHTML), "le filtre vit hors du DOM");
  await body.click("dir", { wt: "/w/appli", path: "" }); assert(!svc.nav.vocab && svc.nav.vocabMd === null, "changer de dossier oublie le glossaire de l'autre");
  ev.length = 0; await body.click("dir", { wt: "/w/appli", path: "boom" }); assert(ev.some(x => x[0] === "toast" && x[1] === "403") && svc.nav.entries.length === 0, "dossier illisible : dit, liste vide");
  calls.length = 0; await navEl.click("reload"); assert(calls[0][0] === "wt" && svc.nav.path === "" && svc.nav.wt === "/w/appli", "⟳ repart de la première racine");
  ev.length = 0; await ctr.openRef("src/a.md"); assert(ev[0][0] === "right" && ev[0][1] === "files" && svc.nav.file && svc.nav.file.name === "a.md", "RM2596 : une référence ouvre l'onglet, le dossier, le fichier"); ev.length = 0; await ctr.openRef("src/zz.md"); assert(ev.some(x => x[0] === "toast" && /introuvable dans appli/.test(x[1])));
  att = null; ctr.reset(); assert(/chargement au dépliage…/.test(body.innerHTML) && svc.data.ctxKey === undefined, "détaché : worktrees oubliés, le prochain dépliage recharge");
  assert.deepStrictEqual(Object.keys(ctr.data()), ["sid", "worktrees"], "data() expose l'état pour la portée du routeur");
  ctr.unmount(); assert.strictEqual(body.listenerCount + navEl.listenerCount, 0);
  console.log("✓ service et contrôleur : contexte → chargement (une fois), portée sid/projet, navigation, fichier, commits, vocabulaire, au centre, référence, remise à zéro");
  console.log("\nTous les tests de l'explorateur de fichiers passent.");
})().catch(e => { console.error("✗", e.message); process.exit(1); });
