#!/usr/bin/env node
// Tests du domaine sets — MODÈLE et SERVICE (RM3017, scindé de test_cockpit_sets.js) : fonctions pures (RM2955, RM2673, RM2741, barre,
// sélecteur, textes) et SetsService (courant serveur, bascules, 💾, sélection, créations, règle, relance, versions).
"use strict";
const fs = require("fs"); const path = require("path"); const assert = require("assert"); const DIR = __dirname;
const { fakeEl, facets, SETS3, now, R, mkRepo } = require("./test_cockpit_sets.helpers.js");
(async () => {
  const M = await import(path.join(DIR, "src/modules/sets/sets.js"));
  const { SetsService } = await import(path.join(DIR, "src/modules/sets/sets.service.js"));

  // — RM2955 : setEditOptions —
  const SETS_2955 = [{ name: "default", label: "sessions actives", count: 12, alive: 5 }, { name: "pm", label: "PM", count: 3, alive: 1, derived: true }, { name: "nuit", count: 0, alive: 0 }];
  let opts = M.setEditOptions(SETS_2955, null, "pm");
  assert.deepStrictEqual(opts.map(o => o.value), ["default", "pm", "nuit"]); assert.strictEqual(opts.find(o => o.value === "pm").selected, true, "sans choix explicite, la carte suit le jeu courant");
  assert(opts.find(o => o.value === "pm").label.includes("● courant") && opts.find(o => o.value === "pm").label.startsWith("⚙ ") && !opts.find(o => o.value === "default").label.includes("● courant"));
  assert.strictEqual(opts.find(o => o.value === "default").label, "sessions actives (5/12)"); assert.strictEqual(M.setEditOptions(SETS_2955, "nuit", "pm").find(o => o.selected).value, "nuit", "un choix explicite l'emporte");
  assert(M.setEditOptions(SETS_2955, "nuit", "pm").find(o => o.value === "pm").label.includes("● courant")); assert.strictEqual(M.setEditOptions(null, null, "pm").length, 0); assert.strictEqual(M.setEditOptions([{ name: "x" }], null, "pm")[0].label, "x (0/0)");
  // — RM2673 : setWritable —
  const SETS = [{ name: "default", label: "default" }, { name: "pm", label: "PM", derived: true, rule: { client: "iprospective", project: "pm-ai-agents" } }];
  assert.strictEqual(M.setWritable(SETS, "default", "set"), true); assert.strictEqual(M.setWritable(SETS, "pm", "set"), false); assert.strictEqual(M.setWritable(SETS, "pm", "live"), false, "le jeu dérivé reste la cible en vue « sessions ouvertes »"); assert.strictEqual(M.setWritable(SETS, "pm", "all"), false);
  assert.strictEqual(M.setWritable(SETS, "default", "client:acme"), false, "RM2536 : une vue par client ne désigne aucun jeu"); assert.strictEqual(M.setWritable(SETS, "inconnu", "set"), true); assert.strictEqual(M.setWritable(null, "pm", null), true);
  // — RM2741 : relaunchBtnState, newSetPlan —
  const SET = { exists: true, count: 4, entries: [{ sid: "1", alive: true }, { sid: "2", alive: false }, { sid: "3", alive: false }, { sid: "4", alive: true }] };
  assert.deepEqual(M.relaunchBtnState(SET, "set"), { show: true, count: 2 }, "le compteur est celui des sessions ÉTEINTES"); assert.strictEqual(M.relaunchBtnState(SET, "live").show, false); assert.strictEqual(M.relaunchBtnState(SET, "all").show, false); assert.strictEqual(M.relaunchBtnState(SET, "client:acme").show, false);
  assert.strictEqual(M.relaunchBtnState({ exists: true, count: 2, entries: [{ alive: true }, { alive: true }] }, "set").show, false); assert.strictEqual(M.relaunchBtnState({ exists: false }, "set").show, false); assert.deepEqual(M.relaunchBtnState({ exists: true, count: 3 }, "set"), { show: true, count: 3 }, "sans entries : le total");
  const EXIST = ["default", "pm"];
  const manual = M.newSetPlan("chantier", "Chantier", {}, ["1", "2"], true, EXIST); assert.strictEqual(manual.kind, "manual"); assert.deepEqual(manual.body, { group: "chantier", label: "Chantier", sids: ["1", "2"] }); assert.strictEqual(manual.note, "");
  assert.deepEqual(M.newSetPlan("chantier", "Chantier", {}, ["1"], false, EXIST).body, { group: "chantier", label: "Chantier" }, "case décochée → jeu vide");
  const derived = M.newSetPlan("acme", "Acme", { client: "acme" }, ["1", "2"], true, EXIST); assert.strictEqual(derived.kind, "derived"); assert.deepEqual(derived.body, { group: "acme", label: "Acme", rule: { client: "acme" } }); assert(/pas versées/.test(derived.note));
  assert.strictEqual(M.newSetPlan("pm", "PM", {}, [], false, EXIST).ok, false); assert(/existe déjà/.test(M.newSetPlan("pm", "PM", {}, [], false, EXIST).error)); assert.strictEqual(M.newSetPlan("x", "", {}, [], false, EXIST).ok, false); assert.strictEqual(M.newSetPlan("", "###", {}, [], false, EXIST).ok, false);
  assert.strictEqual(M.slugifySet("Chantier Calicôte !"), "chantier-calicote"); assert.strictEqual(M.slugifySet("###"), ""); assert.strictEqual(M.slugifySet("a".repeat(40)).length, 32);
  assert.deepStrictEqual(M.ruleFromValues({ client: "acme", project: "", mark: "wip", tag: "", tickets: " 1, 2 ,, 3 " }), { client: "acme", mark: "wip", tickets: ["1", "2", "3"] }); assert.deepStrictEqual(M.ruleFromValues({}), {}); assert.strictEqual(M.ruleSummary({ client: "acme", tickets: ["1", "2"] }), "client=acme tickets=1,2");
  // — barre, sélecteur, textes —
  const bs = M.barState({ sets: SETS, current: "default", view: "set", selMode: false, selectedCount: 0 });
  assert(bs.saveShown && bs.saveLabel === "💾 → default" && /AFFICHÉES au jeu « default »/.test(bs.saveTitle) && bs.delTitle === "Supprimer le jeu « default » (les sessions continuent de tourner)" && bs.targets.length === 0 && !bs.canMove, "RM2673 : les destinations dérivées ne sont pas proposées");
  const bs2 = M.barState({ sets: [...SETS, { name: "b", label: "B", count: 2 }], current: "default", view: "set", selMode: true, selectedCount: 3 }); assert(bs2.saveLabel === "＋ jeu (3)" && bs2.canMove && bs2.targets.length === 1 && bs2.targets[0].label === "vers B (2)", "RM2449 : déplacer vers les autres jeux manuels");
  const bs3 = M.barState({ sets: [...SETS, { name: "b", label: "B" }], current: "pm", view: "live", selMode: false, selectedCount: 0 }); assert(!bs3.saveShown, "RM2452/RM2673 : 💾 masqué sur un jeu dérivé, quelle que soit la vue"); assert(M.barState({ sets: SETS, current: "pm", view: "set", selMode: true, selectedCount: 1 }).saveShown && !M.barState({ sets: [...SETS, { name: "b" }], current: "pm", view: "set", selMode: true, selectedCount: 1 }).canMove, "en sélection le bouton crée ; « → déplacer » exige un jeu source inscriptible");
  const pg = M.pickerGroups({ live_count: 4, all_count: 9, sessions_count: 12, client_views: [{ view: "client:acme", label: "acme", count: 2 }] }, SETS, "pm", "client:acme");
  assert.deepStrictEqual(pg.map(g => g.label), ["vues", "clients", "jeux"]); assert(pg[0].options[0].label === "▶ sessions ouvertes (4)" && pg[0].options[2].value === "view:sessions" && pg[1].options[0].selected && pg[1].options[0].label === "👤 acme (2)" && pg[2].options[1].value === "set:pm" && !pg[2].options[1].selected, "RM2446/2452/2954 : vues, clients, jeux ; la vue client est sélectionnée");
  const jeux = (r, sets, cur) => M.pickerGroups(r, sets, cur, "set").find(g => g.label === "jeux"); assert(jeux({}, SETS, "pm").options[1].selected && jeux({}, [], "default").options[0].label === "default (0)" && M.pickerGroups({}, SETS, "pm", "set").length === 2, "sans client : deux groupes seulement"); assert.deepStrictEqual(M.selButtonState(true), { text: "✓", title: "Terminer la sélection" });
  assert.strictEqual(M.saveSummary({ count: 5, added: ["a", "b"] }, "X"), "💾 5 session(s) dans « X » (+2 nouvelles)"); assert.strictEqual(M.saveSummary({ count: 5, added: [] }, "X"), "💾 5 session(s) dans « X » (rien de neuf)"); assert.strictEqual(M.saveSummary({}, "X"), "Aucune session à enregistrer");
  assert(/OK = les DÉPLACER \(retirées de « A »\)/.test(M.moveConfirmText(2, "B", "A"))); assert.strictEqual(M.moveSummary(["1", "2"], false, "B"), "⧉ 2 session(s) copiée(s) vers « B »"); assert.strictEqual(M.viewMessage("live"), "vue : sessions ouvertes"); assert.strictEqual(M.viewMessage("set", "X"), "vue : jeu « X »");
  assert(/Relancer 3 session\(s\) de « X »[^]*~12 k tokens[^]*de l'ordre de 2\.5 \$[^]*1 déjà active\(s\)[^]*2 sans conversation/.test(M.relaunchConfirmText({ relaunchable: 3, tokens_est: 12345, usd_est: 2.5, already_live: 1, lost: 2 }, "X")), "RM2451 : le prix avant");
  assert.deepStrictEqual(M.relaunchSummary({ resumed: 2, skipped: 1, failed: 1 }), { msg: "▶ 2 reprise(s) · 1 déjà active(s) · 1 échec(s)", failed: true }); assert.deepStrictEqual(M.relaunchSummary({}), { msg: "▶ rien à relancer", failed: false });
  assert.deepStrictEqual(M.spawnWarnings({ set: { joined: false, reason: "plein", group: "pm", max: 12 }, blocked: "approbation attendue" }, (n) => n.toUpperCase()), ["⚠ le jeu « PM » est plein (12) : la session tourne mais n'y a PAS été enregistrée", "⚠ approbation attendue"], "RM2450/RM2951"); assert.deepStrictEqual(M.spawnWarnings({ set: { joined: true } }, (n) => n), []);
  const g1 = M.ghostRelaunchText({ rm_id: "7", engine: "claude", cwd: "/w", resumable: true }); assert(!g1.neuve && /^Relancer la session RM7 \?/.test(g1.text) && /moteur : claude\ndossier : \/w/.test(g1.text) && /sera reprise/.test(g1.text) && g1.start === "▶ relance de RM7…");
  const g2 = M.ghostRelaunchText({ rm_id: "slug", is_ticket: false, resumable: false, model: "opus" }); assert(g2.neuve && /^Ouvrir une session NEUVE pour slug \?/.test(g2.text) && /modèle : opus/.test(g2.text) && /SANS le contexte d'avant/.test(g2.text), "RM2949 : conversation perdue → session neuve annoncée AVANT");
  assert.strictEqual(M.entryState({ alive: true }), "🟢 active"); assert.strictEqual(M.entryState({ resumable: true }), "🟡 reprenable"); assert.strictEqual(M.entryState({}), "🔴 perdue"); assert.strictEqual(M.entryLabel("12"), "RM12"); assert.strictEqual(M.entryLabel("slug"), "slug"); assert.strictEqual(M.sessionLabelOf({ rm_id: "3", is_ticket: false }), "3");
  assert.deepStrictEqual(M.historyFor([{ id: "a", at: 1, sets: [{ name: "x", count: 2 }] }, { id: "b", at: 2, sets: [{ name: "y", count: 1 }] }], "x"), [{ id: "a", at: 1, count: 2 }], "RM2443 : seules les versions contenant le jeu"); assert.strictEqual(M.restartMessage("auto", "RM1"), "⟳ RM1 redémarrera toute seule"); assert.strictEqual(M.retentionMessage(0), "plus rien n'est masqué"); assert(/7 j sont masquées/.test(M.retentionMessage("7")));
  console.log("✓ modèle : RM2955 options de la carte, RM2673 setWritable + barre, RM2741 relancer/nature du jeu, RM2446/2452 sélecteur, textes RM2449/2450/2451/2949");


  // — service —
  const store = {}; const storage = { getItem: (k) => (k in store ? store[k] : null), setItem: (k, v) => { store[k] = v; } };
  const { repo, calls, st } = mkRepo(SETS3, facets, now);
  store.karlSet = "nuit";
  const svc = new SetsService({ repo, storage });
  assert(svc.current === "nuit" && svc.view === "set" && !svc.spawnPref && svc.editedSet() === "nuit", "le jeu courant est relu du navigateur");
  let ls = await svc.loadSets(); assert(svc.current === "default" && store.karlSet === "default" && ls.fallback === null && svc.sets.length === 2 && svc.facets === facets, "RM2445 : le serveur fait foi pour le jeu courant");
  st.listResp = { sets: SETS3, view: "live" }; store.karlSet = "zz"; svc.current = "zz"; ls = await svc.loadSets(); assert(ls.fallback === "default" && svc.view === "live", "jeu courant effacé ailleurs → repli sur le premier connu ; la vue vient du serveur"); st.listResp = { sets: SETS3, current: "default", view: "set", facets };
  await svc.loadSets(); assert.strictEqual(svc.label("pm"), "PM"); assert(svc.writable()); svc.view = "live"; assert(svc.writable(), "vue live sur un jeu manuel : inscriptible"); svc.view = "set";
  assert.strictEqual(await svc.switchSet("pm"), "jeu courant : PM"); assert(svc.current === "pm" && store.karlSet === "pm" && !svc.writable()); assert.strictEqual(await svc.switchSet("default", true), ""); await assert.rejects(svc.switchSet("ko")); assert.strictEqual(svc.current, "default", "échec serveur → le jeu courant revient");
  assert.strictEqual(await svc.switchView("live"), "vue : sessions ouvertes"); assert.strictEqual(svc.view, "live"); await assert.rejects(svc.switchView("ko")); assert.strictEqual(svc.view, "live", "échec → la vue revient"); await svc.switchSet("default", true); assert.strictEqual(svc.view, "set", "basculer de jeu remet la vue du jeu");
  assert.deepEqual(await svc.relaunchState(), { show: true, count: 1 }); assert.strictEqual(await svc.save(["1", "9"]), "💾 4 session(s) dans « Défaut » (+1 nouvelle)"); assert.deepStrictEqual(calls[calls.length - 1], ["add", "default", ["1", "9"]]);
  assert(svc.toggleSelMode()); svc.toggleSelected("1"); svc.toggleSelected("2"); svc.toggleSelected("1"); assert.deepStrictEqual([...svc.selected], ["2"]); svc.toggleSelected("1");
  assert.strictEqual(await svc.move("b", true), "→ 2 session(s) déplacée(s) vers « b »"); assert.deepStrictEqual(calls[calls.length - 1], ["move", { sids: ["2", "1"], to: "b", from: "default", copy: false }]); assert.strictEqual(svc.selected.size, 0, "RM2449 : la sélection est consommée"); assert(!svc.toggleSelMode() && svc.selected.size === 0);
  let res = await svc.createFromForm({ label: "Chantier X", seed: true, rule: {} }, ["1", "2"]); assert(res.ok && res.msg === "＋ jeu « Chantier X » — 2 session(s)" && svc.current === "chantier-x" && svc.view === "set" && store.karlSet === "chantier-x"); assert.deepStrictEqual(calls[calls.length - 1], ["create", { group: "chantier-x", label: "Chantier X", sids: ["1", "2"] }]);
  svc.ruleFormFor = "__new__"; res = await svc.createFromForm({ label: "Acme", seed: true, rule: { client: "acme" } }, ["1"]); assert(res.ok && /dérivé « Acme » — 2 session\(s\) · règle renseignée/.test(res.msg) && svc.ruleFormFor === null && calls[calls.length - 1][1].rule.client === "acme" && !calls[calls.length - 1][1].sids, "RM2741 : dérivé → rien versé, et on le dit");
  res = await svc.createFromForm({ label: "PM", seed: false, rule: {} }, []); assert(!res.ok && /existe déjà/.test(res.error)); res = await svc.createFromForm({ label: "", seed: false, rule: {} }, []); assert(!res.ok);
  svc.editing = "pm"; assert.strictEqual(await svc.applyRule({ client: "beta" }), "règle appliquée — 5 session(s)"); assert.deepStrictEqual(calls[calls.length - 1], ["rule", "pm", { client: "beta" }], "RM2955 : la règle s'applique au jeu RÉGLÉ"); assert.strictEqual(await svc.materialize(), "jeu figé — 3 session(s)"); assert.strictEqual(calls[calls.length - 1][1], "pm");
  assert.strictEqual(await svc.retention("7"), "les sessions inactives depuis 7 j sont masquées (jamais supprimées)"); assert.deepStrictEqual(calls[calls.length - 1], ["retention", "pm", 7]); assert.strictEqual(await svc.rename("Pilotage"), "jeu renommé : Pilotage"); assert.deepStrictEqual(calls[calls.length - 1], ["rename", "pm", "Pilotage"]); svc.editing = null; await svc.switchSet("default", true);
  assert.deepStrictEqual(svc.checkNewName("###"), { ok: false, error: "nom inexploitable — il faut au moins une lettre ou un chiffre" }); assert(/existe déjà/.test(svc.checkNewName("PM").error)); assert.deepStrictEqual(svc.checkNewName("Nuit 2"), { ok: true, name: "nuit-2" });
  svc.toggleSelMode(); svc.toggleSelected("5"); res = await svc.createFromSelection("Nuit 2", true); assert(res.ok && res.msg === "＋ « Nuit 2 » — 2 session(s), retirée(s) de « Défaut »" && svc.current === "nuit-2" && !svc.selMode && svc.selected.size === 0); assert.deepStrictEqual(calls[calls.length - 1], ["create", { group: "nuit-2", label: "Nuit 2", sids: ["5"], move_from: "default" }], "RM2673 : scinder = move_from");
  await svc.switchSet("default", true); svc.selected.add("6"); res = await svc.createFromSelection("Copie", false); assert(res.msg === "＋ « Copie » — 2 session(s), retirée(s) de « Défaut »" || /Copie/.test(res.msg)); assert(!calls[calls.length - 1][1].move_from, "sans scission : pas de move_from"); await svc.switchSet("default", true);
  assert.deepStrictEqual(svc.warnings({ set: { joined: false, reason: "plein", group: "pm", max: 3 } }), ["⚠ le jeu « PM » est plein (3) : la session tourne mais n'y a PAS été enregistrée"]);
  assert.deepStrictEqual(await svc.relaunch("pm"), { msg: "▶ 2 reprise(s)", failed: false }); assert.deepStrictEqual(calls[calls.length - 1], ["relaunch", "pm", false]); svc.setSpawnPref(true); assert(store.karlSetSpawn === "1"); await svc.relaunch("pm"); assert.strictEqual(calls[calls.length - 1][2], true, "RM2395 : la préférence de relance voyage");
  assert.strictEqual(await svc.restart({ rm_id: "12", restart: "auto" }), "⏸ RM12 attendra un clic"); assert.deepStrictEqual(calls[calls.length - 1], ["restart", "12", "default", "idle"]); await svc.restart({ rm_id: "s", is_ticket: false, group: "pm" }); assert.deepStrictEqual(calls[calls.length - 1], ["restart", "s", "pm", "auto"]);
  assert.deepStrictEqual(await svc.forget({ rm_id: "12", group: "pm" }), { grp: "pm", label: "RM12", undo: "u1", count: 1 }); assert.deepStrictEqual(calls[calls.length - 1], ["remove", "pm", "12"]); assert.strictEqual(await svc.undo("pm", "u1"), "↩ rétabli"); assert.deepStrictEqual(calls[calls.length - 1], ["restore", "pm", "u1"]);
  assert.deepStrictEqual(await svc.drop({ rm_id: "3" }), { undo: "u1", msg: "⊖ RM3 retirée de « Défaut » — elle tourne toujours" }); assert.deepStrictEqual(calls[calls.length - 1], ["remove", "default", "3"]);
  svc.setSpawnPref(false); res = await svc.resumeGhost({ rm_id: "7", engine: "claude", session_id: "sid7", resumable: true }); assert(res.msg === "▶ RM7 reprise"); assert.deepStrictEqual(calls[calls.length - 1], ["resume", { engine: "claude", session_id: "sid7", rm_id: "7", spawn: false }], "RM2536 : par identité, jamais par le jeu");
  res = await svc.resumeGhost({ rm_id: "8", resumable: false }); assert(res.msg === "▶ RM8 recréée (session neuve)" && calls[calls.length - 1][1].spawn === true && calls[calls.length - 1][1].engine === undefined, "RM2949 : perdue → neuve"); svc.setSpawnPref(true); await svc.resumeGhost({ rm_id: "9", resumable: true }); assert(calls[calls.length - 1][1].spawn === true, "…ou selon la préférence"); svc.setSpawnPref(false);
  svc.editing = "pm"; const h = await svc.history(); assert.deepStrictEqual(h, { versions: [{ id: "v2", at: now, count: 1 }], keep: 20 }, "RM2443 : les versions du jeu réglé"); assert.strictEqual(await svc.restore("v2"), "↩ « PM » rétabli — 2 session(s)"); assert.deepStrictEqual(calls[calls.length - 1], ["restore", "pm", "v2"]);
  assert.strictEqual(await svc.remove(), "🗑 jeu « PM » effacé"); assert.deepStrictEqual(calls[calls.length - 1], ["remove", "pm", undefined]); assert.strictEqual(svc.editing, null, "RM2955 : le jeu réglé n'existe plus → la carte revient au courant"); svc.editing = "pm"; await svc.remove("default"); assert.strictEqual(svc.editing, "pm", "effacer un autre jeu ne touche pas le jeu réglé");
  console.log("✓ service : courant serveur/repli, bascules réversibles, 💾, sélection, déplacer, créations (RM2741/2673), règle sur le jeu réglé (RM2955), relance/prix, ⟳ ⊖ annuler, reprise par identité (RM2536/2949), versions, effacement");
  console.log("\nTous les tests du modèle et du service des jeux passent.");
})().catch(e => { console.error("✗", e.stack || e.message); process.exit(1); });
