#!/usr/bin/env node
// Tests des jeux de sessions migrés (RM2889) — porte RM2955 (setEditOptions, jeu réglé ≠ jeu courant), RM2673 (setWritable : 💾 ⊖ ⟳ → déplacer /
// scinder jamais sur un dérivé), RM2741 (relaunchBtnState, newSetPlan, formulaire unifié), RM2439 (💾 additif = l'affichage), RM2442/2445/2446/2452
// (sélecteur vues/clients/jeux, courant serveur), RM2448/2449 (sélection, déplacer/copier), RM2450/2951 (avertissements), RM2451 (prix avant relance),
// RM2427/2443 (entrées, annuler, versions), RM2536/2949 (relance d'une tuile grise par identité, neuve si perdue).
"use strict";
const fs = require("fs"); const path = require("path"); const assert = require("assert"); const DIR = __dirname;
const html = fs.readFileSync(path.join(DIR, "index.html"), "utf8");
function fakeEl(id, extra) { const L = []; let inner = ""; const self = Object.assign({ id, style: {}, value: "", dataset: {}, kids: {}, textContent: "", title: "", checked: false, disabled: false, classList: { on: new Set(), toggle(c, v) { v ? this.on.add(c) : this.on.delete(c); }, contains(c) { return this.on.has(c); } }, get innerHTML() { return inner; }, set innerHTML(v) { inner = v; }, contains: () => true,
  querySelector(sel) { return self.kids[sel] || null; }, addEventListener(t, f) { L.push([t, f]); }, removeEventListener(t, f) { const i = L.findIndex(([a, b]) => a === t && b === f); if (i >= 0) L.splice(i, 1); }, get listenerCount() { return L.length; },
  async fire(type, target) { for (const [t, f] of [...L]) if (t === type) await f({ target, preventDefault() {}, stopPropagation() {} }); await new Promise(r => setTimeout(r, 0)); },   // les gestes ne sont pas attendus par l'écouteur : on laisse la chaîne finir
  async click(action, data) { const n = { dataset: Object.assign({ action }, data || {}), closest: () => n, disabled: false }; for (const [t, f] of [...L]) if (t === "click") await f({ target: n, preventDefault() {}, stopPropagation() {} }); await new Promise(r => setTimeout(r, 0)); return n; } }, extra || {}); return self; }
(async () => {
  const M = await import(path.join(DIR, "src/models/sessions/sets.js"));
  const { SetsService } = await import(path.join(DIR, "src/services/sets.service.js"));
  const VM = await import(path.join(DIR, "src/viewmodels/sessions/SetsViewModel.js"));
  const V = await import(path.join(DIR, "src/views/sessions/Sets.view.js"));
  const { mountSets } = await import(path.join(DIR, "src/controllers/sets.controller.js"));

  // — RM2955 : setEditOptions —
  const SETS_2955 = [{ name: "default", label: "sessions actives", count: 12, alive: 5 }, { name: "pm", label: "PM", count: 3, alive: 1, derived: true }, { name: "nuit", count: 0, alive: 0 }];
  let opts = M.setEditOptions(SETS_2955, null, "pm");
  assert.deepStrictEqual(opts.map(o => o.value), ["default", "pm", "nuit"]); assert.strictEqual(opts.find(o => o.value === "pm").selected, true, "sans choix explicite, la carte suit le jeu courant");
  assert(opts.find(o => o.value === "pm").label.includes("● courant") && opts.find(o => o.value === "pm").label.startsWith("⚙ ") && !opts.find(o => o.value === "default").label.includes("● courant"));
  assert.strictEqual(opts.find(o => o.value === "default").label, "sessions actives (5/12)"); assert.strictEqual(M.setEditOptions(SETS_2955, "nuit", "pm").find(o => o.selected).value, "nuit", "un choix explicite l'emporte");
  assert(M.setEditOptions(SETS_2955, "nuit", "pm").find(o => o.value === "pm").label.includes("● courant")); assert.strictEqual(M.setEditOptions(null, null, "pm").length, 0); assert.strictEqual(M.setEditOptions([{ name: "x" }], null, "pm")[0].label, "x (0/0)");
  // — RM2673 : setWritable —
  const SETS = [{ name: "default", label: "default" }, { name: "pm", label: "PM", derived: true, rule: { client: "iprospective", project: "pm-ai-agents" } }];
  assert.strictEqual(M.setWritable(SETS, "default", "set"), true); assert.strictEqual(M.setWritable(SETS, "pm", "set"), false); assert.strictEqual(M.setWritable(SETS, "pm", "live"), false, "le jeu dérivé reste la cible en vue « sessions ouvertes »"); assert.strictEqual(M.setWritable(SETS, "pm", "all"), false);
  assert.strictEqual(M.setWritable(SETS, "default", "client:acme"), false, "RM2536 : une vue par client ne désigne aucun jeu"); assert.strictEqual(M.setWritable(SETS, "inconnu", "set"), true); assert.strictEqual(M.setWritable(null, "pm", null), true);
  // — RM2741 : relaunchBtnState, newSetPlan —
  const SET = { exists: true, count: 4, entries: [{ sid: "1", alive: true }, { sid: "2", alive: false }, { sid: "3", alive: false }, { sid: "4", alive: true }] };
  assert.deepEqual(M.relaunchBtnState(SET, "set"), { show: true, count: 2 }, "le compteur est celui des sessions ÉTEINTES"); assert.strictEqual(M.relaunchBtnState(SET, "live").show, false); assert.strictEqual(M.relaunchBtnState(SET, "all").show, false); assert.strictEqual(M.relaunchBtnState(SET, "client:acme").show, false);
  assert.strictEqual(M.relaunchBtnState({ exists: true, count: 2, entries: [{ alive: true }, { alive: true }] }, "set").show, false); assert.strictEqual(M.relaunchBtnState({ exists: false }, "set").show, false); assert.deepEqual(M.relaunchBtnState({ exists: true, count: 3 }, "set"), { show: true, count: 3 }, "sans entries : le total");
  const EXIST = ["default", "pm"];
  const manual = M.newSetPlan("chantier", "Chantier", {}, ["1", "2"], true, EXIST); assert.strictEqual(manual.kind, "manual"); assert.deepEqual(manual.body, { group: "chantier", label: "Chantier", sids: ["1", "2"] }); assert.strictEqual(manual.note, "");
  assert.deepEqual(M.newSetPlan("chantier", "Chantier", {}, ["1"], false, EXIST).body, { group: "chantier", label: "Chantier" }, "case décochée → jeu vide");
  const derived = M.newSetPlan("acme", "Acme", { client: "acme" }, ["1", "2"], true, EXIST); assert.strictEqual(derived.kind, "derived"); assert.deepEqual(derived.body, { group: "acme", label: "Acme", rule: { client: "acme" } }); assert(/pas versées/.test(derived.note));
  assert.strictEqual(M.newSetPlan("pm", "PM", {}, [], false, EXIST).ok, false); assert(/existe déjà/.test(M.newSetPlan("pm", "PM", {}, [], false, EXIST).error)); assert.strictEqual(M.newSetPlan("x", "", {}, [], false, EXIST).ok, false); assert.strictEqual(M.newSetPlan("", "###", {}, [], false, EXIST).ok, false);
  assert.strictEqual(M.slugifySet("Chantier Calicôte !"), "chantier-calicote"); assert.strictEqual(M.slugifySet("###"), ""); assert.strictEqual(M.slugifySet("a".repeat(40)).length, 32);
  assert.deepStrictEqual(M.ruleFromValues({ client: "acme", project: "", mark: "wip", tag: "", tickets: " 1, 2 ,, 3 " }), { client: "acme", mark: "wip", tickets: ["1", "2", "3"] }); assert.deepStrictEqual(M.ruleFromValues({}), {}); assert.strictEqual(M.ruleSummary({ client: "acme", tickets: ["1", "2"] }), "client=acme tickets=1,2");
  // — barre, sélecteur, textes —
  const bs = M.barState({ sets: SETS, current: "default", view: "set", selMode: false, selectedCount: 0 });
  assert(bs.saveShown && bs.saveLabel === "💾 → default" && /AFFICHÉES au jeu « default »/.test(bs.saveTitle) && bs.delTitle === "Supprimer le jeu « default » (les sessions continuent de tourner)" && bs.targets.length === 0 && !bs.canMove, "RM2673 : les destinations dérivées ne sont pas proposées");
  const bs2 = M.barState({ sets: [...SETS, { name: "b", label: "B", count: 2 }], current: "default", view: "set", selMode: true, selectedCount: 3 }); assert(bs2.saveLabel === "＋ jeu (3)" && bs2.canMove && bs2.targets.length === 1 && bs2.targets[0].label === "vers B (2)", "RM2449 : déplacer vers les autres jeux manuels");
  const bs3 = M.barState({ sets: [...SETS, { name: "b", label: "B" }], current: "pm", view: "live", selMode: false, selectedCount: 0 }); assert(!bs3.saveShown, "RM2452/RM2673 : 💾 masqué sur un jeu dérivé, quelle que soit la vue"); assert(M.barState({ sets: SETS, current: "pm", view: "set", selMode: true, selectedCount: 1 }).saveShown && !M.barState({ sets: [...SETS, { name: "b" }], current: "pm", view: "set", selMode: true, selectedCount: 1 }).canMove, "en sélection le bouton crée ; « → déplacer » exige un jeu source inscriptible");
  const pg = M.pickerGroups({ live_count: 4, all_count: 9, sessions_count: 12, client_views: [{ view: "client:acme", label: "acme", count: 2 }] }, SETS, "pm", "client:acme");
  assert.deepStrictEqual(pg.map(g => g.label), ["vues", "clients", "jeux"]); assert(pg[0].options[0].label === "▶ sessions ouvertes (4)" && pg[0].options[2].value === "view:sessions" && pg[1].options[0].selected && pg[1].options[0].label === "👤 acme (2)" && pg[2].options[1].value === "set:pm" && !pg[2].options[1].selected, "RM2446/2452/2954 : vues, clients, jeux ; la vue client est sélectionnée");
  const jeux = (r, sets, cur) => M.pickerGroups(r, sets, cur, "set").find(g => g.label === "jeux"); assert(jeux({}, SETS, "pm").options[1].selected && jeux({}, [], "default").options[0].label === "default (0)" && M.pickerGroups({}, SETS, "pm", "set").length === 2, "sans client : deux groupes seulement"); assert.deepStrictEqual(M.selButtonState(true), { text: "✓", title: "Terminer la sélection" });
  assert.strictEqual(M.saveSummary({ count: 5, added: ["a", "b"] }, "X"), "💾 5 session(s) dans « X » (+2 nouvelles)"); assert.strictEqual(M.saveSummary({ count: 5, added: [] }, "X"), "💾 5 session(s) dans « X » (rien de neuf)"); assert.strictEqual(M.saveSummary({}, "X"), "Aucune session à enregistrer");
  assert(/OK = les DÉPLACER \(retirées de « A »\)/.test(M.moveConfirmText(2, "B", "A"))); assert.strictEqual(M.moveSummary(["1", "2"], false, "B"), "⧉ 2 session(s) copiée(s) vers « B »"); assert.strictEqual(M.viewMessage("live"), "vue : sessions ouvertes"); assert.strictEqual(M.viewMessage("set", "X"), "vue : jeu « X »");
  assert(/Relancer 3 session\(s\) de « X »[^]*~12 k tokens[^]*de l'ordre de 2\.5 \$[^]*1 déjà active\(s\)[^]*2 sans conversation/.test(M.relaunchConfirmText({ relaunchable: 3, tokens_est: 12345, usd_est: 2.5, already_live: 1, lost: 2 }, "X")), "RM2451 : le prix avant");
  assert.deepStrictEqual(M.relaunchSummary({ resumed: 2, skipped: 1, failed: 1 }), { msg: "▶ 2 reprise(s) · 1 déjà active(s) · 1 échec(s)", failed: true }); assert.deepStrictEqual(M.relaunchSummary({}), { msg: "▶ rien à relancer", failed: false });
  assert.deepStrictEqual(M.spawnWarnings({ set: { joined: false, reason: "plein", group: "pm", max: 12 }, blocked: "approbation attendue" }, (n) => n.toUpperCase()), ["⚠ le jeu « PM » est plein (12) : la session tourne mais n'y a PAS été enregistrée", "⚠ approbation attendue"], "RM2450/RM2951"); assert.deepStrictEqual(M.spawnWarnings({ set: { joined: true } }, (n) => n), []);
  const g1 = M.ghostRelaunchText({ rm_id: "7", engine: "claude", cwd: "/w", resumable: true }); assert(!g1.neuve && /^Relancer la session RM7 \?/.test(g1.text) && /moteur : claude\ndossier : \/w/.test(g1.text) && /sera reprise/.test(g1.text) && g1.start === "▶ relance de RM7…");
  const g2 = M.ghostRelaunchText({ rm_id: "slug", is_ticket: false, resumable: false, model: "opus" }); assert(g2.neuve && /^Ouvrir une session NEUVE pour slug \?/.test(g2.text) && /modèle : opus/.test(g2.text) && /SANS le contexte d'avant/.test(g2.text), "RM2949 : conversation perdue → session neuve annoncée AVANT");
  assert.strictEqual(M.entryState({ alive: true }), "🟢 active"); assert.strictEqual(M.entryState({ resumable: true }), "🟡 reprenable"); assert.strictEqual(M.entryState({}), "🔴 perdue"); assert.strictEqual(M.entryLabel("12"), "RM12"); assert.strictEqual(M.entryLabel("slug"), "slug"); assert.strictEqual(M.sessionLabelOf({ rm_id: "3", is_ticket: false }), "3");
  assert.deepStrictEqual(M.historyFor([{ id: "a", at: 1, sets: [{ name: "x", count: 2 }] }, { id: "b", at: 2, sets: [{ name: "y", count: 1 }] }], "x"), [{ id: "a", at: 1, count: 2 }], "RM2443 : seules les versions contenant le jeu"); assert.strictEqual(M.restartMessage("auto", "RM1"), "⟳ RM1 redémarrera toute seule"); assert.strictEqual(M.retentionMessage(0), "plus rien n'est masqué"); assert(/7 j sont masquées/.test(M.retentionMessage("7")));
  console.log("✓ modèle : RM2955 options de la carte, RM2673 setWritable + barre, RM2741 relancer/nature du jeu, RM2446/2452 sélecteur, textes RM2449/2450/2451/2949");

  // — ViewModels et vues —
  const facets = { clients: [{ slug: "acme", count: 3, projects: ["shop", "api"] }, { slug: "beta", count: 1, projects: ["api"] }], tags: [{ tag: "urgent", count: 2 }] };
  const fNew = String(V.RuleForm(new VM.RuleFormViewModel({ rule: {}, isNew: true, shownCount: 5, facets })));
  assert(/id="rf-name"/.test(fNew) && /id="rf-seed"[^>]*checked/.test(fNew) && /5 session\(s\) affichée\(s\)/.test(fNew) && /manuel/.test(fNew) && /dérivé/.test(fNew) && /<option value="acme"[^>]*>acme \(3\)</.test(fNew) && /<option value="api"[^>]*>api</.test(fNew) && /<option value="urgent"/.test(fNew) && /<option value="wip"/.test(fNew) && /data-action="rule-apply" data-new="1">Créer</.test(fNew) && /data-action="rule-cancel"/.test(fNew) && !/onclick/.test(fNew), "RM2741 : formulaire unifié, facettes, gestes en data-action");
  assert(!/id="rf-seed"/.test(String(V.RuleForm(new VM.RuleFormViewModel({ rule: {}, isNew: true, shownCount: 0, facets })))), "sans session affichée, pas de case sans objet");
  const fEdit = String(V.RuleForm(new VM.RuleFormViewModel({ rule: { client: "acme", tickets: ["1", "2"] }, isNew: false, facets }))); assert(!/id="rf-name"/.test(fEdit) && !/id="rf-seed"/.test(fEdit) && /<option value="acme" selected>/.test(fEdit) && /value="1,2"/.test(fEdit) && /data-new="">Appliquer</.test(fEdit), "édition : ni nom ni peuplement, valeurs reprises");
  const SETS3 = [{ name: "default", label: "Défaut" }, { name: "pm", label: "PM", derived: true }];
  const now = Math.floor(Date.now() / 1000);
  const R = { exists: true, count: 2, label: "Défaut", saved_at: now - 3600, hide_idle_days: 7, entries: [{ sid: "12", engine: "claude", alive: true, restart: "auto", title: "Sujet 12", cwd: "/w/12" }, { sid: "slug", engine: "codex", resumable: false, last_active: now - 86400 }] };
  let vm = new VM.SetCardViewModel({ r: R, edited: "default", current: "default", sets: SETS3, ruleFormFor: null, facets, shownCount: 3, spawnPref: true });
  assert(vm.isCurrent && !vm.empty && vm.rows.length === 2 && vm.rows[0].editable && vm.rows[0].state === "🟢 active" && vm.rows[0].restartLabel === "⟳ auto" && /Redémarre toute seule/.test(vm.rows[0].restartTip) && vm.rows[1].state === "🔴 perdue" && vm.rows[1].inactive === "inactive depuis 1j" && vm.relaunchCount === 1 && vm.savedAgo === "1h" && vm.derivedHeader === null && !vm.newForm && !vm.editForm);
  let c = String(V.SetCard(vm));
  assert(/<b>Défaut<\/b> · 2 <span style="color:var\(--accent\)"[^>]*>● courant<\/span> session\(s\) · enregistré il y a 1h/.test(c) && /data-action="rename">✎</.test(c) && /<li><b>RM12<\/b> <span style="color:var\(--muted\)">claude<\/span> 🟢 active<span class="tkill"[^>]*data-action="entry-forget" data-sid="12">⊖<\/span><span[^>]*data-action="entry-restart" data-sid="12" data-restart="auto">⟳ auto<\/span><br><span style="font-size:11px">Sujet 12<\/span><br><span[^>]*>\/w\/12<\/span><\/li>/.test(c), "entrée éditable : ⊖ et ⟳ en data-action");
  assert(/<b>slug<\/b>[^]*🔴 perdue[^]*sans titre[^]*inactive depuis 1j · </.test(c) && /seulement s'il est le jeu courant\.<\/div>/.test(c) && /value="7" data-action="retention"/.test(c) && /checked data-action="spawn-pref"/.test(c) && /data-action="relaunch-card"[^>]*>▶ relancer \(1\)</.test(c) && /data-action="history">↩ versions</.test(c) && /data-action="delete">🗑 Effacer</.test(c) && /<div id="set-history"><\/div>/.test(c) && !/onclick|onchange/.test(c), "réglages et boutons sans on*");
  vm = new VM.SetCardViewModel({ r: Object.assign({}, R, { derived: true, rule: { client: "acme" }, truncated: true, total: 40 }), edited: "pm", current: "default", sets: SETS3, ruleFormFor: null, facets }); c = String(V.SetCard(vm));
  assert(/⚙ <b>jeu dérivé<\/b> — client=acme <span[^>]*data-action="rule-edit">modifier<\/span> · <span[^>]*data-action="materialize">figer<\/span>/.test(c) && !/entry-forget|entry-restart/.test(c) && !/● courant/.test(c) && / affichée\(s\) sur <b>40<\/b>/.test(c) && /\(ce n'est pas le cas ici\)/.test(c), "RM2673 : jeu dérivé — ni ⊖ ni ⟳ sur les entrées, modifier/figer offerts ; RM2452 : troncature dite ; RM2955 : pas courant");
  vm = new VM.SetCardViewModel({ r: Object.assign({}, R, { derived: true, rule: { client: "acme" } }), edited: "pm", current: "default", sets: SETS3, ruleFormFor: "pm", facets }); c = String(V.SetCard(vm)); assert(vm.editForm && /Règle du jeu/.test(c) && /<option value="acme" selected>/.test(c) && !/jeu dérivé<\/b> —/.test(c), "la règle s'édite dans le formulaire");
  vm = new VM.SetCardViewModel({ r: { exists: false }, edited: "pm", current: "default", sets: SETS3, ruleFormFor: "__new__", facets, shownCount: 2 }); c = String(V.SetCard(vm)); assert(vm.empty && /Nouveau jeu/.test(c) && /2 session\(s\) affichée\(s\)/.test(c) && /Jeu « PM » vide — c'est le jeu COURANT qui reçoit « 💾 »/.test(c), "vide + formulaire de création ; RM2955 : l'invite dit qui reçoit 💾");
  c = String(V.SetCard(new VM.SetCardViewModel({ r: { exists: true, count: 0 }, edited: "default", current: "default", sets: SETS3 }))); assert(/bouton « 💾 → Défaut » dans « ▶ en cours »/.test(c));
  c = String(V.History(new VM.HistoryViewModel({ versions: [{ id: "v1", at: now - 120, count: 3 }], keep: 20, label: "Défaut" }))); assert(/Rétablir « Défaut »/.test(c) && /data-action="restore" data-id="v1">↩ il y a 2min <span[^>]*>— 3 session\(s\)/.test(c)); assert(/Aucune version archivée pour « Défaut » \(max 20 conservées\)/.test(String(V.History(new VM.HistoryViewModel({ versions: [], keep: 20, label: "Défaut" })))));
  c = String(V.PickerOptions(M.pickerGroups({ live_count: 1 }, SETS3, "pm", "set"))); assert(/<optgroup label="vues"><option value="view:live">▶ sessions ouvertes \(1\)<\/option>/.test(c) && /<optgroup label="jeux"><option value="set:default">Défaut \(0\/undefined\)<\/option><option value="set:pm" selected>PM/.test(c)); assert.strictEqual(String(V.TargetOptions([{ value: "b", label: "vers B (2)" }])), '<option value="b">vers B (2)</option>');
  console.log("✓ ViewModels et vues : formulaire RM2741, carte (entrées RM2427/2673, dérivé RM2452, jeu réglé RM2955, réglages), versions RM2443, sélecteurs");

  // — service —
  const store = {}; const storage = { getItem: (k) => (k in store ? store[k] : null), setItem: (k, v) => { store[k] = v; } };
  const calls = []; let listResp = { sets: SETS3, current: "default", view: "set", facets, live_count: 1 };
  const repo = { async list() { calls.push(["list"]); return listResp; }, async get(g) { calls.push(["get", g]); return g === "pm" ? { exists: true, count: 3, derived: true, entries: [{ alive: false }, { alive: true }, { alive: false }] } : { exists: true, count: 2, entries: [{ sid: "1", alive: true }, { sid: "2" }] }; },
    async add(g, sids) { calls.push(["add", g, sids]); return { count: 4, added: ["9"] }; }, async remove(g, sid) { calls.push(["remove", g, sid]); return { undo: sid ? "u1" : undefined, count: 1 }; }, async setCurrent(b) { calls.push(["current", b]); if (b.group === "ko" || b.view === "ko") throw new Error("refusé"); listResp = Object.assign({}, listResp, b.group ? { current: b.group, view: "set" } : { view: b.view }); return {}; }, /* le serveur fait foi (RM2445) : il mémorise ce qu'on lui pose */
    async move(b) { calls.push(["move", b]); return { moved: ["1", "2"] }; }, async create(b) { calls.push(["create", b]); listResp = Object.assign({}, listResp, { current: b.group, view: "set", sets: [...(listResp.sets || []), { name: b.group, label: b.label, count: 2 }] }); return { count: 2, moved: b.move_from ? ["1"] : [] }; }, /* le jeu créé devient courant côté serveur */ async rule(g, r) { calls.push(["rule", g, r]); return { count: 5 }; }, async materialize(g) { calls.push(["materialize", g]); return { count: 3 }; },
    async retention(g, d) { calls.push(["retention", g, d]); return {}; }, async rename(g, l) { calls.push(["rename", g, l]); return {}; }, async estimate(g) { calls.push(["estimate", g]); return { relaunchable: 2, tokens_est: 3000, already_live: 1 }; }, async relaunch(g, sp) { calls.push(["relaunch", g, sp]); return { counts: { resumed: 2 } }; },
    async restart(sid, g, r) { calls.push(["restart", sid, g, r]); return {}; }, async restore(g, id) { calls.push(["restore", g, id]); return { count: 2 }; }, async history() { calls.push(["history"]); return { keep: 20, versions: [{ id: "v1", at: now - 60, sets: [{ name: "default", count: 2 }] }, { id: "v2", at: now, sets: [{ name: "pm", count: 1 }] }] }; },
    async resume(b) { calls.push(["resume", b]); return { spawned: !!b.spawn, blocked: b.rm_id === "blk" ? "approbation attendue" : undefined }; } };
  store.karlSet = "nuit";
  const svc = new SetsService({ repo, storage });
  assert(svc.current === "nuit" && svc.view === "set" && !svc.spawnPref && svc.editedSet() === "nuit", "le jeu courant est relu du navigateur");
  let ls = await svc.loadSets(); assert(svc.current === "default" && store.karlSet === "default" && ls.fallback === null && svc.sets.length === 2 && svc.facets === facets, "RM2445 : le serveur fait foi pour le jeu courant");
  listResp = { sets: SETS3, view: "live" }; store.karlSet = "zz"; svc.current = "zz"; ls = await svc.loadSets(); assert(ls.fallback === "default" && svc.view === "live", "jeu courant effacé ailleurs → repli sur le premier connu ; la vue vient du serveur"); listResp = { sets: SETS3, current: "default", view: "set", facets };
  await svc.loadSets(); assert.strictEqual(svc.label("pm"), "PM"); assert(svc.writable()); svc.view = "live"; assert(svc.writable(), "vue live sur un jeu manuel : inscriptible"); svc.view = "set";
  assert.strictEqual(await svc.switchSet("pm"), "jeu courant : PM"); assert(svc.current === "pm" && store.karlSet === "pm" && !svc.writable()); assert.strictEqual(await svc.switchSet("default", true), ""); await assert.rejects(svc.switchSet("ko")); assert.strictEqual(svc.current, "default", "échec serveur → le jeu courant revient");
  assert.strictEqual(await svc.switchView("live"), "vue : sessions ouvertes"); assert.strictEqual(svc.view, "live"); await assert.rejects(svc.switchView("ko")); assert.strictEqual(svc.view, "live", "échec → la vue revient"); await svc.switchSet("default", true); assert.strictEqual(svc.view, "set", "basculer de jeu remet la vue du jeu");
  assert.deepEqual(await svc.relaunchState(), { show: true, count: 1 }); assert.strictEqual(await svc.save(["1", "9"]), "💾 4 session(s) dans « Défaut » (+1 nouvelle)"); assert.deepStrictEqual(calls[calls.length - 1], ["add", "default", ["1", "9"]]);
  assert(svc.toggleSelMode()); svc.toggleSelected("1"); svc.toggleSelected("2"); svc.toggleSelected("1"); assert.deepStrictEqual([...svc.selected], ["2"]); svc.toggleSelected("1");
  assert.strictEqual(await svc.move("b", true), "→ 2 session(s) déplacée(s) vers « b »"); assert.deepStrictEqual(calls[calls.length - 1], ["move", { sids: ["2", "1"], to: "b", from: "default", copy: false }]); assert.strictEqual(svc.selected.size, 0, "RM2449 : la sélection est consommée"); assert(!svc.toggleSelMode() && svc.selected.size === 0);
  let res = await svc.createFromForm({ label: "Chantier X", seed: true, rule: {} }, ["1", "2"]); assert(res.ok && res.msg === "＋ jeu « Chantier X » — 2 session(s)" && svc.current === "chantier-x" && svc.view === "set" && store.karlSet === "chantier-x"); assert.deepStrictEqual(calls[calls.length - 1], ["create", { group: "chantier-x", label: "Chantier X", sids: ["1", "2"] }]);
  svc.ruleFormFor = "__new__"; res = await svc.createFromForm({ label: "Acme", seed: true, rule: { client: "acme" } }, ["1"]); assert(res.ok && /dérivé « Acme » — 2 session\(s\) · règle renseignée/.test(res.msg) && svc.ruleFormFor === null && calls[calls.length - 1][1].rule.client === "acme" && !calls[calls.length - 1][1].sids, "RM2741 : dérivé → rien versé, et on le dit");
  res = await svc.createFromForm({ label: "PM", seed: false, rule: {} }, []); assert(!res.ok && /existe déjà/.test(res.error)); res = await svc.createFromForm({ label: "", seed: false, rule: {} }, []); assert(!res.ok);
  svc.editing = "pm"; assert.strictEqual(await svc.applyRule({ client: "beta" }), "règle appliquée — 5 session(s)"); assert.deepStrictEqual(calls[calls.length - 1], ["rule", "pm", { client: "beta" }], "RM2955 : la règle s'applique au jeu RÉGLÉ"); assert.strictEqual(await svc.materialize(), "jeu figé — 3 session(s)"); assert.strictEqual(calls[calls.length - 1][1], "pm");
  assert.strictEqual(await svc.retention("7"), "les sessions inactives depuis 7 j sont masquées (jamais supprimées)"); assert.deepStrictEqual(calls[calls.length - 1], ["retention", "pm", 7]); assert.strictEqual(await svc.rename("Pilotage"), "jeu renommé : Pilotage"); assert.deepStrictEqual(calls[calls.length - 1], ["rename", "pm", "Pilotage"]); svc.editing = null; await svc.switchSet("default", true);
  assert.deepStrictEqual(svc.checkNewName("###"), { ok: false, error: "nom inexploitable — il faut au moins une lettre ou un chiffre" }); assert(/existe déjà/.test(svc.checkNewName("PM").error)); assert.deepStrictEqual(svc.checkNewName("Nuit 2"), { ok: true, name: "nuit-2" });
  svc.toggleSelMode(); svc.toggleSelected("5"); res = await svc.createFromSelection("Nuit 2", true); assert(res.ok && res.msg === "＋ « Nuit 2 » — 2 session(s), retirée(s) de « Défaut »" && svc.current === "nuit-2" && !svc.selMode && svc.selected.size === 0); assert.deepStrictEqual(calls[calls.length - 1], ["create", { group: "nuit-2", label: "Nuit 2", sids: ["5"], move_from: "default" }], "RM2673 : scinder = move_from");
  await svc.switchSet("default", true); svc.selected.add("6"); res = await svc.createFromSelection("Copie", false); assert(res.msg === "＋ « Copie » — 2 session(s), retirée(s) de « Défaut »" || /Copie/.test(res.msg)); assert(!calls[calls.length - 1][1].move_from, "sans scission : pas de move_from"); await svc.switchSet("default", true);
  assert.deepStrictEqual(svc.warnings({ set: { joined: false, reason: "plein", group: "pm", max: 3 } }), ["⚠ le jeu « PM » est plein (3) : la session tourne mais n'y a PAS été enregistrée"]);
  assert.deepStrictEqual(await svc.relaunch("pm"), { msg: "▶ 2 reprise(s)", failed: false }); assert.deepStrictEqual(calls[calls.length - 1], ["relaunch", "pm", false]); svc.setSpawnPref(true); assert(store.karlSetSpawn === "1"); await svc.relaunch("pm"); assert.strictEqual(calls[calls.length - 1][2], true, "RM2395 : la préférence de relance voyage");
  assert.strictEqual(await svc.restart({ rm_id: "12", restart: "auto" }), "⏸ RM12 attendra un clic"); assert.deepStrictEqual(calls[calls.length - 1], ["restart", "12", "default", "idle"]); await svc.restart({ rm_id: "s", is_ticket: false, group: "pm" }); assert.deepStrictEqual(calls[calls.length - 1], ["restart", "s", "pm", "auto"]);
  assert.deepStrictEqual(await svc.forget({ rm_id: "12", group: "pm" }), { grp: "pm", label: "RM12", undo: "u1", count: 1 }); assert.deepStrictEqual(calls[calls.length - 1], ["remove", "pm", "12"]); assert.strictEqual(await svc.undo("pm", "u1"), "↩ rétabli"); assert.deepStrictEqual(calls[calls.length - 1], ["restore", "pm", "u1"]);
  assert.deepStrictEqual(await svc.drop({ rm_id: "3" }), { undo: "u1", msg: "⊖ RM3 retirée de « Défaut » — elle tourne toujours" }); assert.deepStrictEqual(calls[calls.length - 1], ["remove", "default", "3"]);
  svc.setSpawnPref(false); res = await svc.resumeGhost({ rm_id: "7", engine: "claude", session_id: "sid7", resumable: true }); assert(res.msg === "▶ RM7 reprise"); assert.deepStrictEqual(calls[calls.length - 1], ["resume", { engine: "claude", session_id: "sid7", rm_id: "7", spawn: false }], "RM2536 : par identité, jamais par le jeu");
  res = await svc.resumeGhost({ rm_id: "8", resumable: false }); assert(res.msg === "▶ RM8 recréée (session neuve)" && calls[calls.length - 1][1].spawn === true && calls[calls.length - 1][1].engine === undefined, "RM2949 : perdue → neuve"); svc.setSpawnPref(true); await svc.resumeGhost({ rm_id: "9", resumable: true }); assert(calls[calls.length - 1][1].spawn === true, "…ou selon la préférence"); svc.setSpawnPref(false);
  svc.editing = "pm"; const h = await svc.history(); assert.deepStrictEqual(h, { versions: [{ id: "v2", at: now, count: 1 }], keep: 20 }, "RM2443 : les versions du jeu réglé"); assert.strictEqual(await svc.restore("v2"), "↩ « PM » rétabli — 2 session(s)"); assert.deepStrictEqual(calls[calls.length - 1], ["restore", "pm", "v2"]);
  assert.strictEqual(await svc.remove(), "🗑 jeu « PM » effacé"); assert.deepStrictEqual(calls[calls.length - 1], ["remove", "pm", undefined]); assert.strictEqual(svc.editing, null, "RM2955 : le jeu réglé n'existe plus → la carte revient au courant"); svc.editing = "pm"; await svc.remove("default"); assert.strictEqual(svc.editing, "pm", "effacer un autre jeu ne touche pas le jeu réglé");
  console.log("✓ service : courant serveur/repli, bascules réversibles, 💾, sélection, déplacer, créations (RM2741/2673), règle sur le jeu réglé (RM2955), relance/prix, ⟳ ⊖ annuler, reprise par identité (RM2536/2949), versions, effacement");

  // — contrôleur —
  const picker = fakeEl("set-picker"), save = fakeEl("btn-set-save"), del = fakeEl("btn-set-del"), selB = fakeEl("btn-sel"), target = fakeEl("sel-target"), moveB = fakeEl("btn-sel-move"), relB = fakeEl("btn-relaunch"), editPicker = fakeEl("set-edit-picker"), body = fakeEl("sessions-set-body"), hist = fakeEl("set-history");
  const rfName = fakeEl("rf-name"), rfSeed = fakeEl("rf-seed"), rfClient = fakeEl("rf-client"), rfProject = fakeEl("rf-project"), rfTag = fakeEl("rf-tag"), rfMark = fakeEl("rf-mark"), rfTickets = fakeEl("rf-tickets");
  const bar = fakeEl("setbar"), card = fakeEl("sessions-set-card");
  Object.assign(bar.kids, { "#set-picker": picker, "#btn-set-save": save, "#btn-set-del": del, "#btn-sel": selB, "#sel-target": target, "#btn-sel-move": moveB, "#btn-relaunch": relB });
  Object.assign(card.kids, { "#set-edit-picker": editPicker, "#sessions-set-body": body, "#set-history": hist, "#rf-name": rfName, "#rf-seed": rfSeed, "#rf-client": rfClient, "#rf-project": rfProject, "#rf-tag": rfTag, "#rf-mark": rfMark, "#rf-tickets": rfTickets });
  const ev = []; let ok = true; let promptAnswer = "Nuit 3"; const shown = [{ rm_id: "1" }, { rm_id: "77", ghost: true }];
  const svc2 = new SetsService({ repo, storage: { getItem: () => null, setItem: () => {} } }); listResp = { sets: SETS3, current: "default", view: "set", facets, live_count: 1, all_count: 2 };
  const ctr = mountSets({ bar, card }, { service: svc2, notify: (m, e) => ev.push(["toast", m, !!e]), notifyAction: (m, l, fn) => ev.push(["action", m, l, fn]), confirm: (m) => { ev.push(["confirm", m]); return ok; }, prompt: (m) => { ev.push(["prompt", m]); return promptAnswer; }, later: (fn) => fn(), ordered: () => shown, refreshSessions: () => ev.push("sessions"), attach: (rm) => ev.push(["attach", rm]) });
  calls.length = 0; await ctr.refreshSets();
  assert(/<optgroup label="vues"><option value="view:live">▶ sessions ouvertes \(1\)/.test(picker.innerHTML) && /<option value="set:default" selected>Défaut/.test(picker.innerHTML) && picker.style.display === "" && save.textContent === "💾 → Défaut" && save.style.display === "" && /« Défaut »/.test(del.title) && selB.textContent === "☑" && target.style.display === "none" && moveB.style.display === "none", "RM2442/2446 : sélecteur et barre peints");
  await new Promise(r => setTimeout(r, 0));   // ▶ relancer est relu sans être attendu (comme l'original)
  assert(calls.some(c => c[0] === "get" && c[1] === "default") && relB.textContent === "▶ relancer (1)" && relB.style.display === "", "RM2741 : ▶ relancer relu avec la vue, compte les éteintes");
  await ctr.load(); assert(/<option value="default" selected>Défaut \(0\/0\) ● courant<\/option>/.test(editPicker.innerHTML) && /<b>default<\/b> · 2/.test(body.innerHTML) && /data-action="entry-forget" data-sid="2"/.test(body.innerHTML), "RM2955 : la carte suit le jeu courant et liste ses entrées (libellé serveur absent → slug)");
  // sélecteur
  ev.length = 0; calls.length = 0; picker.value = "set:pm"; await bar.fire("change", picker); await new Promise(r => setTimeout(r, 0)); assert(calls.some(c => c[0] === "current" && c[1].group === "pm") && svc2.current === "pm" && ev.some(x => x[0] === "toast" && x[1] === "jeu courant : PM") && ev.includes("sessions"), "choisir un jeu : serveur prévenu, liste rafraîchie");
  assert(save.style.display === "none", "RM2452/2673 : 💾 masqué sur un jeu dérivé"); picker.value = "view:live"; await bar.fire("change", picker); await new Promise(r => setTimeout(r, 0)); assert(svc2.view === "live" && ev.some(x => x[1] === "vue : sessions ouvertes")); picker.value = "set:default"; await bar.fire("change", picker); await new Promise(r => setTimeout(r, 0)); assert(svc2.current === "default" && svc2.view === "set");
  // sélection → ＋ jeu (n), déplacer
  ev.length = 0; await bar.click("sel"); await new Promise(r => setTimeout(r, 0)); assert(svc2.selMode && selB.textContent === "✓" && selB.classList.contains("active") && save.textContent === "＋ jeu (0)" && ev.includes("sessions"), "RM2448 : le bouton dit son rôle");
  svc2.selected.add("1"); svc2.selected.add("2"); await ctr.refreshSets(); assert(save.textContent === "＋ jeu (2)" && target.style.display === "none" && moveB.style.display === "none", "RM2673 : pas de destination — seul autre jeu est dérivé");
  listResp = { sets: [...SETS3, { name: "b", label: "B", count: 1 }], current: "default", view: "set", facets }; await ctr.refreshSets(); assert(target.style.display === "" && moveB.style.display === "" && /<option value="b">vers B \(1\)<\/option>/.test(target.innerHTML), "RM2449 : destinations manuelles");
  ev.length = 0; calls.length = 0; target.value = "b"; ok = false; await bar.click("move"); assert(ev.some(x => x[0] === "confirm" && /DÉPLACER/.test(x[1])) && calls.some(c => c[0] === "move" && c[1].copy === true && c[1].to === "b") && ev.some(x => x[0] === "toast" && /⧉ 2 session\(s\) copiée\(s\) vers « B »/.test(x[1])), "Annuler = copier"); ok = true;
  ev.length = 0; target.value = ""; await bar.click("move"); assert(ev.some(x => x[0] === "toast" && x[1] === "aucun jeu de destination" && x[2]));
  svc2.selMode = true; svc2.selected.add("1"); ev.length = 0; calls.length = 0; await bar.click("save"); assert(ev.some(x => x[0] === "prompt" && /1 session\(s\) retenue\(s\)/.test(x[1])) && ev.some(x => x[0] === "confirm" && /RETIRER du jeu « Défaut » \(scinder\)/.test(x[1])) && calls.some(c => c[0] === "create" && c[1].group === "nuit-3" && c[1].move_from === "default") && svc2.current === "nuit-3" && !svc2.selMode && selB.textContent === "☑", "en sélection, 💾 crée un jeu ; scinder proposé (jeu inscriptible) ; le nouveau jeu devient courant");
  await ctr.switchSet("default", true); ev.length = 0; calls.length = 0; await bar.click("save"); assert(calls.some(c => c[0] === "add" && c[1] === "default" && c[2].join() === "1,77") && ev.some(x => x[0] === "toast" && /💾 4 session\(s\) dans « Défaut »/.test(x[1])), "RM2439 : 💾 verse les sid AFFICHÉS, fantômes compris");
  svc2.selMode = true; svc2.selected.add("1"); promptAnswer = "PM"; ev.length = 0; calls.length = 0; await bar.click("save"); assert(ev.some(x => x[0] === "toast" && /existe déjà/.test(x[1]) && x[2]) && !calls.some(c => c[0] === "create") && !ev.some(x => x[0] === "confirm"), "nom pris : refusé AVANT la question de scission"); svc2.selMode = false; svc2.selected.clear(); promptAnswer = "Nuit 3";
  // relancer (barre), avec le prix
  ev.length = 0; calls.length = 0; await bar.click("relaunch"); assert(calls.some(c => c[0] === "estimate" && c[1] === "default") && ev.some(x => x[0] === "confirm" && /Relancer 2 session\(s\) de « Défaut »[^]*~3 k tokens/.test(x[1])) && calls.some(c => c[0] === "relaunch" && c[1] === "default") && ev.some(x => x[1] === "▶ 2 reprise(s)") && ev.includes("sessions"), "RM2451 : estimation, confirmation, relance du jeu COURANT");
  ok = false; calls.length = 0; await bar.click("relaunch"); assert(!calls.some(c => c[0] === "relaunch"), "refus → rien"); ok = true;
  // ＋ jeu → formulaire dans la carte → créer
  ev.length = 0; await bar.click("new-set"); await new Promise(r => setTimeout(r, 0)); assert(svc2.ruleFormFor === "__new__" && /Nouveau jeu/.test(body.innerHTML) && /2 session\(s\) affichée\(s\)/.test(body.innerHTML), "RM2741 : le formulaire s'ouvre dans la carte");
  rfName.value = "Acme"; rfSeed.checked = true; rfClient.value = "acme"; rfTickets.value = "1, 2"; calls.length = 0; ev.length = 0; await card.click("rule-apply", { new: "1" }); assert(calls.some(c => c[0] === "create" && c[1].group === "acme" && c[1].rule.client === "acme" && c[1].rule.tickets.join() === "1,2" && !c[1].sids) && ev.some(x => x[0] === "toast" && /dérivé « Acme »/.test(x[1])) && svc2.current === "acme" && svc2.ruleFormFor === null, "créer : dérivé, devient courant");
  await ctr.switchSet("default", true); svc2.ruleFormFor = "__new__"; rfClient.value = ""; rfTickets.value = ""; rfName.value = ""; ev.length = 0; calls.length = 0; await card.click("rule-apply", { new: "1" }); assert(ev.some(x => x[0] === "toast" && x[1] === "donne un nom au jeu" && x[2]) && !calls.some(c => c[0] === "create")); await card.click("rule-cancel"); assert(svc2.ruleFormFor === null);
  svc2.editing = "pm"; await ctr.load(); assert(/jeu dérivé<\/b>/.test(body.innerHTML)); await card.click("rule-edit"); assert(svc2.ruleFormFor === "pm" && /Règle du jeu/.test(body.innerHTML), "modifier : la règle s'édite"); rfClient.value = ""; ev.length = 0; await card.click("rule-apply", { new: "" }); assert(ev.some(x => x[1] === "règle vide : elle désignerait toutes les sessions" && x[2]), "RM2741 : règle vide refusée à l'édition");
  rfClient.value = "beta"; calls.length = 0; await card.click("rule-apply", { new: "" }); assert(calls.some(c => c[0] === "rule" && c[1] === "pm" && c[2].client === "beta"), "RM2955 : appliquée au jeu réglé");
  ev.length = 0; calls.length = 0; await card.click("materialize"); assert(ev.some(x => x[0] === "confirm" && /Figer « PM »/.test(x[1])) && calls.some(c => c[0] === "materialize" && c[1] === "pm") && ev.some(x => x[1] === "jeu figé — 3 session(s)"));
  // carte : sélecteur du jeu réglé, entrées, réglages, versions, effacer
  editPicker.value = "default"; await card.fire("change", editPicker); assert(svc2.editing === "default" && svc2.current === "default", "RM2955 : régler un jeu ne bascule pas le courant"); editPicker.value = ""; await card.fire("change", editPicker); assert(svc2.editing === null);
  svc2.editing = "pm"; ev.length = 0; calls.length = 0; await card.click("entry-forget", { sid: "12" }); assert(calls.some(c => c[0] === "remove" && c[1] === "pm" && c[2] === "12") && ev.some(x => x[0] === "action" && /⊖ RM12 retirée de « PM »/.test(x[1]) && x[2] === "annuler"), "RM2427/2451 : retirée, annulation proposée"); calls.length = 0; ev.find(x => x[0] === "action")[3](); await new Promise(r => setTimeout(r, 0)); assert(calls.some(c => c[0] === "restore" && c[1] === "pm" && c[2] === "u1"), "annuler → restauration du seul jeu");
  calls.length = 0; ev.length = 0; await card.click("entry-restart", { sid: "slug", restart: "idle" }); assert(calls.some(c => c[0] === "restart" && c[1] === "slug" && c[2] === "pm" && c[3] === "auto") && ev.some(x => x[1] === "⟳ slug redémarrera toute seule"));
  ev.length = 0; calls.length = 0; promptAnswer = "Pilotage"; await card.click("rename"); assert(ev.some(x => x[0] === "prompt" && /Nouveau libellé/.test(x[1])) && calls.some(c => c[0] === "rename" && c[1] === "pm" && c[2] === "Pilotage"));
  const ret = { dataset: { action: "retention" }, value: "3" }; calls.length = 0; await card.fire("change", ret); assert(calls.some(c => c[0] === "retention" && c[1] === "pm" && c[2] === 3)); await card.fire("change", { dataset: { action: "spawn-pref" }, checked: true }); assert(svc2.spawnPref === true);
  calls.length = 0; ev.length = 0; await card.click("relaunch-card"); assert(calls.some(c => c[0] === "estimate" && c[1] === "pm") && calls.some(c => c[0] === "relaunch" && c[1] === "pm" && c[2] === true), "RM2955 : depuis la carte, le jeu RÉGLÉ est relancé, avec la préférence");
  hist.innerHTML = ""; await card.click("history"); assert(/data-action="restore" data-id="v2"/.test(hist.innerHTML) && !/v1/.test(hist.innerHTML), "RM2443 : versions du jeu réglé"); await card.click("history"); assert.strictEqual(hist.innerHTML, "", "second clic : replié");
  hist.innerHTML = "x"; calls.length = 0; ev.length = 0; await card.click("restore", { id: "v2" }); assert(ev.some(x => x[0] === "confirm" && /Rétablir « PM »/.test(x[1])) && calls.some(c => c[0] === "restore" && c[1] === "pm" && c[2] === "v2") && hist.innerHTML === "" && ev.some(x => /rétabli — 2 session\(s\)/.test(x[1])));
  calls.length = 0; ev.length = 0; await card.click("delete"); assert(ev.some(x => x[0] === "confirm" && /Supprimer le jeu « PM »/.test(x[1])) && calls.some(c => c[0] === "remove" && c[1] === "pm" && c[2] === undefined) && svc2.editing === null, "🗑 de la carte : le jeu RÉGLÉ");
  calls.length = 0; ev.length = 0; await bar.click("delete"); assert(ev.some(x => x[0] === "confirm" && /Supprimer le jeu « Défaut »/.test(x[1])) && calls.some(c => c[0] === "remove" && c[1] === "default"), "🗑 de la barre : le jeu COURANT");
  // gestes prêtés à la liste
  ev.length = 0; calls.length = 0; await ctr.dropFromSet({ rm_id: "3" }); assert(calls.some(c => c[0] === "remove" && c[1] === "default" && c[2] === "3") && ev.some(x => x[0] === "action" && /⊖ RM3 retirée de « Défaut » — elle tourne toujours/.test(x[1])) && ev.includes("sessions"), "RM2446 : ⊖ d'une vivante");
  svc2.setSpawnPref(false); ev.length = 0; calls.length = 0; await ctr.relaunchGhost({ rm_id: "7", engine: "claude", session_id: "s7", resumable: true }); assert(ev.some(x => x[0] === "confirm" && /^Relancer la session RM7/.test(x[1])) && ev.some(x => x[1] === "▶ relance de RM7…") && calls.some(c => c[0] === "resume" && c[1].session_id === "s7") && ev.some(x => x[1] === "▶ RM7 reprise") && ev.some(x => x[0] === "attach" && x[1] === "7"), "RM2427/2536 : relance par identité puis attache");
  ev.length = 0; await ctr.relaunchGhost({ rm_id: "blk", resumable: true }); assert(ev.some(x => x[0] === "toast" && x[1] === "⚠ approbation attendue" && x[2]), "RM2951 : un moteur bloqué ne reste pas muet"); ok = false; calls.length = 0; await ctr.relaunchGhost({ rm_id: "7" }); assert(!calls.some(c => c[0] === "resume")); ok = true;
  ev.length = 0; ctr.warnSpawn({ set: { joined: false, reason: "plein", group: "default", max: 12 } }); assert(ev.some(x => x[0] === "toast" && /est plein \(12\)/.test(x[1]) && x[2]), "RM2450");
  assert.deepStrictEqual(ctr.selection(), { on: false, set: svc2.selected }); assert.strictEqual(ctr.writable, M.setWritable); assert.strictEqual(ctr.label("pm"), "PM");
  ctr.unmount(); assert.strictEqual(bar.listenerCount + card.listenerCount, 0, "unmount libère tout");
  console.log("✓ contrôleur : sélecteur, barre (sélection, déplacer, 💾/＋ jeu, ▶ relancer, 🗑 courant), carte (formulaire, règle, entrées, réglages, versions, 🗑 réglé), gestes prêtés à la liste");

  // — hôtes et ponts dans index.html —
  ["setbar", "set-picker", "btn-set-save", "btn-set-del", "btn-sel", "sel-target", "btn-sel-move", "btn-relaunch", "sessions-set-card", "set-edit-picker", "sessions-set-body"].forEach(id => assert(html.includes('id="' + id + '"'), "hôte manquant : " + id));
  const barHtml = html.slice(html.indexOf('id="setbar"'), html.indexOf('id="runlist"')); assert(!/\son\w+=/.test(barHtml), "la barre des jeux ne porte plus de on*"); assert((barHtml.match(/data-action="/g) || []).length >= 6, "…ses gestes sont en data-action");
  const cardHtml = html.slice(html.indexOf('id="sessions-set-card"'), html.indexOf('id="sessions-set-body"')); assert(!/\son\w+=/.test(cardHtml) && /data-action="new-set"/.test(cardHtml), "la carte non plus");
  { const boot = fs.readFileSync(path.join(DIR, "src/boot.js"), "utf8"); assert(/setsCtl\.refreshSets\(\); setsCtl\.refreshSet\(\);/.test(boot) && /sessions: \(\) => \{ resume\.load\(\); setsCtl\.load\(\); \}/.test(boot), "boot.js : jeux relus à l'init, carte chargée à la première activation du panneau"); }
  for (const f of ["src/views/sessions/Sets.view.js", "src/controllers/sets.controller.js"]) assert(!/\son(click|change|input)=/.test(fs.readFileSync(path.join(DIR, f), "utf8")), "aucun handler inline dans " + f);
  console.log("✓ hôtes sans on*, ponts refreshSessionSets / refreshSessionSet / loadSessionSet en place");
  console.log("\nTous les tests des jeux de sessions passent.");
})().catch(e => { console.error("✗", e.stack || e.message); process.exit(1); });
