#!/usr/bin/env node
// Tests du terminal et du composer migrés (RM2889) — porte RM2561 (origine du WebSocket), RM2807 (client maison opt-in), RM2700
// (cookie de gate), RM2527 (garde d'état, historique, envoi client maison ou repli serveur, ↑/↓, Échap), RM2168/2631 (copies).
"use strict";
const path = require("path"); const assert = require("assert"); const DIR = __dirname; const settle = () => new Promise(r => setTimeout(r, 8));
function fakeEl(id, extra) { const L = []; let inner = ""; const self = Object.assign({ id, style: {}, value: "", textContent: "", title: "", innerHTML: "", kids: {}, get innerHTML() { return inner; }, set innerHTML(v) { inner = v; }, querySelector(sel) { return self.kids[sel] || null; }, getElementsByTagName: () => [1, 2], contains: () => true, setSelectionRange(a, b) { self.sel = [a, b]; }, focus() { self.focused = true; },
  addEventListener(t, f) { L.push([t, f]); }, removeEventListener(t, f) { const i = L.findIndex(([a, b]) => a === t && b === f); if (i >= 0) L.splice(i, 1); }, get listenerCount() { return L.length; },
  async fire(type, target, extra2) { for (const [t, f] of [...L]) if (t === type) await f(Object.assign({ target, preventDefault() {}, stopPropagation() {} }, extra2 || {})); },
  async click(action, extra2) { const n = { dataset: { action }, closest: () => n }; for (const [t, f] of [...L]) if (t === "click") await f(Object.assign({ target: n, preventDefault() {} }, extra2 || {})); } }, extra || {}); return self; }
(async () => {
  const M = await import(path.join(DIR, "src/models/terminal/terminal.js"));
  const { TerminalService } = await import(path.join(DIR, "src/services/terminal.service.js"));
  const VM = await import(path.join(DIR, "src/viewmodels/terminal/ComposerViewModel.js"));
  const V = await import(path.join(DIR, "src/views/terminal/Composer.view.js"));
  const { mountTerminal } = await import(path.join(DIR, "src/controllers/terminal.controller.js"));
  const https443 = { port: "", protocol: "https:", hostname: "karl.lxc", origin: "https://karl.lxc" };
  assert.strictEqual(M.termBase({ ttyd_base: "" }, https443), "https://karl.lxc/ttyd", "RM2561 : derrière le vhost, même origine"); assert.strictEqual(M.termBase({}, Object.assign({}, https443, { port: "443" })), "https://karl.lxc/ttyd"); assert.strictEqual(M.termBase({}, { port: "9876", protocol: "http:", hostname: "dev.local", origin: "http://dev.local:9876" }), "http://dev.local:7681", "accès direct : repli :7681"); assert.strictEqual(M.termBase({ ttyd_base: "https://ailleurs:1234" }, https443), "https://ailleurs:1234");
  assert.strictEqual(M.ttydUrl({}, { protocol: "http:", hostname: "h" }, "42"), "http://h:7681/?arg=42"); assert.strictEqual(M.ttydUrl({ ttyd_base: "https://t//" }, {}, "a b"), "https://t/?arg=a%20b");
  const st = (v) => ({ getItem: (k) => (k === "karl_xterm" ? v : null) }); assert.strictEqual(M.termAvailable(st("1"), { KarlTerm: {}, Terminal: {} }), true); assert.strictEqual(M.termAvailable(st(null), { KarlTerm: {}, Terminal: {} }), false, "RM2807 : l'iframe ttyd reste le défaut"); assert.strictEqual(M.termAvailable(st("1"), {}), false, "bundle absent : repli"); assert.strictEqual(M.termAvailable({ getItem() { throw new Error("privé"); } }, {}), false);
  assert.strictEqual(M.composerGuard("idle").allow, true); assert.strictEqual(M.composerGuard("working").allow, true); assert.strictEqual(M.composerGuard(undefined).allow, true); assert.strictEqual(M.composerGuard("choice").allow, false); assert.strictEqual(M.composerGuard("attention").allow, false); assert(/menu/i.test(M.composerGuard("choice").warn) && /question/i.test(M.composerGuard("attention").warn)); assert.strictEqual(M.composerGuard("idle").warn, null);
  assert.deepStrictEqual(M.composerHistoryAdd([], "a"), ["a"]); assert.deepStrictEqual(M.composerHistoryAdd(["a"], "b"), ["b", "a"]); assert.deepStrictEqual(M.composerHistoryAdd(["b", "a"], "a"), ["a", "b"]); assert.deepStrictEqual(M.composerHistoryAdd(["a"], "  a  "), ["a"]); assert.deepStrictEqual(M.composerHistoryAdd(["a"], "   "), ["a"]); assert.deepStrictEqual(M.composerHistoryAdd(null, "a"), ["a"]); assert.deepStrictEqual(M.composerHistoryAdd(["a", "b", "c"], "d", 3), ["d", "a", "b"]);
  assert.strictEqual(M.composerLabels(M.composerGuard("idle")).btn, "Envoyer ⏎"); assert.strictEqual(M.composerLabels(M.composerGuard("choice")).btn, "Envoyer quand même"); assert.strictEqual(M.truncate("abcdef", 3), "abc…"); assert.strictEqual(M.sessionCookie("t k", true), "karl_session=t%20k; Path=/; SameSite=Strict; Secure"); assert(!/Secure/.test(M.sessionCookie("t", false)));
  const cv = new VM.ComposerViewModel({ state: "choice", history: ["x".repeat(400), "b"] }); assert(!cv.allow && /menu/.test(String(V.ComposerWarn(cv))) && /<b>Envoi retenu\.<\/b>/.test(String(V.ComposerWarn(cv)))); const hh = String(V.ComposerHistory(cv)); assert(/class="hitem" data-i="0"[^>]*>x{300}…<\/div>/.test(hh) && /data-i="1"[^>]*>b</.test(hh) && !/onclick=/.test(hh)); assert(/Aucun message envoyé/.test(String(V.ComposerHistory(new VM.ComposerViewModel({ state: "idle", history: [] })))));
  console.log("✓ modèle et vue (RM2561/2807/2700/2527) : origine WebSocket, opt-in xterm, cookie de gate, garde, historique, libellés");
  const calls = []; const repo = { async send(sid, msg) { calls.push(["send", sid, msg]); if (msg === "ko") throw new Error("réseau"); }, async capture(sid, n) { calls.push(["capture", sid, n]); return "lignes…"; }, async buffer() { calls.push(["buffer"]); return repo.buf; }, async memdebug(p) { calls.push(["memdebug", p.rm]); } }; repo.buf = "copie tmux";
  const store = { d: {}, getItem(k) { return this.d[k] === undefined ? null : this.d[k]; }, setItem(k, v) { this.d[k] = String(v); } };
  const svc = new TerminalService({ repo, storage: store }); assert.deepStrictEqual(svc.history("42"), []); assert.deepStrictEqual(svc.remember("42", "a"), ["a"]); assert.deepStrictEqual(svc.remember("42", "b"), ["b", "a"]); assert.deepStrictEqual(JSON.parse(store.d["karlComposerHist:42"]), ["b", "a"], "l'historique est celui de CETTE session, dans ce navigateur");
  assert.deepStrictEqual(await svc.send({ send: () => true }, "42", "hi"), { ok: true }); assert.strictEqual(calls.length, 0, "client maison : la socket, pas le serveur"); assert(/déconnecté/.test((await svc.send({ send: () => false }, "42", "hi")).message)); assert.deepStrictEqual(await svc.send(null, "42", "hi"), { ok: true }); assert.deepStrictEqual(calls[0], ["send", "42", "hi"], "sans client maison : repli POST /send"); assert.strictEqual((await svc.send(null, "42", "ko")).message, "réseau");
  console.log("✓ service : historique par session, envoi par la socket du client maison sinon /send");
  const host = fakeEl("termhost"), frame = fakeEl("term"), composer = fakeEl("composer", { style: { display: "none" } }); const ta = fakeEl("cmptext"), warn = fakeEl("cmpwarn"), send = fakeEl("cmpsend"), hint = fakeEl("cmphint"), hist = fakeEl("cmphist", { style: { display: "none" } }), histbtn = fakeEl("cmphistbtn");
  Object.assign(composer.kids, { "#cmptext": ta, "#cmpwarn": warn, "#cmpsend": send, "#cmphint": hint, "#cmphist": hist, "#cmphistbtn": histbtn });
  const ev = []; let att = "42"; let sstate = "idle"; let cookie = ""; const fakeTerm = { fits: 0, disposed: 0, sent: [], fit() { this.fits++; }, dispose() { this.disposed++; }, send(t) { this.sent.push(t); return true; }, term: { focus() { ev.push("term-focus"); } } };
  const win = { KarlTerm: { attach: (h, sid, o) => { ev.push(["attach", sid, o.base]); return fakeTerm; } }, Terminal: {}, location: { port: "", protocol: "https:", hostname: "karl.lxc", origin: "https://karl.lxc" } };
  const store2 = { d: {}, getItem(k) { return this.d[k] === undefined ? null : this.d[k]; }, setItem(k, v) { this.d[k] = String(v); } };
  const ctr = mountTerminal({ host, frame, composer }, { service: new TerminalService({ repo, storage: store2 }), storage: store2, win, cfg: () => ({ auth_required: true }), notify: (m, e) => ev.push(["toast", m, !!e]), attached: () => att, sess: () => ({ "42": { state: sstate } }), token: () => "tok", setCookie: (c) => { cookie = c; }, clipboard: { writeText: async (t) => { if (t === "lignes…") ev.push(["clip", t]); else throw new Error("refus"); } }, copyFallback: (t) => { ev.push(["fallback", t]); return true; }, capture: (t, txt) => ev.push(["capture", t, txt]) });
  assert.strictEqual(ctr.mountTerm("42"), "iframe", "RM2807 : sans opt-in, l'iframe ttyd"); assert(frame.style.display === "block" && frame.src === "https://karl.lxc:7681/?arg=42" && host.style.display === "none" && composer.style.display === "flex", "iframe posée, composer affiché"); assert(/karl_session=tok; Path=\/; SameSite=Strict; Secure/.test(cookie), "RM2700 : cookie de gate posé depuis le token");
  assert(send.textContent === "Envoyer ⏎" && warn.style.display === "none" && /Entrée envoie/.test(hint.textContent));
  ta.value = "bonjour"; calls.length = 0; ev.length = 0; await composer.fire("keydown", ta, { key: "Enter" }); assert.deepStrictEqual(calls[0], ["send", "42", "bonjour"], "Entrée envoie ; sans client maison : /send"); assert(ta.value === "" && ev.some(x => x[0] === "toast" && /Envoyé : bonjour/.test(x[1])) && JSON.parse(store2.d["karlComposerHist:42"])[0] === "bonjour");
  sstate = "choice"; ctr.composerRefresh(); assert(send.textContent === "Envoyer quand même" && warn.style.display === "block" && /menu de choix/.test(warn.innerHTML) && /neutralisée/.test(hint.textContent), "RM2527 : la garde suit l'état live"); ta.value = "x"; calls.length = 0; ev.length = 0; await composer.fire("keydown", ta, { key: "Enter" }); assert(calls.length === 0 && ev.some(x => x[0] === "toast" && /menu/.test(x[1]) && x[2]), "Entrée neutralisée quand un menu est ouvert"); await composer.click("send"); assert.deepStrictEqual(calls[0], ["send", "42", "x"], "le bouton « Envoyer quand même » force"); sstate = "idle"; ctr.composerRefresh();
  ta.value = ""; await composer.fire("keydown", ta, { key: "ArrowUp" }); assert.strictEqual(ta.value, "x", "↑ dans un champ vide : le plus récent"); await composer.fire("keydown", ta, { key: "ArrowUp" }); assert.strictEqual(ta.value, "bonjour"); await composer.fire("keydown", ta, { key: "ArrowDown" }); assert.strictEqual(ta.value, "x"); await composer.fire("keydown", ta, { key: "ArrowDown" }); assert.strictEqual(ta.value, "", "↓ jusqu'au brouillon (vide)"); ta.value = "en cours"; await composer.fire("keydown", ta, { key: "ArrowUp" }); assert.strictEqual(ta.value, "en cours", "un champ non vide n'est pas piégé");
  await composer.click("history"); assert(hist.style.display === "block" && histbtn.textContent === "historique ▴" && /data-i="0"[^>]*>x</.test(hist.innerHTML) && /data-i="1"[^>]*>bonjour</.test(hist.innerHTML)); await hist.fire("click", { closest: (s) => (s === ".hitem" ? { dataset: { i: "1" } } : null) }); assert(ta.value === "bonjour" && ta.focused, "reprendre un message de l'historique"); await composer.click("history"); assert.strictEqual(hist.style.display, "none");
  ev.length = 0; calls.length = 0; await composer.click("copy", { altKey: false }); await settle(); assert.deepStrictEqual(calls[0], ["capture", "42", 300]); assert(ev.some(x => x[0] === "clip") && ev.some(x => x[0] === "toast" && /Copié — 300 dernières lignes/.test(x[1])), "RM2168 : 300 lignes au presse-papier"); ev.length = 0; await composer.click("copy", { altKey: true }); await settle(); assert(ev.some(x => x[0] === "capture" && x[1] === "Capture karl-42" && x[2] === "lignes…"), "Alt+clic : la fenêtre texte");
  ev.length = 0; await composer.click("pull"); await settle(); assert(ev.some(x => x[0] === "fallback" && x[1] === "copie tmux") && ev.some(x => x[0] === "toast" && /Copie du terminal récupérée/.test(x[1])), "RM2631 : la copie faite dans le terminal, presse-papier refusé → repli execCommand"); repo.buf = null; ev.length = 0; await composer.click("pull"); await settle(); assert(ev.some(x => x[0] === "toast" && /Aucune copie en attente/.test(x[1]) && x[2]));
  store2.d.karl_xterm = "1"; ev.length = 0; assert.strictEqual(ctr.mountTerm("42"), "xterm", "opt-in : client maison"); assert(ev.some(x => x[0] === "attach" && x[1] === "42" && x[2] === "https://karl.lxc/ttyd") && host.style.display === "block" && frame.style.display === "none" && ctr.session() === fakeTerm, "RM2561 : base même-origine"); await new Promise(r => setTimeout(r, 5)); assert(fakeTerm.fits >= 1, "ajusté après le premier rendu");
  ta.value = "via socket"; calls.length = 0; await composer.fire("keydown", ta, { key: "Enter" }); assert(fakeTerm.sent.includes("via socket") && calls.length === 0, "client maison : l'envoi emprunte la socket, même PTY qu'une frappe"); ev.length = 0; await composer.fire("keydown", ta, { key: "Escape" }); assert(ev.includes("term-focus"), "Échap rend la main au terminal");
  ctr.unmountTerm(); assert(fakeTerm.disposed === 1 && ctr.session() === null && host.style.display === "none" && frame.src === "about:blank" && composer.style.display === "none" && ta.value === "", "démonté : session libérée, surfaces cachées, composer vidé");
  att = null; ta.value = "x"; ev.length = 0; composer.style.display = "flex"; await ctr.composerSend(); assert(ev.some(x => x[0] === "toast" && /Aucune session attachée/.test(x[1])));
  ctr.unmount(); assert.strictEqual(composer.listenerCount + hist.listenerCount, 0);
  console.log("✓ contrôleur : iframe par défaut + cookie de gate, client maison sur opt-in, composer (Entrée, garde, forçage, ↑/↓, historique, Échap), copies, démontage");
  console.log("\nTous les tests du terminal passent.");
})().catch(e => { console.error("✗", e.message); process.exit(1); });
