#!/usr/bin/env node
// Tests du worklog de session migré (RM2889) — porte RM2466 (décors, sections, notifications), RM2581 (fraîcheur), RM2584/2935 (documents),
// RM2605/2799 (numéro cliquable), RM2610 (sous-onglets), RM2695 (avancement), RM2716/2719/2720/2786 (lots), RM2723 (ligne de MR),
// RM2796 (dérive), RM2798 (groupes), RM2801 (étape de MR), RM2823/2831 (embarquer), RM2888 (menu de statut), RM2795 (marque).
"use strict";
const path = require("path"); const assert = require("assert"); const DIR = __dirname;
const settle = () => new Promise(r => setTimeout(r, 10));
const escO = s => String(s == null ? "" : s).replace(/[&<>"]/g, c => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" }[c]));
function fakeElement(id) { const L = []; let inner = ""; const kids = {}; return { id, kids, textContent: "", style: {}, dataset: {}, get innerHTML() { return inner; }, set innerHTML(v) { inner = v; }, contains: () => true, querySelector(sel) { return kids[sel] || null; },
  addEventListener(t, f) { L.push([t, f]); }, removeEventListener(t, f) { const i = L.findIndex(([a, b]) => a === t && b === f); if (i >= 0) L.splice(i, 1); }, get listenerCount() { return L.length; },
  async click(action, data, extra) { const n = Object.assign({ dataset: Object.assign({ action }, data || {}), closest: () => n }, extra || {}); for (const [t, f] of [...L]) if (t === "click") await f({ target: n, preventDefault() {}, stopPropagation() {} }); return n; } }; }
(async () => {
  const M = await import(path.join(DIR, "src/models/worklog/worklog.js"));
  const { WorklogService } = await import(path.join(DIR, "src/services/worklog.service.js"));
  const VM = await import(path.join(DIR, "src/viewmodels/worklog/WorklogViewModel.js"));
  const V = await import(path.join(DIR, "src/views/worklog/Worklog.view.js"));
  const { mountWorklog } = await import(path.join(DIR, "src/controllers/worklog.controller.js"));
  // — RM2466 : décors —
  const dLive = M.pendingDecor({ kind: "live", state: "attention" }), dChoice = M.pendingDecor({ kind: "live", state: "choice" }), dStale = M.pendingDecor({ kind: "stale" });
  assert(dLive.cls.includes("ounres") && !dStale.cls.includes("ounres") && dLive.icon !== dStale.icon && dLive.tag !== dStale.tag && dChoice.icon !== dLive.icon && /bloqu/i.test(dLive.tag) && /sans réponse/i.test(dStale.tag) && M.pendingDecor(null).tag && M.pendingDecor(undefined).icon);
  const nc = M.notifyDecor("critical"), nw = M.notifyDecor("warn"), ni = M.notifyDecor("info"); assert(nc.icon !== nw.icon && nw.icon !== ni.icon && nc.label === "critical" && nw.label === "warn" && ni.label === "info" && nc.cls.includes("ounres") && !ni.cls.includes("ounres")); assert.strictEqual(M.notifyDecor(undefined).label, "warn");
  // — sections, onglets, documents —
  assert.deepStrictEqual(M.worklogSections({ todo: [{ ref: "RM1" }], waiting: [{ ref: "RM2" }], done: [{ ref: "RM3" }] }).map(s => s.key), ["todo", "waiting", "done"]);
  assert.deepStrictEqual(M.worklogSections({ todo: [{ ref: "RM1" }], mep: [{ ref: "RM2" }, { ref: "RM3" }], done: [{ ref: "RM4" }] }).map(s => s.key), ["todo", "mep", "done"], "RM2860 : MEP entre à faire et fait");
  assert.deepStrictEqual(M.worklogSections({ todo: [{ ref: "RM1" }], testing: [{ ref: "RM2" }], mep: [{ ref: "RM4" }], waiting: [{ ref: "RM5" }], done: [{ ref: "RM6" }] }).map(s => s.key), ["todo", "testing", "mep", "waiting", "done"], "RM2930 : à tester avant la MEP");
  assert.strictEqual(M.worklogSections({ mep: [] }).length, 0); assert.strictEqual(M.worklogSections({ todo: [], waiting: [{ ref: "RM2" }], done: [] }).length, 1); assert.strictEqual(M.worklogSections(null).length, 0); assert(M.worklogSections({ todo: [{}] }).every(s => s.icon && s.label));
  const secs2 = [{ key: "todo", icon: "⏳", label: "reste à faire", items: [1, 2] }, { key: "done", icon: "✅", label: "fait", items: [1] }];
  assert.deepStrictEqual(M.worklogTabList(secs2, 3, 0).map(t => [t.key, t.n]), [["todo", 2], ["done", 1], ["documents", 3]]); assert.strictEqual(M.worklogTabList([], 0, 0).length, 0); assert.strictEqual(M.worklogTabList([], 2, 0)[0].key, "documents"); assert.strictEqual(M.worklogTabList([{ key: "done", icon: "x", label: "fait", items: [1] }], 0, 2)[0].key, "todo", "RM2610 : orphelines → onglet à faire");
  const wd = M.worklogDocs({ RM1: [["a.py", "output"], ["b.md", "output"]], RM2: [["c", ""]] }); assert.strictEqual(wd.length, 3); assert.deepStrictEqual(wd[0], { ref: "RM1", name: "a.py", kind: "output" }); assert.strictEqual(M.worklogDocs({ RM3: ["str-seul"] })[0].name, "str-seul"); assert.strictEqual(M.worklogDocs(null).length, 0);
  // — RM2798 groupes, RM2801 étape, RM2796 dérive, RM2695 avancement, RM2591 branches —
  const WL = [{ ref: "RM1", client: "calicote", project: "presta" }, { ref: "RM2", client: "abatik", project: "infra" }, { ref: "RM3", client: "calicote", project: "presta" }, { ref: "RM4" }];
  const g = M.groupWorklogItems(WL); assert.deepEqual(g.map(x => x.key), ["calicote / presta", "abatik / infra", "hors projet"]); assert.deepEqual(g[0].items.map(i => i.ref), ["RM1", "RM3"]); assert.strictEqual(M.groupWorklogItems([{ ref: "A", project: "infra" }])[0].key, "infra"); assert.strictEqual(M.groupWorklogItems([{ ref: "A", client: "abatik" }])[0].key, "abatik"); assert.deepEqual(M.groupWorklogItems(null), []);
  assert.strictEqual(M.mrStage(null), null); assert.strictEqual(M.mrStage({}), null); assert.strictEqual(M.mrStage({ stage: "inconnue" }), null);
  const ouv = M.mrStage({ stage: "open", url: "https://g/mr/1", count: 1, mrs: [{ iid: "1", state: "opened", target: "dev" }] }); assert(ouv.txt === "⇥ MR" && ouv.cls === "warn" && /à merger/.test(ouv.tip) && ouv.url === "https://g/mr/1"); const integ = M.mrStage({ stage: "integration", url: "u", count: 1, mrs: [] }); assert(integ.txt === "✓ dev" && integ.cls === "ok" && /par lot \(dev → main\)/.test(integ.tip)); assert.strictEqual(M.mrStage({ stage: "prod", url: "u", count: 1, mrs: [] }).txt, "✓ prod");
  const multi = M.mrStage({ stage: "prod", url: "u", count: 2, mrs: [{ iid: "1", state: "merged", target: "dev", repo: "a/b" }, { iid: "2", state: "merged", target: "main" }] }); assert(/!1 merged → dev \(a\/b\)/.test(multi.tip) && /!2 merged → main/.test(multi.tip) && /2 MR/.test(multi.tip));
  assert.deepStrictEqual(M.statusInfo({ status: "en_cours" }), { status: "en_cours", drifted: false, tip: "" }); const der = M.statusInfo({ status: "a_tester_demandeur", opened_status: "en_cours", drifted: true }); assert(der.drifted && /en_cours → a_tester_demandeur/.test(der.tip)); assert(!M.statusInfo({ status: "en_cours", opened_status: "en_cours", drifted: true }).drifted); assert(!M.statusInfo({ status: "a_faire", drifted: true }).drifted); assert.strictEqual(M.statusInfo({}).status, "?"); assert.strictEqual(M.statusInfo(null).status, "?");
  assert.strictEqual(M.worklogProgress({ ref: "RM1", status: "en_cours" }), null, "sans checklist : rien, jamais 0/0"); assert.strictEqual(M.worklogProgress(null), null); assert.strictEqual(M.worklogProgress({ checklist: { done: 0, total: 0, items: [] } }), null);
  const wp = M.worklogProgress({ checklist: { done: 3, total: 6, items: ["reste A", "reste B"] } }); assert(wp.check.done === 3 && wp.check.total === 6 && wp.check.cls === "" && wp.check.items.length === 2); assert.strictEqual(M.worklogProgress({ checklist: { done: 6, total: 6, items: [] } }).check.cls, "ok"); assert.strictEqual(M.worklogProgress({ checklist: { done: 0, total: 4, items: ["a"] } }).check.cls, "warn"); assert(M.worklogProgress({ checklist: { done: 0, total: 60, items: ["a"], truncated: true } }).check.truncated);
  assert.deepStrictEqual(M.worklogProgress({ sub_tasks: [{ rm_id: "2696", status: "a_faire", title: "T2" }] }).subs, [{ rm: "2696", status: "a_faire", title: "T2" }]);
  assert.deepStrictEqual(M.branchesByRm(["2591-x", "2591-y", "sans", "7-z"]), { RM2591: ["2591-x", "2591-y"], RM7: ["7-z"] });
  console.log("✓ modèle (RM2466/2610/2584/2798/2801/2796/2695/2591) : décors, sections, onglets, documents, groupes, étape, dérive, avancement, branches");
  // — lots (RM2786/2720/2823/2719) —
  const CFG = { closable_statuses: ["a_mep", "a_tester_demandeur", "a_tester_dev", "en_mep"], batch_modes: { traiter: { statuses: ["a_faire", "en_cours", "a_corriger"], skip: { a_tester_demandeur: "livré" } }, atester: { statuses: ["en_cours"] }, etudier: { statuses: ["a_etudier_chiffrer"] } } };
  const SEL = [{ rm_id: "1", status: "a_etudier_chiffrer" }, { rm_id: "2", status: "a_faire" }, { rm_id: "3", status: "a_tester_demandeur" }, { rm_id: "4", status: "en_cours" }];
  const nb = M.batchButtons(SEL, ["RM2"], CFG); assert.deepStrictEqual(nb, { traiter: 2, atester: 1, etudier: 1, fermer: 1, mr: 1 }); assert.strictEqual(M.batchButtons(SEL, [], CFG).mr, 0, "merger sans MR ne s'affiche pas"); assert.strictEqual(M.batchButtons([{ rm_id: "9", status: "a_tester_demandeur" }], [], CFG).traiter, 0); const inc = M.batchButtons([{ rm_id: "1", status: "zzz" }], [], CFG); assert(inc.traiter === 1 && inc.fermer === 1, "statut inconnu : compte partout"); assert.deepEqual(M.batchButtons([], [], CFG), { traiter: 0, atester: 0, etudier: 0, fermer: 0, mr: 0 }); assert.doesNotThrow(() => M.batchButtons(null, null, null));
  const pc = M.closeBatchPlan(SEL, CFG); assert(pc.count === 1 && pc.todo[0].rm_id === "3" && pc.skipped.length === 3 && pc.skipped.every(t => t.why) && /livré/.test(pc.skipped.find(t => t.rm_id === "4").why)); assert(M.closeBatchPlan([{ rm_id: "7", status: "zzz" }], CFG).skipped[0].why.includes("zzz"));
  assert(M.BATCH_MODES.atester && M.BATCH_MODES.traiter && M.BATCH_MODES.etudier && M.BATCH_MODES.atester.envoi !== M.BATCH_MODES.traiter.envoi && M.BATCH_MODES.atester.points === false && M.BATCH_MODES.etudier.points === false);
  const RC = { "10": { found: true, client: "acme", project: "boutique", cwd: "/w/acme/boutique" }, "11": { found: true, client: "acme", project: "boutique", cwd: "/w/acme/boutique" }, "20": { found: true, client: "beta", project: "api", cwd: "/w/beta/api" }, "30": { found: false } };
  const homo = M.offloadPlan([{ rm_id: "10" }, { rm_id: "11" }], RC); assert(!homo.mixed && homo.targets.map(t => t.rm_id).join(",") === "10,11" && homo.client === "acme" && homo.project === "boutique" && homo.cwd === "/w/acme/boutique" && homo.anchor === "10");
  const mel = M.offloadPlan([{ rm_id: "10" }, { rm_id: "20" }], RC); assert(mel.mixed && mel.projects.slice().sort().join(" ") === "acme/boutique beta/api"); const inco = M.offloadPlan([{ rm_id: "10" }, { rm_id: "30" }], RC); assert(inco.blocked.map(t => t.rm_id).join(",") === "30" && inco.targets.map(t => t.rm_id).join(",") === "10" && !inco.mixed); assert.strictEqual(M.offloadPlan([{ rm_id: "30" }], RC).anchor, null); assert.strictEqual(M.offloadPlan([{ rm_id: "RM10" }], RC).anchor, "10");
  const scoped = M.scopeItems([{ rm_id: "10", points: ["a", "b"] }, { rm_id: "11", points: ["c"] }], [{ ref: "10", value: "a", checked: true }, { ref: "10", value: "b", checked: false }, { ref: "11", value: "c", checked: true }]); assert.deepStrictEqual(scoped[0].scope, ["a"], "RM2719 : un point décoché restreint la portée"); assert.strictEqual(scoped[1].scope, undefined, "tous cochés = ticket entier");
  const lignes = M.spawnConfirmLines(homo, { engine: "claude", model: "opus" }, { titre: "Ouvrir une session sur ce lot", reste: "⊘ 2 au-delà" }); assert(/Ouvrir une session sur ce lot pour 2 ticket\(s\)/.test(lignes[0]) && lignes.includes("projet : acme / boutique") && lignes.includes("ancrage : RM10") && lignes.includes("moteur : claude  ·  modèle : opus") && lignes.includes("⊘ 2 au-delà"));
  console.log("✓ lots (RM2786/2720/2823/2719) : boutons selon la règle serveur, fermeture avec raisons, embarquement par projet, portée par points");
  // — vue —
  const mr = String(V.MrLine(VM.mrLine({ iid: 571, ref: "RM2720", target: "dev", url: "https://gl.x/g/p/-/merge_requests/571" }))); assert(/!571/.test(mr) && /RM2720/.test(mr) && /→ <span class="pill">dev<\/span>/.test(mr) && /ouvrir ↗/.test(mr) && /data-action="merge-one" data-url="https:\/\/gl.x\/g\/p\/-\/merge_requests\/571" data-iid="571" data-target="dev">⇥ merger</.test(mr) && !/onclick=/.test(mr), "RM2723 : la MR est désignée par son URL");
  const mrNo = String(V.MrLine(VM.mrLine({ iid: 12, target: "dev" }))); assert(!/merge-one/.test(mrNo) && /!12/.test(mrNo), "sans URL : pas de bouton"); assert(/session éteinte/.test(String(V.MrLine(VM.mrLine({ iid: 3, url: "u", alive: false }))))); assert(!/<img|<i>/.test(String(V.MrLine(VM.mrLine({ iid: "<img src=x>", ref: '"><b>', target: "<i>", url: "https://gl.x/9" })))), "iid, ref, cible échappés");
  const W = { found: true, checked_ts: 1000, notifications: [{ level: "critical", kind: "hook", ref: "RM1", message: "boum <b>", ts: "t1" }, { level: "info", message: "ok" }], notifications_done: [{}, {}], mrs_pending: [{ iid: 5, ref: "RM2", url: "https://g/5", target: "dev" }], requests_open: [{ n: 3, text: "fais <x>", ts: "t2" }],
    buckets: { todo: [{ ref: "RM1", status: "a_faire", label: "Un <b>", client: "c", project: "p", checklist: { done: 1, total: 2, items: ["reste"] }, next: "suite", note: "n" }, { ref: "libre-x", status: "?", label: "chantier" }], done: [{ ref: "RM2", status: "a_tester_demandeur", opened_status: "en_cours", drifted: true, client: "c", project: "p" }, { ref: "RM3", status: "ferme", client: "d", project: "q" }] },
    mr_stage: { RM2: { stage: "open", url: "https://g/mr/2", count: 1, mrs: [] } }, docs: { RM1: [["docs/cdc.md", "output"], ["'memory: x.md'", "ref"]] } };
  const pane = (e, sub) => String(V.WorklogPane(new VM.WorklogViewModel(Object.assign({ data: W, attached: "42", branches: ["1-ma-branche", "orpheline"], selected: new Set(["RM1"]), sub: sub || "todo" }, e), { ago: () => "2min" }), { tip: (id) => ' data-tip-rm="' + id + '"', pin: (k, key) => "<pin>" + key + "</pin>", linkify: (s) => "<lk>" + escO(s) + "</lk>" }));
  assert.strictEqual(pane({ attached: null }), "", "sans session : rien");
  let h = pane({});
  assert(/🔔 notifications de la session \(2\) <span class="otag"[^>]*>2 traitées<\/span>/.test(h) && /class="oline oq ounres"[^>]*title="t1">🔴 <span class="otag">critical<\/span><span class="pill">hook<\/span> <b>RM1<\/b> boum &lt;b&gt;/.test(h) && h.indexOf("🔔") < h.indexOf("🔀") && h.indexOf("🔀") < h.indexOf("📥") && h.indexOf("📥") < h.indexOf('class="rsub"'), "RM2466 : incidents, MR, demandes AVANT le travail, échappés");
  assert(/📥 <span class="otag">#3<\/span> fais &lt;x&gt;/.test(h) && /🔀 MR à merger \(1\)/.test(h));
  assert(/<div class="rsub"><button class="active" data-action="sub" data-key="todo">⏳ reste à faire \(2\)<\/button><button class="" data-action="sub" data-key="done">✅ fait \(2\)<\/button><button class="" data-action="sub" data-key="documents">📄 documents \(2\)<\/button><\/div>/.test(h), "RM2610 : sous-onglets par statut + documents");
  assert(/<input type="checkbox"[^>]*data-action="toggle" data-ref="RM1" data-status="a_faire" data-label="Un &lt;b&gt;" checked>/.test(h) && /<pin>1<\/pin><span class="rmref" data-tip-rm="1" data-action="ticket" data-rm="1">RM1<\/span>/.test(h) && /data-action="status" data-ref="RM1"><span class="pill">a_faire<\/span><\/span>/.test(h), "ligne ticket : case cochée, marque, numéro cliquable + infobulle, pastille → menu de statut (RM2888)");
  assert(/<span class="pill" title="branche du ticket">⎇ 1-ma-branche<\/span>/.test(h) && /→ suite/.test(h) && /↳ n/.test(h) && /<span class="pill " title="critères d’acceptation cochés">1\/2 ✓<\/span><span class="wl-crit"[^>]*>☐ reste</.test(h), "RM2591/2695 : branche, suite, note, avancement");
  assert(/<b>libre-x<\/b> <span class="pill">\?<\/span>/.test(h) && !/data-ref="libre-x"[^>]*type="checkbox"/.test(h) && !/data-action="status" data-ref="libre-x"/.test(h), "RM2605/2716/2888 : un chantier libre n'est ni un lien, ni cochable, ni un workflow");
  assert(/🌿 autres branches \(1\)[\s\S]*⎇ orpheline/.test(h), "RM2610 : branches orphelines sous « à faire »"); assert(!/onclick=/.test(h));
  h = pane({}, "done"); assert(/<div class="wlgroup"><div class="wlghead">c \/ p <span class="gcnt">1<\/span><\/div>/.test(h) && /class="wlghead">d \/ q/.test(h), "RM2798 : deux projets → groupes délimités"); assert(/<span class="pill warn" title="Statut modifié hors de cette session : en_cours → a_tester_demandeur">a_tester_demandeur<\/span>/.test(h), "RM2796 : la dérive en couleur, le détail au survol"); assert(/<span class="pill warn" style="cursor:pointer" title="MR ouverte, à merger" data-action="mr-stage" data-url="https:\/\/g\/mr\/2">⇥ MR<\/span>/.test(h), "RM2801 : l'étape de MR sur la ligne");
  h = pane({ data: Object.assign({}, W, { buckets: { todo: [W.buckets.todo[0]] } }) }, "todo"); assert(!/wlghead/.test(h) && /data-ref="RM1"/.test(h), "RM2798 : un seul groupe → pas d'en-tête"); assert(/wlghead">hors projet/.test(pane({}, "todo")), "…un chantier libre à côté d'un ticket de projet forme le groupe « hors projet »");
  h = pane({}, "documents"); assert(/<span class="olink" title="Ouvrir la fiche RM1" data-action="ticket" data-rm="1">RM1<\/span>/.test(h) && /📄 <lk>docs\/cdc.md<\/lk> <span class="pill">output<\/span>/.test(h) && /<lk>memory: x.md<\/lk>/.test(h) && !/'memory/.test(h), "RM2935 : documents cliquables par linkify, quotes YAML retirées");
  h = pane({ data: { found: false, buckets: {} }, branches: [] }); assert(/pas de worklog pour cette session/.test(h)); assert(/aucun ticket ouvert dans cette session/.test(pane({ data: { found: true, buckets: {} }, branches: [] }))); assert(/🌿 autres branches \(1\)/.test(pane({ data: { found: true, buckets: {}, docs: {} }, branches: ["x"] }, "documents")), "seules des branches : l'onglet à faire les accueille (RM2610)");
  const vmF = new VM.WorklogViewModel({ data: W, attached: "42" }, { ago: () => "2min" }); assert.strictEqual(vmF.fresh, "vérifié 2min", "RM2581 : fraîcheur"); assert.strictEqual(new VM.WorklogViewModel({ data: W, attached: null }, { ago: () => "x" }).fresh, "");
  const PLAN = { count: 2, prompt: "consigne <x>", todo: [{ rm_id: "10", status: "a_faire", title: "dev", instruction: "traiter puis livrer", points: ["critère A", 'crit "B"'], points_truncated: true }, { rm_id: "11", status: "a_etudier_chiffrer", title: "étude", instruction: "étudier et chiffrer" }], skipped: [{ rm_id: "12", status: "a_tester_demandeur", title: "chez toi", reason: "attend TON verdict" }] };
  const bp = String(V.BatchPlan(new VM.BatchPlanViewModel(PLAN), { envoi: "▶ envoyer à la session" })); assert(/▶ à traiter \(2\)/.test(bp) && /<b>1\.<\/b> <span class="r-id">RM10/.test(bp) && /traiter puis livrer/.test(bp) && /⊘ écartés \(1\)/.test(bp) && /attend TON verdict/.test(bp) && !/au-delà de 10/.test(bp) && /data-action="send-batch">▶ envoyer à la session</.test(bp) && /data-action="close">annuler/.test(bp) && /consigne &lt;x&gt;/.test(bp));
  assert((bp.match(/type="checkbox" checked/g) || []).length === 2 && /data-ref="10"/.test(bp) && /value="critère A"/.test(bp) && /value="crit &quot;B&quot;"/.test(bp) && /aucun coché = ticket écarté · ⚠ liste de critères incomplète/.test(bp), "RM2719 : points cochés par défaut, échappés, liste tronquée dite");
  assert(/au-delà de 10/.test(String(V.BatchPlan(new VM.BatchPlanViewModel({ todo: Array.from({ length: 12 }, (_, i) => ({ rm_id: String(i) })), skipped: [] }), { envoi: "x" })))); assert(/aucun ticket actionnable/.test(String(V.BatchPlan(new VM.BatchPlanViewModel({ todo: [], skipped: [] }), { envoi: "x" })))); assert(!/<img|<script>/.test(String(V.BatchPlan(new VM.BatchPlanViewModel({ todo: [{ rm_id: "1<b>", status: "<img src=x>", title: "<script>", instruction: "<b>i" }], skipped: [{ rm_id: "2", reason: "<script>" }] }), { envoi: "x" }))));
  const mbDev = String(V.MrBatch(new VM.MrBatchViewModel({ mode: "dev", live: [], skipped: [], runs: [{ rm_ids: ["10"], source: "10-x", target: "dev" }] }))); assert(/10-x → dev/.test(mbDev) && !/promotion emporte/.test(mbDev) && /data-action="send-mr"/.test(mbDev)); const mbProd = String(V.MrBatch(new VM.MrBatchViewModel({ mode: "prod", live: ["11"], skipped: [{ rm_id: "13", reason: "aucune branche" }], runs: [{ rm_ids: ["10", "11"], source: "dev", target: "main" }] }))); assert(/emporte TOUT ce que « dev »/.test(mbProd) && /dev → main/.test(mbProd) && /session encore vivante pour RM11/.test(mbProd) && /⊘ écartés \(1\)/.test(mbProd) && /aucune branche/.test(mbProd)); assert(/rien à merger/.test(String(V.MrBatch(new VM.MrBatchViewModel({ mode: "dev", runs: [] })))));
  const cp = String(V.ClosePlan(M.closeBatchPlan(SEL, CFG))); assert(/Seront fermés \(1\)/.test(cp) && /<b>RM3<\/b>/.test(cp) && /Écartés \(3\)/.test(cp) && /data-action="send-close"/.test(cp) && /pm-task-status-update/.test(cp)); assert(!/send-close/.test(String(V.ClosePlan(M.closeBatchPlan([{ rm_id: "1", status: "a_faire" }], CFG)))), "rien de fermable : pas de bouton");
  console.log("✓ vue : notifications avant le travail, sous-onglets, lignes de ticket complètes, groupes, dérive, étape MR, documents, écrans de lot");
  // — service + contrôleur —
  const calls = []; const repo = { async load(sid, force) { calls.push(["load", sid, !!force]); if (sid === "ko") throw new Error("boom"); return Object.assign({}, W, { rm_id: sid }); }, async batch(body) { calls.push(["batch", JSON.parse(JSON.stringify(body))]); return body.dry_run ? { count: body.items.length, mode: body.mode, todo: body.items.map(it => ({ rm_id: it.rm_id, status: it.status, title: it.title, instruction: "go", points: it.points || [] })), skipped: [], prompt: "consigne serveur" } : { count: body.items.length, mode: body.mode, skipped: [] }; },
    async mrBatch(body) { calls.push(["mrBatch", body]); return body.dry_run ? { mode: body.mode, runs: [{ rm_ids: ["1"], source: "1-x", target: body.mode === "prod" ? "main" : "dev" }], skipped: [], live: [], todo: [{ rm_id: "1" }] } : { results: [1], failed: body.mode === "prod" ? [{ rm_ids: ["1"], source: "dev", target: "main", stdout: "conflit" }] : [] }; }, async mrMerge(url) { calls.push(["merge", url]); return { ok: url !== "https://ko", rc: url === "https://ko" ? 1 : 0, stderr: "refus" }; }, async spawn(body) { calls.push(["spawn", body]); return { ok: true }; } };
  const runs = []; const run = async (name, args) => { runs.push([name, args]); return { ok: args.rm_id !== "3" ? true : false, stderr: "checklist non cochée" }; };
  const svc = new WorklogService({ repo, run });
  await svc.load("42"); assert(svc.data.rm_id === "42" && svc.pending === null); await svc.load("ko"); assert(svc.data.rm_id === "ko" && svc.data.found === false && /boom/.test(svc.data.error), "RM2673 : rm_id même en échec");
  svc.points["RM1"] = { points: ["a", "b"], points_truncated: false }; svc.toggle("RM1", "a_faire", "Un", true); svc.toggle("RM3", "a_tester_demandeur", "Trois", true); assert.deepStrictEqual(svc.selected.map(s => s.rm_id), ["1", "3"]); assert.deepStrictEqual(svc.selected[0].points, ["a", "b"]); svc.toggle("RM3", "", "", false); assert.strictEqual(svc.selection.size, 1);
  svc.data = Object.assign({}, W, { rm_id: "42" }); assert.deepStrictEqual(svc.buttons(CFG), { traiter: 1, atester: 0, etudier: 0, fermer: 0, mr: 0 });
  await svc.planBatch("42", "atester"); assert(calls[calls.length - 1][1].dry_run && calls[calls.length - 1][1].mode === "atester" && calls[calls.length - 1][1].items[0].points.length === 0, "RM2720 : pas de portée par points en mode à tester"); await svc.planBatch("42", "traiter"); assert.deepStrictEqual(calls[calls.length - 1][1].items[0].points, ["a", "b"]);
  const r = await svc.sendBatch("42", [{ ref: "1", value: "a", checked: true }, { ref: "1", value: "b", checked: false }]); assert.deepStrictEqual(calls[calls.length - 1][1].items[0].scope, ["a"], "RM2719 : la portée cochée part") && assert(!calls[calls.length - 1][1].dry_run); assert.strictEqual(svc.selection.size, 0, "l'envoi vide la sélection");
  svc.toggle("RM3", "a_tester_demandeur", "Trois", true); svc.closePlan(CFG); const cr = await svc.sendClose("note", () => {}); assert.deepStrictEqual(cr, { ok: [], ko: [{ rm_id: "3", why: "checklist non cochée" }] }, "RM2786 : un refus est rendu avec sa raison, jamais forcé"); assert.deepStrictEqual(runs[0], ["task-status", { rm_id: "3", status: "ferme", close_reason: "resolu", note: "note" }]);
  console.log("✓ service : chargement tolérant, sélection avec points, boutons, plans dry_run, envoi avec portée, fermetures via pm-task-status-update");
  const body = fakeElement("workbody"), fresh = fakeElement("workfresh"), nav = fakeElement("outnav"); const btnIds = ["batch-etudier-btn", "batch-btn", "batch-atester-btn", "mr-dev-btn", "mr-prod-btn", "batch-close-btn", "batch-offload-btn"]; btnIds.forEach(id => { nav.kids["#" + id] = { style: {}, textContent: "" }; });
  const ev = []; let att = "42"; const modalContent = { boxes: [], querySelectorAll() { return this.boxes; } }; const modal = { open: (t, f, on) => { ev.push(["modal", t]); modal.on = on; modal.frag = String(f); }, close: () => ev.push(["modal-close"]), content: () => modalContent };
  const RCACHE = { "1": { found: true, client: "acme", project: "shop", cwd: "/w/shop", title: "Un" }, "2": { found: true, client: "acme", project: "shop", cwd: "/w/shop" }, "20": { found: true, client: "beta", project: "api", cwd: "/w/api" } };
  const ctr = mountWorklog({ body, fresh, nav }, { service: svc, notify: (m, e) => ev.push(["toast", m, !!e]), ago: () => "1min", attached: () => att, sess: () => ({ "42": { registry: { branches: ["1-br"] } } }), cfg: () => CFG, resolve: () => RCACHE, tipAttr: () => "", pinOf: () => "", linkify: (s) => escO(s),
    openReview: (rm) => ev.push(["review", rm]), openStatusMenu: (ref) => ev.push(["status", ref]), showTicket: (rm) => ev.push(["show", rm]), modal, confirm: () => true, prompt: () => "Testé.", alert: (m) => ev.push(["alert", m]), capture: (t) => ev.push(["capture", t]),
    ticket: { ensureResolved: async (rm) => ev.push(["resolve", rm]) }, launcher: () => ({ engine: "claude", model: "" }), warnSpawn: () => ev.push("warn"), refreshSessions: async () => ev.push("sessions"), attach: (rm) => ev.push(["attach", rm]), forgetOpened: (rm) => ev.push(["forget", rm]), forgetTicketSessions: (rm) => ev.push(["ts", rm]), openExternal: (u) => ev.push(["open", u]), projectWorklog: () => ev.push("proj"), afterLoad: () => ev.push("afterLoad") });
  calls.length = 0; await ctr.load(); assert.deepStrictEqual(calls[0], ["load", "42", false]); assert(/data-key="todo"/.test(body.innerHTML) && fresh.textContent === "vérifié 1min" && ev.includes("afterLoad"), "chargé, rendu, la liste des tickets prévenue (RM2673)");
  await nav.click("reload"); assert(calls.some(c => c[0] === "load" && c[2] === true), "⟳ force la garde serveur");
  ctr.setFromRefresh({ rm_id: "99", found: true, buckets: {} }); assert.strictEqual(ctr.data().rm_id, "42", "un worklog d'une autre session est jeté"); ctr.setFromRefresh({ rm_id: "42", found: true, buckets: { done: [{ ref: "RM9", status: "ferme" }] } }); assert(/data-key="done">✅ fait \(1\)/.test(body.innerHTML), "RM2763 : le composite pousse un worklog frais");
  ctr.setFromRefresh(Object.assign({}, W, { rm_id: "42" })); await body.click("sub", { key: "done" }); assert(/class="active" data-action="sub" data-key="done"/.test(body.innerHTML));
  await body.click("toggle", { ref: "RM1", status: "a_faire", label: "Un" }, { checked: true }); await body.click("toggle", { ref: "RM2", status: "a_tester_demandeur", label: "Deux" }, { checked: true }); assert.strictEqual(ctr.selection().length, 2); assert(nav.kids["#batch-btn"].style.display === "" && nav.kids["#batch-btn"].textContent === "▶ traiter (1)" && nav.kids["#batch-close-btn"].textContent === "✅ fermer (1)" && nav.kids["#batch-offload-btn"].textContent === "⇱ nouvelle session (2)" && nav.kids["#mr-dev-btn"].textContent === "⇥ merger dev (1)" && nav.kids["#batch-etudier-btn"].style.display === "none", "RM2786 : boutons selon la règle, compteurs = ce qui part (une MR ouverte pour RM2, rien à analyser)");
  await body.click("open", { ref: "RM1" }); assert(ev.some(x => x[0] === "review" && x[1] === "1")); await body.click("open", { ref: "libre" }); assert(ev.some(x => x[0] === "toast" && /Chantier hors ticket/.test(x[1]))); await body.click("ticket", { rm: "1" }); assert(ev.some(x => x[0] === "show" && x[1] === "1")); await body.click("status", { ref: "RM1" }); assert(ev.some(x => x[0] === "status" && x[1] === "RM1"), "RM2888"); await body.click("mr-stage", { url: "https://g/mr/2" }); assert(ev.some(x => x[0] === "open" && x[1] === "https://g/mr/2"));
  calls.length = 0; await nav.click("batch", { mode: "traiter" }); assert(calls[0][0] === "batch" && calls[0][1].dry_run && ev.some(x => x[0] === "modal" && /▶ Traiter 2 ticket\(s\) — session 42/.test(x[1])) && /data-action="send-batch"/.test(modal.frag), "RM2716 : récapitulatif dry_run avant tout envoi");
  modalContent.boxes = []; await modal.on("send-batch", { dataset: {} }); await settle(); assert(calls.some(c => c[0] === "batch" && !c[1].dry_run) && ev.some(x => x[0] === "toast" && /2 ticket\(s\) envoyés à la session 42/.test(x[1])) && ev.some(x => x[0] === "modal-close") && calls.some(c => c[0] === "load" && c[2] === true), "envoi puis fermeture et rechargement"); assert.strictEqual(ctr.selection().length, 0);
  await body.click("toggle", { ref: "RM1", status: "a_faire", label: "Un" }, { checked: true }); calls.length = 0; ev.length = 0; await nav.click("mr", { mode: "dev" }); assert(calls[0][0] === "mrBatch" && calls[0][1].dry_run && /merge dans l’intégration \(1\)/.test(modal.frag)); await modal.on("send-mr", { dataset: {} }); await settle(); assert(ev.some(x => x[0] === "toast" && /1 MR mergée/.test(x[1])) && ev.some(x => x[0] === "modal-close"));
  ev.length = 0; await nav.click("mr", { mode: "prod" }); await modal.on("send-mr", { dataset: {} }); await settle(); assert(ev.some(x => x[0] === "toast" && /1 merge\(s\) en échec/.test(x[1]) && x[2]) && ev.some(x => x[0] === "capture" && /Merge — ÉCHEC/.test(x[1])) && !ev.some(x => x[0] === "modal-close"), "RM2720 : l'échec rend la sortie du script, la modale reste");
  await body.click("toggle", { ref: "RM3", status: "a_tester_demandeur", label: "Trois" }, { checked: true }); ev.length = 0; runs.length = 0; await nav.click("close-batch"); assert(ev.some(x => x[0] === "modal" && /✅ Fermer 1 ticket\(s\)/.test(x[1]))); await modal.on("send-close", { dataset: {} }); await settle(); assert(runs.length === 1 && ev.some(x => x[0] === "toast" && /0 fermé\(s\), 1 refusé\(s\)/.test(x[1])) && ev.some(x => x[0] === "modal" && /Fermetures refusées \(1\)/.test(x[1])) && /checklist non cochée/.test(modal.frag), "RM2786 : les refus sont listés avec leur raison");
  ev.length = 0; calls.length = 0; await body.click("merge-one", { url: "https://g/5", iid: "5", target: "dev" }, { disabled: false, textContent: "" }); await settle(); assert(calls.some(c => c[0] === "merge" && c[1] === "https://g/5") && ev.some(x => x[0] === "toast" && /MR !5 mergée/.test(x[1])) && ev.includes("proj"), "RM2723 : merge confirmé, worklog projet rafraîchi"); ev.length = 0; await ctr.mergeOne("https://ko", "6", "dev", null); assert(ev.some(x => x[0] === "capture" && /Merge MR !6 — ÉCHEC/.test(x[1])));
  await body.click("toggle", { ref: "RM1", status: "a_faire", label: "Un" }, { checked: true }); await body.click("toggle", { ref: "RM2", status: "a_tester_demandeur", label: "Deux" }, { checked: true }); ev.length = 0; calls.length = 0; await nav.click("offload"); await settle();
  assert(calls.some(c => c[0] === "batch" && c[1].dry_run && c[1].rm_id === "42") && calls.some(c => c[0] === "spawn" && c[1].rm_id === "1" && c[1].cwd === "/w/shop" && c[1].prompt === "consigne serveur" && c[1].engine === "claude"), "RM2823 : consigne du serveur, session par /spawn, ancrée sur le premier ticket"); assert(ev.some(x => x[0] === "toast" && /2 ticket\(s\) → session karl-RM1/.test(x[1])) && ev.includes("warn") && ev.some(x => x[0] === "ts" && x[1] === "1") && ev.some(x => x[0] === "forget" && x[1] === "2") && ev.includes("sessions"), "…suites : alerte, caches, tickets ouverts, sessions"); assert.strictEqual(ctr.selection().length, 0);
  ev.length = 0; await ctr.spawnBatch([{ rm_id: "1" }, { rm_id: "20" }], null, {}); assert(ev.some(x => x[0] === "alert" && /plusieurs projets/.test(x[1])), "RM2823 : deux projets → refus nommé"); ev.length = 0; await ctr.spawnBatch([{ rm_id: "30" }], null, {}); assert(ev.some(x => x[0] === "alert" && /Aucun de ces tickets/.test(x[1])) && ev.some(x => x[0] === "resolve" && x[1] === "30"), "…un projet non résolu est demandé avant de conclure");
  att = null; await ctr.load(); assert.strictEqual(body.innerHTML, ""); assert.strictEqual(fresh.textContent, "");
  ctr.unmount(); assert.strictEqual(body.listenerCount + nav.listenerCount, 0);
  console.log("✓ contrôleur : chargé/rafraîchi/poussé, sous-onglets, sélection → boutons, lots (traiter, merger, fermer, embarquer) avec récapitulatif, MR mergée, gestes délégués");
  console.log("\nTous les tests du worklog passent.");
})().catch(e => { console.error("✗", e.message); process.exit(1); });
