// views/sessions/Sets — la barre des jeux (options du sélecteur, destinations) et la carte « Sessions enregistrées » (règle, entrées,
// réglages, versions). Gestes en data-action, aucun on*. RM2889.
import { html, raw, attrs } from "../../core/html.js";

const Opt = (o) => html`<option ${attrs({ value: o.value, selected: !!o.selected })}>${o.label}</option>`;
/** RM2446/2452 : les groupes d'options du sélecteur de la barre. */
export function PickerOptions(groups) { return html`${groups.map(g => html`<optgroup label="${g.label}">${g.options.map(Opt)}</optgroup>`)}`; }
/** RM2449 : destinations d'un déplacement. */
export function TargetOptions(targets) { return html`${targets.map(t => html`<option value="${t.value}">${t.label}</option>`)}`; }
/** RM2955 : options de la carte. */
export function EditPickerOptions(opts) { return html`${opts.map(Opt)}`; }

const Select = (id, options, cur) => html`<select id="${id}" style="width:100%"><option value=""${!cur ? raw(" selected") : ""}>— indifférent —</option>${options.map(o => html`<option value="${o.value}"${String(cur || "") === o.value ? raw(" selected") : ""}>${o.label}</option>`)}</select>`;
/** RM2452/RM2741 : le formulaire de règle (création ou édition). */
export function RuleForm(vm) {
  return html`<div style="border:1px solid var(--line);border-radius:6px;padding:8px;margin:6px 0"><div style="font-size:11.5px;margin-bottom:6px">⚙ <b>${vm.title}</b> — ${vm.isNew ? raw("critères vides = jeu <b>manuel</b> (tu le remplis) ; un critère renseigné = jeu <b>dérivé</b>, dont le contenu se calcule") : "son contenu se calcule, toute session qui satisfait la règle y entre d'elle-même"}</div>${vm.isNew ? html`<input id="rf-name" placeholder="Nom du jeu (ex. Chantier Clienta)" style="width:100%;margin-bottom:6px">` : ""}${vm.seedShown ? html`<label style="font-size:11px;display:flex;gap:5px;align-items:center;margin:0 0 6px"><input type="checkbox" id="rf-seed" style="width:auto;margin:0" checked> y placer les ${String(vm.shown)} session(s) affichée(s) <span style="color:var(--muted)">(sans effet sur un jeu dérivé)</span></label>` : ""}<label style="font-size:11px">client${Select("rf-client", vm.clients, vm.rule.client)}</label><label style="font-size:11px">projet${Select("rf-project", vm.projects, vm.rule.project)}</label><label style="font-size:11px">étiquette${Select("rf-tag", vm.tags, vm.rule.tag)}</label><label style="font-size:11px">marque${Select("rf-mark", vm.marks, vm.rule.mark)}</label><label style="font-size:11px">tickets (séparés par des virgules)<input id="rf-tickets" style="width:100%" value="${vm.tickets}"></label><div style="display:flex;gap:6px;margin-top:8px"><button class="mini" data-action="rule-apply" data-new="${vm.isNew ? "1" : ""}">${vm.submitLabel}</button><button class="mini" data-action="rule-cancel">Annuler</button></div></div>`;
}

const Row = (e) => html`<li><b>${e.label}</b> <span style="color:var(--muted)">${e.engine}</span> ${e.state}${e.editable ? html`<span class="tkill" style="float:right" title="Retirer cette session du jeu" data-action="entry-forget" data-sid="${e.sid}">⊖</span><span style="float:right;margin-right:8px;cursor:pointer" title="${e.restartTip}" data-action="entry-restart" data-sid="${e.sid}" data-restart="${e.restart}">${e.restartLabel}</span>` : ""}<br><span style="font-size:11px">${e.title ? e.title : raw('<i style="opacity:.5">sans titre</i>')}</span><br><span style="color:var(--muted);font-size:11px">${e.inactive ? e.inactive + " · " : ""}${e.cwd}</span></li>`;

/** La carte « Sessions enregistrées » (RM2395/2427/2439/2443/2450/2452/2673/2955). */
export function SetCard(vm) {
  if (vm.empty) return html`${vm.newForm ? RuleForm(vm.newForm) : ""}<div class="empty">Jeu « ${vm.label} » vide — ${vm.emptyHint}, ou « ＋ jeu » avec un critère pour un jeu qui se remplit tout seul.</div>`;
  return html`${vm.newForm ? RuleForm(vm.newForm) : ""}${vm.editForm ? RuleForm(vm.editForm) : ""}${vm.derivedHeader !== null ? html`<div style="font-size:11.5px;margin-bottom:6px">⚙ <b>jeu dérivé</b> — ${vm.derivedHeader} <span style="cursor:pointer;text-decoration:underline" data-action="rule-edit">modifier</span> · <span style="cursor:pointer;text-decoration:underline" data-action="materialize">figer</span><br><span style="color:var(--muted)">contenu calculé : rien à curer, et toute session satisfaisant la règle y entre d'elle-même</span></div>` : ""}<div style="color:var(--muted);font-size:11.5px;margin-bottom:6px"><b>${vm.headerLabel}</b> · ${String(vm.count)}${vm.isCurrent ? html` <span style="color:var(--accent)" title="C'est le jeu courant : il gouverne le panneau « ▶ en cours » et reçoit les sessions">● courant</span>` : ""}${vm.truncated ? html` affichée(s) sur <b>${String(vm.total)}</b>` : ""} session(s) · enregistré il y a ${vm.savedAgo} <span style="cursor:pointer" title="Renommer ce jeu (le libellé seul ; la clé interne ne bouge pas)" data-action="rename">✎</span></div><ul class="results">${vm.rows.map(Row)}</ul><div style="color:var(--muted);font-size:11px;margin:8px 0 4px">${vm.autostartNote}</div><label style="display:flex;align-items:center;gap:6px;margin:0 0 6px;font-size:11.5px">Masquer les sessions inactives depuis <input type="number" min="0" max="3650" style="width:60px" value="${String(vm.hideIdleDays)}" data-action="retention"> jour(s) — 0 = ne rien masquer <span style="color:var(--muted)">(masquées, jamais supprimées)</span></label><label style="display:flex;align-items:center;gap:6px;margin:0 0 8px;cursor:pointer"><input type="checkbox" style="width:auto"${vm.spawnPref ? raw(" checked") : ""} data-action="spawn-pref"> Recréer une session neuve si la conversation est perdue</label><div style="display:flex;gap:6px;flex-wrap:wrap"><button data-action="relaunch-card" title="Relance d'un coup les sessions du jeu qui ne tournent PAS (un TUI par session) — sinon, clique une tuile grise pour n'en réveiller qu'une">▶ relancer (${String(vm.relaunchCount)})</button><button class="mini" data-action="history">↩ versions</button><button class="mini" data-action="delete">🗑 Effacer</button></div><div id="set-history"></div>`;
}

/** RM2443 : la liste des versions archivées. */
export function History(vm) {
  if (vm.empty) return html`<div class="empty">Aucune version archivée pour « ${vm.label} » (max ${String(vm.keep)} conservées).</div>`;
  return html`<div style="color:var(--muted);font-size:11.5px;margin:8px 0 4px">Rétablir « ${vm.label} » dans un état précédent :</div><ul class="results">${vm.rows.map(v => html`<li style="cursor:pointer" title="Rétablir cet état — l'état actuel sera lui-même archivé" data-action="restore" data-id="${v.id}">↩ il y a ${v.ago} <span style="color:var(--muted)">— ${String(v.count)} session(s)</span></li>`)}</ul>`;
}
export const Loading = () => html`<div class="empty">chargement…</div>`;
export const ErrorBox = (msg) => html`<div class="empty">${msg}</div>`;
