// views/tickets/NewTicket — le formulaire complet (RM2672/2726/2752). Balisage repris ; gestes en data-*.
import { html } from "../../core/html.js";
const opt = (v, cur) => html`<option value="${v.value || v}"${(v.value || v) === cur ? " selected" : ""}>${v.label || v}</option>`;

export function ProjectRadios(radios) {
  if (!radios.length) return html`<div style="color:var(--muted);font-size:12px">aucun projet pour ce client</div>`;
  return html`${radios.map(r => html`<label><input type="radio" name="ntf-project" value="${r.value}"${r.checked ? " checked" : ""}> ${r.label}</label>`)}`;
}
export function ClientProjectPicker(vm) {
  if (vm.noProjects) return html`<div style="color:var(--muted)">aucun projet connu — le serveur n’en remonte pas.</div>`;
  return html`<div class="row2"><div><label for="ntf-client">Client</label><select id="ntf-client" data-field="client">${vm.clients.map(c => html`<option value="${c}"${c === vm.client ? " selected" : ""}>${c}</option>`)}</select></div><div><label>Projet</label><div class="pradios" id="ntf-projects">${ProjectRadios(vm.radios())}</div></div></div>`;
}
export function NewTicketForm(vm) {
  return html`<h2 style="margin-top:0">＋ Nouveau ticket</h2><div style="max-width:820px"><label for="ntf-title">Titre</label><input id="ntf-title" data-field="title" type="text" placeholder="Ce qu'il faut faire, en une ligne">${ClientProjectPicker(vm)}<div class="row2"><div><label for="ntf-type">Type</label><select id="ntf-type" data-field="type">${vm.types.map(t => opt(t, "feature"))}</select></div><div><label for="ntf-prio">Priorité</label><select id="ntf-prio" data-field="priority">${vm.priorities.map(p => opt(p, "normal"))}</select></div></div><div id="ntf-bugbox" style="display:none"><label for="ntf-bug-steps">Étapes de reproduction <span style="color:var(--danger)">(requis)</span></label><textarea id="ntf-bug-steps" data-field="bug_steps" rows="5" placeholder="1. …&#10;2. …&#10;3. ce qu'on observe, et ce qu'on attendait"></textarea><label for="ntf-bug-repro">Reproductibilité</label><select id="ntf-bug-repro" data-field="bug_reproducibility">${vm.repro.map(v => opt(v, "always"))}</select></div><label for="ntf-tags">Tags <span style="color:var(--muted)">(csv)</span></label><input id="ntf-tags" data-field="tags" type="text" placeholder="cockpit, mail"><label for="ntf-desc">Description</label><textarea id="ntf-desc" data-field="description" rows="12" placeholder="Contexte, ce qui est demandé, ce qui reste à clarifier…"></textarea><details style="margin-top:10px"><summary>Options — test, environnement, estimation</summary><div class="row2"><div><label for="ntf-agent-test">Passe agent-testeur</label><select id="ntf-agent-test" data-field="agent_test">${vm.agentTest.map(v => opt(v, "default"))}</select></div><div><label for="ntf-env">Env cible <span style="color:var(--muted)">(optionnel)</span></label><input id="ntf-env" data-field="target_env" type="text" placeholder="dev, test, prod…"></div></div><div class="row2"><div><label for="ntf-human">Temps humain prévu (min)</label><input id="ntf-human" data-field="est_human_minutes" type="number" min="0"></div><div><label for="ntf-ai">Temps IA prévu (min)</label><input id="ntf-ai" data-field="est_ai_minutes" type="number" min="0"></div></div><label for="ntf-diff">Difficulté</label><select id="ntf-diff" data-field="difficulty"><option value=""></option>${vm.difficulty.map(v => opt(v, ""))}</select></details><button class="primary" id="ntf-btn" style="margin-top:12px" data-action="submit">Créer le ticket</button></div>`;
}
